package hooks

// This file is not generated by Speakeasy and will never be overwritten.
// It implements the BeforeRequest hook that exchanges a refresh token for
// a short-lived bearer token and caches it for the lifetime of the token.

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"time"
)

const (
	defaultRefreshURL = "https://auth.squadcast.com/oauth/access-token"
	refreshPath       = "/oauth/access-token"
)

// ── token cache ──────────────────────────────────────────────────────────────

type accessTokenCache struct {
	mu     sync.Mutex
	token  string
	expiry time.Time
}

func (c *accessTokenCache) get() (string, bool) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.token != "" && time.Now().Before(c.expiry) {
		return c.token, true
	}
	return "", false
}

func (c *accessTokenCache) set(token string, expiry time.Time) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.token = token
	c.expiry = expiry
}

// ── hook ──────────────────────────────────────────────────────────────────────

// AccessTokenHook implements BeforeRequestHook.
// It reads the refresh token from the SDK's security source, exchanges it for
// a bearer token (caching the result), and sets the Authorization header on
// every outgoing request.
type AccessTokenHook struct {
	cache accessTokenCache
}

// compile-time assertion
var _ beforeRequestHook = (*AccessTokenHook)(nil)

func (h *AccessTokenHook) BeforeRequest(hookCtx BeforeRequestContext, req *http.Request) (*http.Request, error) {
	if hookCtx.SecuritySource == nil {
		return req, nil
	}

	// Fetch the security object (components.Security{RefreshToken: ...}) from the source.
	rawSec, err := hookCtx.SecuritySource(hookCtx.Context)
	if err != nil {
		return nil, fmt.Errorf("squadcastsdk: get security source: %w", err)
	}

	// We intentionally avoid importing models/components here to keep the hooks
	// package decoupled. JSON round-trip extracts the refreshToken field regardless
	// of the concrete type returned by the source.
	b, err := json.Marshal(rawSec)
	if err != nil {
		return nil, fmt.Errorf("squadcastsdk: marshal security: %w", err)
	}

	var sec struct {
		RefreshToken string `json:"refreshToken"`
	}
	if err := json.Unmarshal(b, &sec); err != nil {
		return nil, fmt.Errorf("squadcastsdk: unmarshal security: %w", err)
	}

	// Not a refresh-token auth — nothing to do.
	if sec.RefreshToken == "" {
		return req, nil
	}

	refreshURL := resolveRefreshURL(hookCtx.BaseURL, req)

	// Return cached bearer token if still valid.
	if token, ok := h.cache.get(); ok {
		req.Header.Set("Authorization", "Bearer "+token)
		return req, nil
	}

	// Cache miss — fetch a fresh bearer token.
	token, expiry, err := fetchAccessToken(refreshURL, sec.RefreshToken)
	if err != nil {
		return nil, err
	}

	h.cache.set(token, expiry)
	req.Header.Set("Authorization", "Bearer "+token)
	return req, nil
}

func resolveRefreshURL(baseURL string, req *http.Request) string {
	for _, candidate := range []string{baseURL, requestURLString(req)} {
		if candidate == "" {
			continue
		}

		parsedURL, err := url.Parse(candidate)
		if err != nil || parsedURL.Hostname() == "" {
			continue
		}

		authHost := authHostForAPIHost(parsedURL.Hostname())
		if authHost == "" {
			continue
		}

		return (&url.URL{
			Scheme: "https",
			Host:   authHost,
			Path:   refreshPath,
		}).String()
	}

	return defaultRefreshURL
}

func requestURLString(req *http.Request) string {
	if req == nil || req.URL == nil {
		return ""
	}

	return req.URL.String()
}

func authHostForAPIHost(apiHost string) string {
	apiHost = strings.ToLower(strings.TrimSpace(apiHost))
	if apiHost == "" {
		return ""
	}

	if strings.HasPrefix(apiHost, "api.") {
		return "auth." + strings.TrimPrefix(apiHost, "api.")
	}

	return "auth.squadcast.com"
}

// ── token fetch ───────────────────────────────────────────────────────────────

type accessTokenResponse struct {
	Data struct {
		AccessToken string `json:"access_token"`
		ExpiresAt   int64  `json:"expires_at"`
	} `json:"data"`
}

// fetchAccessToken calls the Squadcast auth endpoint and returns the bearer
// token together with its expiry time.
func fetchAccessToken(refreshURL, refreshToken string) (string, time.Time, error) {
	req, err := http.NewRequest(http.MethodGet, refreshURL, nil)
	if err != nil {
		return "", time.Time{}, fmt.Errorf("squadcastsdk: build refresh request: %w", err)
	}
	req.Header.Set("X-Refresh-Token", refreshToken)
	req.Header.Set("Accept", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", time.Time{}, fmt.Errorf("squadcastsdk: refresh request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return "", time.Time{}, fmt.Errorf("squadcastsdk: unexpected status %d from token endpoint", resp.StatusCode)
	}

	var tr accessTokenResponse
	if err := json.NewDecoder(resp.Body).Decode(&tr); err != nil {
		return "", time.Time{}, fmt.Errorf("squadcastsdk: decode token response: %w", err)
	}

	if tr.Data.AccessToken == "" {
		return "", time.Time{}, fmt.Errorf("squadcastsdk: empty access_token in refresh response")
	}

	return tr.Data.AccessToken, time.Unix(tr.Data.ExpiresAt, 0), nil
}
