// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package squadcastsdk

import (
	"github.com/solarwinds/squadcast-sdk-go/internal/config"
	"github.com/solarwinds/squadcast-sdk-go/internal/hooks"
)

type Extensions struct {
	Webhooks *ExtensionsWebhooks
	Msteams  *ExtensionsMsteams

	rootSDK          *SquadcastSDK
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newExtensions(rootSDK *SquadcastSDK, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Extensions {
	return &Extensions{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		Webhooks:         newExtensionsWebhooks(rootSDK, sdkConfig, hooks),
		Msteams:          newExtensionsMsteams(rootSDK, sdkConfig, hooks),
	}
}
