// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package squadcastsdk

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/config"
	"github.com/SquadcastHub/squadcast-sdk-go/internal/hooks"
)

type IncidentActions struct {
	Circleci *Circleci

	rootSDK          *SquadcastSDK
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newIncidentActions(rootSDK *SquadcastSDK, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *IncidentActions {
	return &IncidentActions{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		Circleci:         newCircleci(rootSDK, sdkConfig, hooks),
	}
}
