// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type AptaMarkAsTransientRequest struct {
	IncidentID string `pathParam:"style=simple,explode=false,name=incidentID"`
}

func (a *AptaMarkAsTransientRequest) GetIncidentID() string {
	if a == nil {
		return ""
	}
	return a.IncidentID
}

// AptaMarkAsTransientResponseBody - The request has succeeded.
type AptaMarkAsTransientResponseBody struct {
	Data components.V3IncidentsAptaMessageResponse `json:"data"`
}

func (a *AptaMarkAsTransientResponseBody) GetData() components.V3IncidentsAptaMessageResponse {
	if a == nil {
		return components.V3IncidentsAptaMessageResponse{}
	}
	return a.Data
}

type AptaMarkAsTransientResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *AptaMarkAsTransientResponseBody
}

func (a *AptaMarkAsTransientResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AptaMarkAsTransientResponse) GetObject() *AptaMarkAsTransientResponseBody {
	if a == nil {
		return nil
	}
	return a.Object
}
