// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/solarwinds/squadcast-sdk-go/models/components"
)

type AuditLogsExportAuditLogsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	V3AuditLogsExportAuditLogsResponse *components.V3AuditLogsExportAuditLogsResponse
}

func (a *AuditLogsExportAuditLogsResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuditLogsExportAuditLogsResponse) GetV3AuditLogsExportAuditLogsResponse() *components.V3AuditLogsExportAuditLogsResponse {
	if a == nil {
		return nil
	}
	return a.V3AuditLogsExportAuditLogsResponse
}
