// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/solarwinds/squadcast-sdk-go/models/components"
)

var AuthGetAccessTokenServerList = []string{
	"https://auth.squadcast.com",
	"https://auth.eu.squadcast.com",
}

type AuthGetAccessTokenRequest struct {
	// (Required) Send your refresh token obtained from Squadcast web application.
	XRefreshToken string `header:"style=simple,explode=false,name=X-Refresh-Token"`
}

func (a *AuthGetAccessTokenRequest) GetXRefreshToken() string {
	if a == nil {
		return ""
	}
	return a.XRefreshToken
}

// AuthGetAccessTokenResponseBody - The request has succeeded.
type AuthGetAccessTokenResponseBody struct {
	// Access token response returned by the OAuth endpoint.
	Data components.V3AuthAccessTokenData `json:"data"`
}

func (a *AuthGetAccessTokenResponseBody) GetData() components.V3AuthAccessTokenData {
	if a == nil {
		return components.V3AuthAccessTokenData{}
	}
	return a.Data
}

type AuthGetAccessTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *AuthGetAccessTokenResponseBody
}

func (a *AuthGetAccessTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthGetAccessTokenResponse) GetObject() *AuthGetAccessTokenResponseBody {
	if a == nil {
		return nil
	}
	return a.Object
}
