// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type CommunicationCardsUpdateCommunicationCardRequest struct {
	// Required
	IncidentID                                                  string                                                                 `pathParam:"style=simple,explode=false,name=IncidentId"`
	CommunicationCardID                                         string                                                                 `pathParam:"style=simple,explode=false,name=communicationCardId"`
	V3IncidentsCommunicationCardsUpdateCommunicationCardRequest components.V3IncidentsCommunicationCardsUpdateCommunicationCardRequest `request:"mediaType=application/json"`
}

func (c *CommunicationCardsUpdateCommunicationCardRequest) GetIncidentID() string {
	if c == nil {
		return ""
	}
	return c.IncidentID
}

func (c *CommunicationCardsUpdateCommunicationCardRequest) GetCommunicationCardID() string {
	if c == nil {
		return ""
	}
	return c.CommunicationCardID
}

func (c *CommunicationCardsUpdateCommunicationCardRequest) GetV3IncidentsCommunicationCardsUpdateCommunicationCardRequest() components.V3IncidentsCommunicationCardsUpdateCommunicationCardRequest {
	if c == nil {
		return components.V3IncidentsCommunicationCardsUpdateCommunicationCardRequest{}
	}
	return c.V3IncidentsCommunicationCardsUpdateCommunicationCardRequest
}

// CommunicationCardsUpdateCommunicationCardResponseBody - The request has succeeded.
type CommunicationCardsUpdateCommunicationCardResponseBody struct {
	Data components.V3IncidentsCommunicationCardsCommunicationCardResponse `json:"data"`
}

func (c *CommunicationCardsUpdateCommunicationCardResponseBody) GetData() components.V3IncidentsCommunicationCardsCommunicationCardResponse {
	if c == nil {
		return components.V3IncidentsCommunicationCardsCommunicationCardResponse{}
	}
	return c.Data
}

type CommunicationCardsUpdateCommunicationCardResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *CommunicationCardsUpdateCommunicationCardResponseBody
}

func (c *CommunicationCardsUpdateCommunicationCardResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CommunicationCardsUpdateCommunicationCardResponse) GetObject() *CommunicationCardsUpdateCommunicationCardResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
