// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type CommunicationCardsDeleteCommunicationCardRequest struct {
	// Required
	IncidentID          string `pathParam:"style=simple,explode=false,name=IncidentId"`
	CommunicationCardID string `pathParam:"style=simple,explode=false,name=communicationCardId"`
}

func (c *CommunicationCardsDeleteCommunicationCardRequest) GetIncidentID() string {
	if c == nil {
		return ""
	}
	return c.IncidentID
}

func (c *CommunicationCardsDeleteCommunicationCardRequest) GetCommunicationCardID() string {
	if c == nil {
		return ""
	}
	return c.CommunicationCardID
}

// CommunicationCardsDeleteCommunicationCardResponseBody - The request has succeeded.
type CommunicationCardsDeleteCommunicationCardResponseBody struct {
	Data string `json:"data"`
}

func (c *CommunicationCardsDeleteCommunicationCardResponseBody) GetData() string {
	if c == nil {
		return ""
	}
	return c.Data
}

type CommunicationCardsDeleteCommunicationCardResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *CommunicationCardsDeleteCommunicationCardResponseBody
}

func (c *CommunicationCardsDeleteCommunicationCardResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CommunicationCardsDeleteCommunicationCardResponse) GetObject() *CommunicationCardsDeleteCommunicationCardResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
