// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// CommunicationCardsCreateSlackChannelInCommunicationCardResponseBody - The request has succeeded.
type CommunicationCardsCreateSlackChannelInCommunicationCardResponseBody struct {
	Data components.V3IncidentsCommunicationCardsCommunicationCardResponse `json:"data"`
}

func (c *CommunicationCardsCreateSlackChannelInCommunicationCardResponseBody) GetData() components.V3IncidentsCommunicationCardsCommunicationCardResponse {
	if c == nil {
		return components.V3IncidentsCommunicationCardsCommunicationCardResponse{}
	}
	return c.Data
}

type CommunicationCardsCreateSlackChannelInCommunicationCardResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *CommunicationCardsCreateSlackChannelInCommunicationCardResponseBody
}

func (c *CommunicationCardsCreateSlackChannelInCommunicationCardResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CommunicationCardsCreateSlackChannelInCommunicationCardResponse) GetObject() *CommunicationCardsCreateSlackChannelInCommunicationCardResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
