// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// CommunicationCardsArchiveSlackChannelResponseBody - The request has succeeded.
type CommunicationCardsArchiveSlackChannelResponseBody struct {
	Data components.V3IncidentsCommunicationCardsCommunicationCardResponse `json:"data"`
}

func (c *CommunicationCardsArchiveSlackChannelResponseBody) GetData() components.V3IncidentsCommunicationCardsCommunicationCardResponse {
	if c == nil {
		return components.V3IncidentsCommunicationCardsCommunicationCardResponse{}
	}
	return c.Data
}

type CommunicationCardsArchiveSlackChannelResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *CommunicationCardsArchiveSlackChannelResponseBody
}

func (c *CommunicationCardsArchiveSlackChannelResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CommunicationCardsArchiveSlackChannelResponse) GetObject() *CommunicationCardsArchiveSlackChannelResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
