// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type ComponentsListComponentsRequest struct {
	StatuspageID string `pathParam:"style=simple,explode=false,name=statuspageID"`
}

func (c *ComponentsListComponentsRequest) GetStatuspageID() string {
	if c == nil {
		return ""
	}
	return c.StatuspageID
}

// ComponentsListComponentsResponseBody - The request has succeeded.
type ComponentsListComponentsResponseBody struct {
	Data []components.V4StatusPagesComponentsListComponentsResponse `json:"data"`
}

func (c *ComponentsListComponentsResponseBody) GetData() []components.V4StatusPagesComponentsListComponentsResponse {
	if c == nil {
		return []components.V4StatusPagesComponentsListComponentsResponse{}
	}
	return c.Data
}

type ComponentsListComponentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *ComponentsListComponentsResponseBody
}

func (c *ComponentsListComponentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ComponentsListComponentsResponse) GetObject() *ComponentsListComponentsResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
