// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type ComponentsUpdateComponentByIDRequest struct {
	StatuspageID                                      string                                                       `pathParam:"style=simple,explode=false,name=statuspageID"`
	ComponentID                                       string                                                       `pathParam:"style=simple,explode=false,name=component_id"`
	V4StatusPagesComponentsUpdateComponentByIDRequest components.V4StatusPagesComponentsUpdateComponentByIDRequest `request:"mediaType=application/json"`
}

func (c *ComponentsUpdateComponentByIDRequest) GetStatuspageID() string {
	if c == nil {
		return ""
	}
	return c.StatuspageID
}

func (c *ComponentsUpdateComponentByIDRequest) GetComponentID() string {
	if c == nil {
		return ""
	}
	return c.ComponentID
}

func (c *ComponentsUpdateComponentByIDRequest) GetV4StatusPagesComponentsUpdateComponentByIDRequest() components.V4StatusPagesComponentsUpdateComponentByIDRequest {
	if c == nil {
		return components.V4StatusPagesComponentsUpdateComponentByIDRequest{}
	}
	return c.V4StatusPagesComponentsUpdateComponentByIDRequest
}

// ComponentsUpdateComponentByIDResponseBody - The request has succeeded.
type ComponentsUpdateComponentByIDResponseBody struct {
	Data components.V4StatusPagesComponentsUpdateComponentByIDResponse `json:"data"`
}

func (c *ComponentsUpdateComponentByIDResponseBody) GetData() components.V4StatusPagesComponentsUpdateComponentByIDResponse {
	if c == nil {
		return components.V4StatusPagesComponentsUpdateComponentByIDResponse{}
	}
	return c.Data
}

type ComponentsUpdateComponentByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *ComponentsUpdateComponentByIDResponseBody
}

func (c *ComponentsUpdateComponentByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *ComponentsUpdateComponentByIDResponse) GetObject() *ComponentsUpdateComponentByIDResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
