// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type DeduplicationRulesCreateOrUpdateDeduplicationRulesRequest struct {
	ServiceID                                                   string                                                                 `pathParam:"style=simple,explode=false,name=serviceID"`
	V3ServicesDeduplicationRulesCreateDeduplicationRulesRequest components.V3ServicesDeduplicationRulesCreateDeduplicationRulesRequest `request:"mediaType=application/json"`
}

func (d *DeduplicationRulesCreateOrUpdateDeduplicationRulesRequest) GetServiceID() string {
	if d == nil {
		return ""
	}
	return d.ServiceID
}

func (d *DeduplicationRulesCreateOrUpdateDeduplicationRulesRequest) GetV3ServicesDeduplicationRulesCreateDeduplicationRulesRequest() components.V3ServicesDeduplicationRulesCreateDeduplicationRulesRequest {
	if d == nil {
		return components.V3ServicesDeduplicationRulesCreateDeduplicationRulesRequest{}
	}
	return d.V3ServicesDeduplicationRulesCreateDeduplicationRulesRequest
}

type DeduplicationRulesCreateOrUpdateDeduplicationRulesData struct {
	Rules []components.V3ServicesDeduplicationRulesDeduplicationRuleResponse `json:"rules"`
}

func (d *DeduplicationRulesCreateOrUpdateDeduplicationRulesData) GetRules() []components.V3ServicesDeduplicationRulesDeduplicationRuleResponse {
	if d == nil {
		return []components.V3ServicesDeduplicationRulesDeduplicationRuleResponse{}
	}
	return d.Rules
}

// DeduplicationRulesCreateOrUpdateDeduplicationRulesResponseBody - The request has succeeded and a new resource has been created as a result.
type DeduplicationRulesCreateOrUpdateDeduplicationRulesResponseBody struct {
	Data DeduplicationRulesCreateOrUpdateDeduplicationRulesData `json:"data"`
}

func (d *DeduplicationRulesCreateOrUpdateDeduplicationRulesResponseBody) GetData() DeduplicationRulesCreateOrUpdateDeduplicationRulesData {
	if d == nil {
		return DeduplicationRulesCreateOrUpdateDeduplicationRulesData{}
	}
	return d.Data
}

type DeduplicationRulesCreateOrUpdateDeduplicationRulesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *DeduplicationRulesCreateOrUpdateDeduplicationRulesResponseBody
}

func (d *DeduplicationRulesCreateOrUpdateDeduplicationRulesResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeduplicationRulesCreateOrUpdateDeduplicationRulesResponse) GetObject() *DeduplicationRulesCreateOrUpdateDeduplicationRulesResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
