// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// EscalationPoliciesCreateEscalationPoliciesResponseBody - The request has succeeded and a new resource has been created as a result.
type EscalationPoliciesCreateEscalationPoliciesResponseBody struct {
	// Represents an Escalation Policy in the system.
	Data components.V3EscalationPoliciesEscalationPolicyResponse `json:"data"`
}

func (e *EscalationPoliciesCreateEscalationPoliciesResponseBody) GetData() components.V3EscalationPoliciesEscalationPolicyResponse {
	if e == nil {
		return components.V3EscalationPoliciesEscalationPolicyResponse{}
	}
	return e.Data
}

type EscalationPoliciesCreateEscalationPoliciesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *EscalationPoliciesCreateEscalationPoliciesResponseBody
}

func (e *EscalationPoliciesCreateEscalationPoliciesResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EscalationPoliciesCreateEscalationPoliciesResponse) GetObject() *EscalationPoliciesCreateEscalationPoliciesResponseBody {
	if e == nil {
		return nil
	}
	return e.Object
}
