// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type EscalationPoliciesGetEscalationPolicyByIDRequest struct {
	// (Required) escalation policy ID
	EscalationPolicyID string `pathParam:"style=simple,explode=false,name=escalationPolicyID"`
}

func (e *EscalationPoliciesGetEscalationPolicyByIDRequest) GetEscalationPolicyID() string {
	if e == nil {
		return ""
	}
	return e.EscalationPolicyID
}

// EscalationPoliciesGetEscalationPolicyByIDResponseBody - The request has succeeded.
type EscalationPoliciesGetEscalationPolicyByIDResponseBody struct {
	// Represents an Escalation Policy in the system.
	Data components.V3EscalationPoliciesEscalationPolicyResponse `json:"data"`
}

func (e *EscalationPoliciesGetEscalationPolicyByIDResponseBody) GetData() components.V3EscalationPoliciesEscalationPolicyResponse {
	if e == nil {
		return components.V3EscalationPoliciesEscalationPolicyResponse{}
	}
	return e.Data
}

type EscalationPoliciesGetEscalationPolicyByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *EscalationPoliciesGetEscalationPolicyByIDResponseBody
}

func (e *EscalationPoliciesGetEscalationPolicyByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EscalationPoliciesGetEscalationPolicyByIDResponse) GetObject() *EscalationPoliciesGetEscalationPolicyByIDResponseBody {
	if e == nil {
		return nil
	}
	return e.Object
}
