// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type EscalationPoliciesUpdateEscalationPolicyRequest struct {
	// (Required) escalation policy ID
	EscalationPolicyID string `pathParam:"style=simple,explode=false,name=escalationPolicyID"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	V3EscalationPoliciesUpdateEscalationPolicyRequest any `request:"mediaType=text/plain"`
}

func (e *EscalationPoliciesUpdateEscalationPolicyRequest) GetEscalationPolicyID() string {
	if e == nil {
		return ""
	}
	return e.EscalationPolicyID
}

func (e *EscalationPoliciesUpdateEscalationPolicyRequest) GetV3EscalationPoliciesUpdateEscalationPolicyRequest() any {
	if e == nil {
		return nil
	}
	return e.V3EscalationPoliciesUpdateEscalationPolicyRequest
}

// EscalationPoliciesUpdateEscalationPolicyResponseBody - The request has succeeded.
type EscalationPoliciesUpdateEscalationPolicyResponseBody struct {
	// Represents an Escalation Policy in the system.
	Data components.V3EscalationPoliciesEscalationPolicyResponse `json:"data"`
}

func (e *EscalationPoliciesUpdateEscalationPolicyResponseBody) GetData() components.V3EscalationPoliciesEscalationPolicyResponse {
	if e == nil {
		return components.V3EscalationPoliciesEscalationPolicyResponse{}
	}
	return e.Data
}

type EscalationPoliciesUpdateEscalationPolicyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *EscalationPoliciesUpdateEscalationPolicyResponseBody
}

func (e *EscalationPoliciesUpdateEscalationPolicyResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EscalationPoliciesUpdateEscalationPolicyResponse) GetObject() *EscalationPoliciesUpdateEscalationPolicyResponseBody {
	if e == nil {
		return nil
	}
	return e.Object
}
