// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type ExportRefreshScheduleIcalLinkRequestBody struct {
}

type ExportRefreshScheduleIcalLinkRequest struct {
	ScheduleID  string                                   `pathParam:"style=simple,explode=false,name=scheduleID"`
	MyOnCall    bool                                     `queryParam:"style=form,explode=false,name=myOnCall"`
	RequestBody ExportRefreshScheduleIcalLinkRequestBody `request:"mediaType=application/json"`
}

func (e *ExportRefreshScheduleIcalLinkRequest) GetScheduleID() string {
	if e == nil {
		return ""
	}
	return e.ScheduleID
}

func (e *ExportRefreshScheduleIcalLinkRequest) GetMyOnCall() bool {
	if e == nil {
		return false
	}
	return e.MyOnCall
}

func (e *ExportRefreshScheduleIcalLinkRequest) GetRequestBody() ExportRefreshScheduleIcalLinkRequestBody {
	if e == nil {
		return ExportRefreshScheduleIcalLinkRequestBody{}
	}
	return e.RequestBody
}

// ExportRefreshScheduleIcalLinkResponseBody - The request has succeeded.
type ExportRefreshScheduleIcalLinkResponseBody struct {
	Data components.V4ICalLinkResponse `json:"data"`
}

func (e *ExportRefreshScheduleIcalLinkResponseBody) GetData() components.V4ICalLinkResponse {
	if e == nil {
		return components.V4ICalLinkResponse{}
	}
	return e.Data
}

type ExportRefreshScheduleIcalLinkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *ExportRefreshScheduleIcalLinkResponseBody
}

func (e *ExportRefreshScheduleIcalLinkResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *ExportRefreshScheduleIcalLinkResponse) GetObject() *ExportRefreshScheduleIcalLinkResponseBody {
	if e == nil {
		return nil
	}
	return e.Object
}
