// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// GlobalEventRulesCreateGlobalEventRuleResponseBody - The request has succeeded and a new resource has been created as a result.
type GlobalEventRulesCreateGlobalEventRuleResponseBody struct {
	Data components.V3GlobalEventRulesCreatedGlobalEventRuleResponse `json:"data"`
}

func (g *GlobalEventRulesCreateGlobalEventRuleResponseBody) GetData() components.V3GlobalEventRulesCreatedGlobalEventRuleResponse {
	if g == nil {
		return components.V3GlobalEventRulesCreatedGlobalEventRuleResponse{}
	}
	return g.Data
}

type GlobalEventRulesCreateGlobalEventRuleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *GlobalEventRulesCreateGlobalEventRuleResponseBody
}

func (g *GlobalEventRulesCreateGlobalEventRuleResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GlobalEventRulesCreateGlobalEventRuleResponse) GetObject() *GlobalEventRulesCreateGlobalEventRuleResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
