// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type GlobalEventRulesReorderRulesetRequest struct {
	GerID                                   int64                                              `pathParam:"style=simple,explode=false,name=ger_id"`
	AlertSourceVersion                      string                                             `pathParam:"style=simple,explode=false,name=alert_source_version"`
	AlertSourceShortname                    string                                             `pathParam:"style=simple,explode=false,name=alert_source_shortname"`
	V3GlobalEventRulesReorderRulesetRequest components.V3GlobalEventRulesReorderRulesetRequest `request:"mediaType=application/json"`
}

func (g *GlobalEventRulesReorderRulesetRequest) GetGerID() int64 {
	if g == nil {
		return 0
	}
	return g.GerID
}

func (g *GlobalEventRulesReorderRulesetRequest) GetAlertSourceVersion() string {
	if g == nil {
		return ""
	}
	return g.AlertSourceVersion
}

func (g *GlobalEventRulesReorderRulesetRequest) GetAlertSourceShortname() string {
	if g == nil {
		return ""
	}
	return g.AlertSourceShortname
}

func (g *GlobalEventRulesReorderRulesetRequest) GetV3GlobalEventRulesReorderRulesetRequest() components.V3GlobalEventRulesReorderRulesetRequest {
	if g == nil {
		return components.V3GlobalEventRulesReorderRulesetRequest{}
	}
	return g.V3GlobalEventRulesReorderRulesetRequest
}

// GlobalEventRulesReorderRulesetResponseBody - The request has succeeded.
type GlobalEventRulesReorderRulesetResponseBody struct {
	Data components.V3GlobalEventRulesOrderingResponse `json:"data"`
}

func (g *GlobalEventRulesReorderRulesetResponseBody) GetData() components.V3GlobalEventRulesOrderingResponse {
	if g == nil {
		return components.V3GlobalEventRulesOrderingResponse{}
	}
	return g.Data
}

type GlobalEventRulesReorderRulesetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *GlobalEventRulesReorderRulesetResponseBody
}

func (g *GlobalEventRulesReorderRulesetResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GlobalEventRulesReorderRulesetResponse) GetObject() *GlobalEventRulesReorderRulesetResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
