// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type GlobalEventRulesUpdateRuleByIDRequest struct {
	GerID                               int64                                          `pathParam:"style=simple,explode=false,name=ger_id"`
	AlertSourceVersion                  string                                         `pathParam:"style=simple,explode=false,name=alert_source_version"`
	AlertSourceShortname                string                                         `pathParam:"style=simple,explode=false,name=alert_source_shortname"`
	RuleID                              string                                         `pathParam:"style=simple,explode=false,name=rule_id"`
	V3GlobalEventRulesUpdateRuleRequest components.V3GlobalEventRulesUpdateRuleRequest `request:"mediaType=application/json"`
}

func (g *GlobalEventRulesUpdateRuleByIDRequest) GetGerID() int64 {
	if g == nil {
		return 0
	}
	return g.GerID
}

func (g *GlobalEventRulesUpdateRuleByIDRequest) GetAlertSourceVersion() string {
	if g == nil {
		return ""
	}
	return g.AlertSourceVersion
}

func (g *GlobalEventRulesUpdateRuleByIDRequest) GetAlertSourceShortname() string {
	if g == nil {
		return ""
	}
	return g.AlertSourceShortname
}

func (g *GlobalEventRulesUpdateRuleByIDRequest) GetRuleID() string {
	if g == nil {
		return ""
	}
	return g.RuleID
}

func (g *GlobalEventRulesUpdateRuleByIDRequest) GetV3GlobalEventRulesUpdateRuleRequest() components.V3GlobalEventRulesUpdateRuleRequest {
	if g == nil {
		return components.V3GlobalEventRulesUpdateRuleRequest{}
	}
	return g.V3GlobalEventRulesUpdateRuleRequest
}

// GlobalEventRulesUpdateRuleByIDResponseBody - The request has succeeded.
type GlobalEventRulesUpdateRuleByIDResponseBody struct {
	Data components.V3GlobalEventRulesRulesetRuleResponse `json:"data"`
}

func (g *GlobalEventRulesUpdateRuleByIDResponseBody) GetData() components.V3GlobalEventRulesRulesetRuleResponse {
	if g == nil {
		return components.V3GlobalEventRulesRulesetRuleResponse{}
	}
	return g.Data
}

type GlobalEventRulesUpdateRuleByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *GlobalEventRulesUpdateRuleByIDResponseBody
}

func (g *GlobalEventRulesUpdateRuleByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GlobalEventRulesUpdateRuleByIDResponse) GetObject() *GlobalEventRulesUpdateRuleByIDResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
