// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type GlobalEventRulesDeleteGerRulesetRequest struct {
	GerID                int64  `pathParam:"style=simple,explode=false,name=ger_id"`
	AlertSourceVersion   string `pathParam:"style=simple,explode=false,name=alert_source_version"`
	AlertSourceShortname string `pathParam:"style=simple,explode=false,name=alert_source_shortname"`
}

func (g *GlobalEventRulesDeleteGerRulesetRequest) GetGerID() int64 {
	if g == nil {
		return 0
	}
	return g.GerID
}

func (g *GlobalEventRulesDeleteGerRulesetRequest) GetAlertSourceVersion() string {
	if g == nil {
		return ""
	}
	return g.AlertSourceVersion
}

func (g *GlobalEventRulesDeleteGerRulesetRequest) GetAlertSourceShortname() string {
	if g == nil {
		return ""
	}
	return g.AlertSourceShortname
}

// GlobalEventRulesDeleteGerRulesetResponseBody - There is no content to send for this request, but the headers may be useful.
type GlobalEventRulesDeleteGerRulesetResponseBody struct {
}

type GlobalEventRulesDeleteGerRulesetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (g *GlobalEventRulesDeleteGerRulesetResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GlobalEventRulesDeleteGerRulesetResponse) GetBody() []byte {
	if g == nil {
		return nil
	}
	return g.Body
}
