// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type GlobalEventRulesGetGlobalEventRuleByIDRequest struct {
	GerID int64 `pathParam:"style=simple,explode=false,name=ger_id"`
}

func (g *GlobalEventRulesGetGlobalEventRuleByIDRequest) GetGerID() int64 {
	if g == nil {
		return 0
	}
	return g.GerID
}

// GlobalEventRulesGetGlobalEventRuleByIDResponseBody - The request has succeeded.
type GlobalEventRulesGetGlobalEventRuleByIDResponseBody struct {
	Data components.V3GlobalEventRulesGlobalEventRuleResponse `json:"data"`
}

func (g *GlobalEventRulesGetGlobalEventRuleByIDResponseBody) GetData() components.V3GlobalEventRulesGlobalEventRuleResponse {
	if g == nil {
		return components.V3GlobalEventRulesGlobalEventRuleResponse{}
	}
	return g.Data
}

type GlobalEventRulesGetGlobalEventRuleByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *GlobalEventRulesGetGlobalEventRuleByIDResponseBody
}

func (g *GlobalEventRulesGetGlobalEventRuleByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GlobalEventRulesGetGlobalEventRuleByIDResponse) GetObject() *GlobalEventRulesGetGlobalEventRuleByIDResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
