// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type GlobalOncallReminderRulesGetGlobalOncallReminderRulesRequest struct {
	// required *
	OwnerID string `queryParam:"style=form,explode=true,name=owner_id"`
}

func (g *GlobalOncallReminderRulesGetGlobalOncallReminderRulesRequest) GetOwnerID() string {
	if g == nil {
		return ""
	}
	return g.OwnerID
}

// GlobalOncallReminderRulesGetGlobalOncallReminderRulesResponseBody - The request has succeeded.
type GlobalOncallReminderRulesGetGlobalOncallReminderRulesResponseBody struct {
	Data components.V3GlobalOncallReminderRulesGlobalOncallReminderRuleResponse `json:"data"`
}

func (g *GlobalOncallReminderRulesGetGlobalOncallReminderRulesResponseBody) GetData() components.V3GlobalOncallReminderRulesGlobalOncallReminderRuleResponse {
	if g == nil {
		return components.V3GlobalOncallReminderRulesGlobalOncallReminderRuleResponse{}
	}
	return g.Data
}

type GlobalOncallReminderRulesGetGlobalOncallReminderRulesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *GlobalOncallReminderRulesGetGlobalOncallReminderRulesResponseBody
}

func (g *GlobalOncallReminderRulesGetGlobalOncallReminderRulesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GlobalOncallReminderRulesGetGlobalOncallReminderRulesResponse) GetObject() *GlobalOncallReminderRulesGetGlobalOncallReminderRulesResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
