// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// GlobalOncallReminderRulesCreateGlobalOncallReminderRulesResponseBody - The request has succeeded.
type GlobalOncallReminderRulesCreateGlobalOncallReminderRulesResponseBody struct {
	Data components.V3GlobalOncallReminderRulesGlobalOncallReminderRuleResponse `json:"data"`
}

func (g *GlobalOncallReminderRulesCreateGlobalOncallReminderRulesResponseBody) GetData() components.V3GlobalOncallReminderRulesGlobalOncallReminderRuleResponse {
	if g == nil {
		return components.V3GlobalOncallReminderRulesGlobalOncallReminderRuleResponse{}
	}
	return g.Data
}

type GlobalOncallReminderRulesCreateGlobalOncallReminderRulesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *GlobalOncallReminderRulesCreateGlobalOncallReminderRulesResponseBody
}

func (g *GlobalOncallReminderRulesCreateGlobalOncallReminderRulesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GlobalOncallReminderRulesCreateGlobalOncallReminderRulesResponse) GetObject() *GlobalOncallReminderRulesCreateGlobalOncallReminderRulesResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
