// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type IncidentsIncidentPriorityUpdateRequest struct {
	IncidentID                               string                                              `pathParam:"style=simple,explode=false,name=incidentID"`
	V3IncidentsIncidentPriorityUpdateRequest components.V3IncidentsIncidentPriorityUpdateRequest `request:"mediaType=application/json"`
}

func (i *IncidentsIncidentPriorityUpdateRequest) GetIncidentID() string {
	if i == nil {
		return ""
	}
	return i.IncidentID
}

func (i *IncidentsIncidentPriorityUpdateRequest) GetV3IncidentsIncidentPriorityUpdateRequest() components.V3IncidentsIncidentPriorityUpdateRequest {
	if i == nil {
		return components.V3IncidentsIncidentPriorityUpdateRequest{}
	}
	return i.V3IncidentsIncidentPriorityUpdateRequest
}

// IncidentsIncidentPriorityUpdateResponseBody - The request has succeeded.
type IncidentsIncidentPriorityUpdateResponseBody struct {
	Data components.V3IncidentsIncidentPriorityUpdateResponse `json:"data"`
}

func (i *IncidentsIncidentPriorityUpdateResponseBody) GetData() components.V3IncidentsIncidentPriorityUpdateResponse {
	if i == nil {
		return components.V3IncidentsIncidentPriorityUpdateResponse{}
	}
	return i.Data
}

type IncidentsIncidentPriorityUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *IncidentsIncidentPriorityUpdateResponseBody
}

func (i *IncidentsIncidentPriorityUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IncidentsIncidentPriorityUpdateResponse) GetObject() *IncidentsIncidentPriorityUpdateResponseBody {
	if i == nil {
		return nil
	}
	return i.Object
}
