// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// IncidentsIncidentExportAsyncBody - The body type of the operation request or response.
type IncidentsIncidentExportAsyncBody struct {
	Data components.V3IncidentsIncidentExportAsyncResponse
}

func (i *IncidentsIncidentExportAsyncBody) GetData() components.V3IncidentsIncidentExportAsyncResponse {
	if i == nil {
		return components.V3IncidentsIncidentExportAsyncResponse{}
	}
	return i.Data
}

// IncidentsIncidentExportAsyncResponseBody - The request has been accepted for processing, but processing has not yet completed.
type IncidentsIncidentExportAsyncResponseBody struct {
	// The body type of the operation request or response.
	Body IncidentsIncidentExportAsyncBody
}

func (i *IncidentsIncidentExportAsyncResponseBody) GetBody() IncidentsIncidentExportAsyncBody {
	if i == nil {
		return IncidentsIncidentExportAsyncBody{}
	}
	return i.Body
}

type IncidentsIncidentExportAsyncResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (i *IncidentsIncidentExportAsyncResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IncidentsIncidentExportAsyncResponse) GetBody() []byte {
	if i == nil {
		return nil
	}
	return i.Body
}
