// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type RequestsStatus struct {
}

type IncidentsGetIncidentsStatusByRequestidsMeta struct {
	ErrorCount   int64 `json:"error_count"`
	SuccessCount int64 `json:"success_count"`
}

func (i *IncidentsGetIncidentsStatusByRequestidsMeta) GetErrorCount() int64 {
	if i == nil {
		return 0
	}
	return i.ErrorCount
}

func (i *IncidentsGetIncidentsStatusByRequestidsMeta) GetSuccessCount() int64 {
	if i == nil {
		return 0
	}
	return i.SuccessCount
}

// IncidentsGetIncidentsStatusByRequestidsResponseBody - The request has succeeded.
type IncidentsGetIncidentsStatusByRequestidsResponseBody struct {
	RequestsStatus RequestsStatus                              `json:"requests_status"`
	Meta           IncidentsGetIncidentsStatusByRequestidsMeta `json:"meta"`
}

func (i *IncidentsGetIncidentsStatusByRequestidsResponseBody) GetRequestsStatus() RequestsStatus {
	if i == nil {
		return RequestsStatus{}
	}
	return i.RequestsStatus
}

func (i *IncidentsGetIncidentsStatusByRequestidsResponseBody) GetMeta() IncidentsGetIncidentsStatusByRequestidsMeta {
	if i == nil {
		return IncidentsGetIncidentsStatusByRequestidsMeta{}
	}
	return i.Meta
}

type IncidentsGetIncidentsStatusByRequestidsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *IncidentsGetIncidentsStatusByRequestidsResponseBody
}

func (i *IncidentsGetIncidentsStatusByRequestidsResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IncidentsGetIncidentsStatusByRequestidsResponse) GetObject() *IncidentsGetIncidentsStatusByRequestidsResponseBody {
	if i == nil {
		return nil
	}
	return i.Object
}
