// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// IncidentsBulkAcknowledgeIncidentsResponseBody - The request has succeeded.
type IncidentsBulkAcknowledgeIncidentsResponseBody struct {
	Data string `json:"data"`
}

func (i *IncidentsBulkAcknowledgeIncidentsResponseBody) GetData() string {
	if i == nil {
		return ""
	}
	return i.Data
}

type IncidentsBulkAcknowledgeIncidentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *IncidentsBulkAcknowledgeIncidentsResponseBody
}

func (i *IncidentsBulkAcknowledgeIncidentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IncidentsBulkAcknowledgeIncidentsResponse) GetObject() *IncidentsBulkAcknowledgeIncidentsResponseBody {
	if i == nil {
		return nil
	}
	return i.Object
}
