// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// IncidentsBulkResolveIncidentsResponseBody - The request has succeeded.
type IncidentsBulkResolveIncidentsResponseBody struct {
	Data string `json:"data"`
}

func (i *IncidentsBulkResolveIncidentsResponseBody) GetData() string {
	if i == nil {
		return ""
	}
	return i.Data
}

type IncidentsBulkResolveIncidentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *IncidentsBulkResolveIncidentsResponseBody
}

func (i *IncidentsBulkResolveIncidentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IncidentsBulkResolveIncidentsResponse) GetObject() *IncidentsBulkResolveIncidentsResponseBody {
	if i == nil {
		return nil
	}
	return i.Object
}
