// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type IncidentActionsCreateATicketOnJiraServerRequest struct {
	IncidentID string `pathParam:"style=simple,explode=false,name=incidentID"`
}

func (i *IncidentActionsCreateATicketOnJiraServerRequest) GetIncidentID() string {
	if i == nil {
		return ""
	}
	return i.IncidentID
}

// IncidentActionsCreateATicketOnJiraServerResponseBody - The request has succeeded.
type IncidentActionsCreateATicketOnJiraServerResponseBody struct {
	Data string `json:"data"`
}

func (i *IncidentActionsCreateATicketOnJiraServerResponseBody) GetData() string {
	if i == nil {
		return ""
	}
	return i.Data
}

type IncidentActionsCreateATicketOnJiraServerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *IncidentActionsCreateATicketOnJiraServerResponseBody
}

func (i *IncidentActionsCreateATicketOnJiraServerResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IncidentActionsCreateATicketOnJiraServerResponse) GetObject() *IncidentActionsCreateATicketOnJiraServerResponseBody {
	if i == nil {
		return nil
	}
	return i.Object
}
