// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type IncidentActionsTriggerAWebhookManuallyRequest struct {
	IncidentID     string `pathParam:"style=simple,explode=false,name=incidentID"`
	EventWebhookID string `pathParam:"style=simple,explode=false,name=eventWebhookID"`
}

func (i *IncidentActionsTriggerAWebhookManuallyRequest) GetIncidentID() string {
	if i == nil {
		return ""
	}
	return i.IncidentID
}

func (i *IncidentActionsTriggerAWebhookManuallyRequest) GetEventWebhookID() string {
	if i == nil {
		return ""
	}
	return i.EventWebhookID
}

// IncidentActionsTriggerAWebhookManuallyResponseBody - The request has succeeded.
type IncidentActionsTriggerAWebhookManuallyResponseBody struct {
	// Represents the response structure for triggering a webhook manually.
	Data components.V3IncidentsIncidentActionsWebhookActionResponse `json:"data"`
}

func (i *IncidentActionsTriggerAWebhookManuallyResponseBody) GetData() components.V3IncidentsIncidentActionsWebhookActionResponse {
	if i == nil {
		return components.V3IncidentsIncidentActionsWebhookActionResponse{}
	}
	return i.Data
}

type IncidentActionsTriggerAWebhookManuallyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *IncidentActionsTriggerAWebhookManuallyResponseBody
}

func (i *IncidentActionsTriggerAWebhookManuallyResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IncidentActionsTriggerAWebhookManuallyResponse) GetObject() *IncidentActionsTriggerAWebhookManuallyResponseBody {
	if i == nil {
		return nil
	}
	return i.Object
}
