// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type IssuesGetIssueByIDRequest struct {
	StatuspageID string `pathParam:"style=simple,explode=false,name=statuspageID"`
	IssueID      string `pathParam:"style=simple,explode=false,name=issue_id"`
}

func (i *IssuesGetIssueByIDRequest) GetStatuspageID() string {
	if i == nil {
		return ""
	}
	return i.StatuspageID
}

func (i *IssuesGetIssueByIDRequest) GetIssueID() string {
	if i == nil {
		return ""
	}
	return i.IssueID
}

// IssuesGetIssueByIDResponseBody - The request has succeeded.
type IssuesGetIssueByIDResponseBody struct {
	Data components.V4StatusPagesIssuesGetIssueByIDResponse `json:"data"`
}

func (i *IssuesGetIssueByIDResponseBody) GetData() components.V4StatusPagesIssuesGetIssueByIDResponse {
	if i == nil {
		return components.V4StatusPagesIssuesGetIssueByIDResponse{}
	}
	return i.Data
}

type IssuesGetIssueByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *IssuesGetIssueByIDResponseBody
}

func (i *IssuesGetIssueByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IssuesGetIssueByIDResponse) GetObject() *IssuesGetIssueByIDResponseBody {
	if i == nil {
		return nil
	}
	return i.Object
}
