// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type MaintenancesListMaintenancesRequest struct {
	StatuspageID string `pathParam:"style=simple,explode=false,name=statuspageID"`
	StartTime    string `queryParam:"style=form,explode=false,name=startTime"`
	EndTime      string `queryParam:"style=form,explode=false,name=endTime"`
}

func (m *MaintenancesListMaintenancesRequest) GetStatuspageID() string {
	if m == nil {
		return ""
	}
	return m.StatuspageID
}

func (m *MaintenancesListMaintenancesRequest) GetStartTime() string {
	if m == nil {
		return ""
	}
	return m.StartTime
}

func (m *MaintenancesListMaintenancesRequest) GetEndTime() string {
	if m == nil {
		return ""
	}
	return m.EndTime
}

type MaintenancesListMaintenancesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	V4StatusPagesMaintenancesListMaintenancesResponse *components.V4StatusPagesMaintenancesListMaintenancesResponse
}

func (m *MaintenancesListMaintenancesResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MaintenancesListMaintenancesResponse) GetV4StatusPagesMaintenancesListMaintenancesResponse() *components.V4StatusPagesMaintenancesListMaintenancesResponse {
	if m == nil {
		return nil
	}
	return m.V4StatusPagesMaintenancesListMaintenancesResponse
}
