// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type MaintenancesUpdateMaintenanceByIDRequest struct {
	StatuspageID                                          string                                                           `pathParam:"style=simple,explode=false,name=statuspageID"`
	MaintenanceID                                         string                                                           `pathParam:"style=simple,explode=false,name=maintenance_id"`
	V4StatusPagesMaintenancesUpdateMaintenanceByIDRequest components.V4StatusPagesMaintenancesUpdateMaintenanceByIDRequest `request:"mediaType=application/json"`
}

func (m *MaintenancesUpdateMaintenanceByIDRequest) GetStatuspageID() string {
	if m == nil {
		return ""
	}
	return m.StatuspageID
}

func (m *MaintenancesUpdateMaintenanceByIDRequest) GetMaintenanceID() string {
	if m == nil {
		return ""
	}
	return m.MaintenanceID
}

func (m *MaintenancesUpdateMaintenanceByIDRequest) GetV4StatusPagesMaintenancesUpdateMaintenanceByIDRequest() components.V4StatusPagesMaintenancesUpdateMaintenanceByIDRequest {
	if m == nil {
		return components.V4StatusPagesMaintenancesUpdateMaintenanceByIDRequest{}
	}
	return m.V4StatusPagesMaintenancesUpdateMaintenanceByIDRequest
}

// MaintenancesUpdateMaintenanceByIDResponseBody - The request has succeeded.
type MaintenancesUpdateMaintenanceByIDResponseBody struct {
	Data components.V4StatusPagesMaintenancesUpdateMaintenanceByIDResponse `json:"data"`
}

func (m *MaintenancesUpdateMaintenanceByIDResponseBody) GetData() components.V4StatusPagesMaintenancesUpdateMaintenanceByIDResponse {
	if m == nil {
		return components.V4StatusPagesMaintenancesUpdateMaintenanceByIDResponse{}
	}
	return m.Data
}

type MaintenancesUpdateMaintenanceByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *MaintenancesUpdateMaintenanceByIDResponseBody
}

func (m *MaintenancesUpdateMaintenanceByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MaintenancesUpdateMaintenanceByIDResponse) GetObject() *MaintenancesUpdateMaintenanceByIDResponseBody {
	if m == nil {
		return nil
	}
	return m.Object
}
