// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type MaintenancesCreateMaintenanceRequest struct {
	StatuspageID                                      string                                                       `pathParam:"style=simple,explode=false,name=statuspageID"`
	V4StatusPagesMaintenancesCreateMaintenanceRequest components.V4StatusPagesMaintenancesCreateMaintenanceRequest `request:"mediaType=application/json"`
}

func (m *MaintenancesCreateMaintenanceRequest) GetStatuspageID() string {
	if m == nil {
		return ""
	}
	return m.StatuspageID
}

func (m *MaintenancesCreateMaintenanceRequest) GetV4StatusPagesMaintenancesCreateMaintenanceRequest() components.V4StatusPagesMaintenancesCreateMaintenanceRequest {
	if m == nil {
		return components.V4StatusPagesMaintenancesCreateMaintenanceRequest{}
	}
	return m.V4StatusPagesMaintenancesCreateMaintenanceRequest
}

// MaintenancesCreateMaintenanceResponseBody - The request has succeeded.
type MaintenancesCreateMaintenanceResponseBody struct {
	Data components.V4StatusPagesMaintenancesCreateMaintenanceResponse `json:"data"`
}

func (m *MaintenancesCreateMaintenanceResponseBody) GetData() components.V4StatusPagesMaintenancesCreateMaintenanceResponse {
	if m == nil {
		return components.V4StatusPagesMaintenancesCreateMaintenanceResponse{}
	}
	return m.Data
}

type MaintenancesCreateMaintenanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *MaintenancesCreateMaintenanceResponseBody
}

func (m *MaintenancesCreateMaintenanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MaintenancesCreateMaintenanceResponse) GetObject() *MaintenancesCreateMaintenanceResponseBody {
	if m == nil {
		return nil
	}
	return m.Object
}
