// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type MaintenancesGetMaintenanceByIDRequest struct {
	StatuspageID  string `pathParam:"style=simple,explode=false,name=statuspageID"`
	MaintenanceID string `pathParam:"style=simple,explode=false,name=maintenance_id"`
}

func (m *MaintenancesGetMaintenanceByIDRequest) GetStatuspageID() string {
	if m == nil {
		return ""
	}
	return m.StatuspageID
}

func (m *MaintenancesGetMaintenanceByIDRequest) GetMaintenanceID() string {
	if m == nil {
		return ""
	}
	return m.MaintenanceID
}

// MaintenancesGetMaintenanceByIDResponseBody - The request has succeeded.
type MaintenancesGetMaintenanceByIDResponseBody struct {
	Data components.V4StatusPagesMaintenancesGetMaintenanceByIDResponse `json:"data"`
}

func (m *MaintenancesGetMaintenanceByIDResponseBody) GetData() components.V4StatusPagesMaintenancesGetMaintenanceByIDResponse {
	if m == nil {
		return components.V4StatusPagesMaintenancesGetMaintenanceByIDResponse{}
	}
	return m.Data
}

type MaintenancesGetMaintenanceByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *MaintenancesGetMaintenanceByIDResponseBody
}

func (m *MaintenancesGetMaintenanceByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MaintenancesGetMaintenanceByIDResponse) GetObject() *MaintenancesGetMaintenanceByIDResponseBody {
	if m == nil {
		return nil
	}
	return m.Object
}
