// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// MSTeamsGetMsteamsConfigResponseBody - The request has succeeded.
type MSTeamsGetMsteamsConfigResponseBody struct {
	// The request body for creating or updating an MS Teams extension configuration.
	Data components.V3ExtensionsMSTeamsMSTeamsConfigResponse `json:"data"`
}

func (m *MSTeamsGetMsteamsConfigResponseBody) GetData() components.V3ExtensionsMSTeamsMSTeamsConfigResponse {
	if m == nil {
		return components.V3ExtensionsMSTeamsMSTeamsConfigResponse{}
	}
	return m.Data
}

type MSTeamsGetMsteamsConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *MSTeamsGetMsteamsConfigResponseBody
}

func (m *MSTeamsGetMsteamsConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MSTeamsGetMsteamsConfigResponse) GetObject() *MSTeamsGetMsteamsConfigResponseBody {
	if m == nil {
		return nil
	}
	return m.Object
}
