// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type NotesDeleteNoteRequest struct {
	// Required
	IncidentID string `pathParam:"style=simple,explode=false,name=IncidentId"`
	// Required
	NoteID string `pathParam:"style=simple,explode=false,name=NoteId"`
}

func (n *NotesDeleteNoteRequest) GetIncidentID() string {
	if n == nil {
		return ""
	}
	return n.IncidentID
}

func (n *NotesDeleteNoteRequest) GetNoteID() string {
	if n == nil {
		return ""
	}
	return n.NoteID
}

// NotesDeleteNoteResponseBody - There is no content to send for this request, but the headers may be useful.
type NotesDeleteNoteResponseBody struct {
}

type NotesDeleteNoteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (n *NotesDeleteNoteResponse) GetHTTPMeta() components.HTTPMetadata {
	if n == nil {
		return components.HTTPMetadata{}
	}
	return n.HTTPMeta
}

func (n *NotesDeleteNoteResponse) GetBody() []byte {
	if n == nil {
		return nil
	}
	return n.Body
}
