// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type OverlayGetAllCustomContentTemplateOverlayByServiceRequest struct {
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceID"`
}

func (o *OverlayGetAllCustomContentTemplateOverlayByServiceRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

// OverlayGetAllCustomContentTemplateOverlayByServiceResponseBody - The request has succeeded.
type OverlayGetAllCustomContentTemplateOverlayByServiceResponseBody struct {
	Data []components.V3ServicesOverlayCustomContentOverlayResponse `json:"data"`
}

func (o *OverlayGetAllCustomContentTemplateOverlayByServiceResponseBody) GetData() []components.V3ServicesOverlayCustomContentOverlayResponse {
	if o == nil {
		return []components.V3ServicesOverlayCustomContentOverlayResponse{}
	}
	return o.Data
}

type OverlayGetAllCustomContentTemplateOverlayByServiceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *OverlayGetAllCustomContentTemplateOverlayByServiceResponseBody
}

func (o *OverlayGetAllCustomContentTemplateOverlayByServiceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OverlayGetAllCustomContentTemplateOverlayByServiceResponse) GetObject() *OverlayGetAllCustomContentTemplateOverlayByServiceResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
