// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type OverlayRenderDedupKeyTemplateRequest struct {
	ServiceID                                      string                                                    `pathParam:"style=simple,explode=false,name=serviceID"`
	V3ServicesOverlayRenderDedupKeyTemplateRequest components.V3ServicesOverlayRenderDedupKeyTemplateRequest `request:"mediaType=application/json"`
}

func (o *OverlayRenderDedupKeyTemplateRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *OverlayRenderDedupKeyTemplateRequest) GetV3ServicesOverlayRenderDedupKeyTemplateRequest() components.V3ServicesOverlayRenderDedupKeyTemplateRequest {
	if o == nil {
		return components.V3ServicesOverlayRenderDedupKeyTemplateRequest{}
	}
	return o.V3ServicesOverlayRenderDedupKeyTemplateRequest
}

// OverlayRenderDedupKeyTemplateResponseBody - The request has succeeded.
type OverlayRenderDedupKeyTemplateResponseBody struct {
	Data string `json:"data"`
}

func (o *OverlayRenderDedupKeyTemplateResponseBody) GetData() string {
	if o == nil {
		return ""
	}
	return o.Data
}

type OverlayRenderDedupKeyTemplateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *OverlayRenderDedupKeyTemplateResponseBody
}

func (o *OverlayRenderDedupKeyTemplateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OverlayRenderDedupKeyTemplateResponse) GetObject() *OverlayRenderDedupKeyTemplateResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
