// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type OverridesGetOverrideByIDRequest struct {
	ScheduleID string `pathParam:"style=simple,explode=false,name=scheduleID"`
	OverrideID string `pathParam:"style=simple,explode=false,name=overrideID"`
}

func (o *OverridesGetOverrideByIDRequest) GetScheduleID() string {
	if o == nil {
		return ""
	}
	return o.ScheduleID
}

func (o *OverridesGetOverrideByIDRequest) GetOverrideID() string {
	if o == nil {
		return ""
	}
	return o.OverrideID
}

// OverridesGetOverrideByIDResponseBody - The request has succeeded.
type OverridesGetOverrideByIDResponseBody struct {
	Data components.V4OverrideResponse `json:"data"`
}

func (o *OverridesGetOverrideByIDResponseBody) GetData() components.V4OverrideResponse {
	if o == nil {
		return components.V4OverrideResponse{}
	}
	return o.Data
}

type OverridesGetOverrideByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *OverridesGetOverrideByIDResponseBody
}

func (o *OverridesGetOverrideByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OverridesGetOverrideByIDResponse) GetObject() *OverridesGetOverrideByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
