// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type OverlayRenderCustomContentOverlayRequest struct {
	ServiceID                                          string                                                        `pathParam:"style=simple,explode=false,name=serviceID"`
	V3ServicesOverlayRenderCustomContentOverlayRequest components.V3ServicesOverlayRenderCustomContentOverlayRequest `request:"mediaType=application/json"`
}

func (o *OverlayRenderCustomContentOverlayRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *OverlayRenderCustomContentOverlayRequest) GetV3ServicesOverlayRenderCustomContentOverlayRequest() components.V3ServicesOverlayRenderCustomContentOverlayRequest {
	if o == nil {
		return components.V3ServicesOverlayRenderCustomContentOverlayRequest{}
	}
	return o.V3ServicesOverlayRenderCustomContentOverlayRequest
}

// OverlayRenderCustomContentOverlayResponseBody - The request has succeeded.
type OverlayRenderCustomContentOverlayResponseBody struct {
	Data string `json:"data"`
}

func (o *OverlayRenderCustomContentOverlayResponseBody) GetData() string {
	if o == nil {
		return ""
	}
	return o.Data
}

type OverlayRenderCustomContentOverlayResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *OverlayRenderCustomContentOverlayResponseBody
}

func (o *OverlayRenderCustomContentOverlayResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OverlayRenderCustomContentOverlayResponse) GetObject() *OverlayRenderCustomContentOverlayResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
