// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type OverlayDeleteNotificationTemplateOverlayRequest struct {
	ServiceID   string `pathParam:"style=simple,explode=false,name=serviceID"`
	AlertSource string `pathParam:"style=simple,explode=false,name=alertSource"`
}

func (o *OverlayDeleteNotificationTemplateOverlayRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *OverlayDeleteNotificationTemplateOverlayRequest) GetAlertSource() string {
	if o == nil {
		return ""
	}
	return o.AlertSource
}

// OverlayDeleteNotificationTemplateOverlayResponseBody - There is no content to send for this request, but the headers may be useful.
type OverlayDeleteNotificationTemplateOverlayResponseBody struct {
}

type OverlayDeleteNotificationTemplateOverlayResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (o *OverlayDeleteNotificationTemplateOverlayResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OverlayDeleteNotificationTemplateOverlayResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}
