// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type OverridesCreateScheduleOverrideRequest struct {
	ScheduleID                      string                                     `pathParam:"style=simple,explode=false,name=scheduleID"`
	V4CreateScheduleOverrideRequest components.V4CreateScheduleOverrideRequest `request:"mediaType=application/json"`
}

func (o *OverridesCreateScheduleOverrideRequest) GetScheduleID() string {
	if o == nil {
		return ""
	}
	return o.ScheduleID
}

func (o *OverridesCreateScheduleOverrideRequest) GetV4CreateScheduleOverrideRequest() components.V4CreateScheduleOverrideRequest {
	if o == nil {
		return components.V4CreateScheduleOverrideRequest{}
	}
	return o.V4CreateScheduleOverrideRequest
}

// OverridesCreateScheduleOverrideResponseBody - The request has succeeded and a new resource has been created as a result.
type OverridesCreateScheduleOverrideResponseBody struct {
	Data components.V4OverrideResponse `json:"data"`
}

func (o *OverridesCreateScheduleOverrideResponseBody) GetData() components.V4OverrideResponse {
	if o == nil {
		return components.V4OverrideResponse{}
	}
	return o.Data
}

type OverridesCreateScheduleOverrideResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *OverridesCreateScheduleOverrideResponseBody
}

func (o *OverridesCreateScheduleOverrideResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OverridesCreateScheduleOverrideResponse) GetObject() *OverridesCreateScheduleOverrideResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
