// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type OverridesDeleteScheduleOverrideRequest struct {
	ScheduleID string `pathParam:"style=simple,explode=false,name=scheduleID"`
	OverrideID string `pathParam:"style=simple,explode=false,name=overrideID"`
}

func (o *OverridesDeleteScheduleOverrideRequest) GetScheduleID() string {
	if o == nil {
		return ""
	}
	return o.ScheduleID
}

func (o *OverridesDeleteScheduleOverrideRequest) GetOverrideID() string {
	if o == nil {
		return ""
	}
	return o.OverrideID
}

// OverridesDeleteScheduleOverrideResponseBody - There is no content to send for this request, but the headers may be useful.
type OverridesDeleteScheduleOverrideResponseBody struct {
}

type OverridesDeleteScheduleOverrideResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (o *OverridesDeleteScheduleOverrideResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OverridesDeleteScheduleOverrideResponse) GetBody() []byte {
	if o == nil {
		return nil
	}
	return o.Body
}
