// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type OverlayGetDedupKeyOverlayForAlertSourceRequest struct {
	ServiceID   string `pathParam:"style=simple,explode=false,name=serviceID"`
	AlertSource string `pathParam:"style=simple,explode=false,name=alertSource"`
}

func (o *OverlayGetDedupKeyOverlayForAlertSourceRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *OverlayGetDedupKeyOverlayForAlertSourceRequest) GetAlertSource() string {
	if o == nil {
		return ""
	}
	return o.AlertSource
}

// OverlayGetDedupKeyOverlayForAlertSourceResponseBody - The request has succeeded.
type OverlayGetDedupKeyOverlayForAlertSourceResponseBody struct {
	Data components.V3ServicesOverlayOverlayResponse `json:"data"`
}

func (o *OverlayGetDedupKeyOverlayForAlertSourceResponseBody) GetData() components.V3ServicesOverlayOverlayResponse {
	if o == nil {
		return components.V3ServicesOverlayOverlayResponse{}
	}
	return o.Data
}

type OverlayGetDedupKeyOverlayForAlertSourceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *OverlayGetDedupKeyOverlayForAlertSourceResponseBody
}

func (o *OverlayGetDedupKeyOverlayForAlertSourceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OverlayGetDedupKeyOverlayForAlertSourceResponse) GetObject() *OverlayGetDedupKeyOverlayForAlertSourceResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
