// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type OverlayOptinForKeyBasedDeduplicationForAServiceRequest struct {
	ServiceID                                             string                                                           `pathParam:"style=simple,explode=false,name=serviceID"`
	V3ServicesOverlayOptInForKeyBasedDeduplicationRequest components.V3ServicesOverlayOptInForKeyBasedDeduplicationRequest `request:"mediaType=application/json"`
}

func (o *OverlayOptinForKeyBasedDeduplicationForAServiceRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *OverlayOptinForKeyBasedDeduplicationForAServiceRequest) GetV3ServicesOverlayOptInForKeyBasedDeduplicationRequest() components.V3ServicesOverlayOptInForKeyBasedDeduplicationRequest {
	if o == nil {
		return components.V3ServicesOverlayOptInForKeyBasedDeduplicationRequest{}
	}
	return o.V3ServicesOverlayOptInForKeyBasedDeduplicationRequest
}

// OverlayOptinForKeyBasedDeduplicationForAServiceResponseBody - The request has succeeded.
type OverlayOptinForKeyBasedDeduplicationForAServiceResponseBody struct {
}

type OverlayOptinForKeyBasedDeduplicationForAServiceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *OverlayOptinForKeyBasedDeduplicationForAServiceResponseBody
}

func (o *OverlayOptinForKeyBasedDeduplicationForAServiceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OverlayOptinForKeyBasedDeduplicationForAServiceResponse) GetObject() *OverlayOptinForKeyBasedDeduplicationForAServiceResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
