// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type PostmortemsDeletePostmortemByIncidentRequest struct {
	IncidentID string `pathParam:"style=simple,explode=false,name=incidentID"`
}

func (p *PostmortemsDeletePostmortemByIncidentRequest) GetIncidentID() string {
	if p == nil {
		return ""
	}
	return p.IncidentID
}

// PostmortemsDeletePostmortemByIncidentResponseBody - The request has succeeded.
type PostmortemsDeletePostmortemByIncidentResponseBody struct {
	Data components.V3IncidentsPostmortemsPostmortemResponse `json:"data"`
}

func (p *PostmortemsDeletePostmortemByIncidentResponseBody) GetData() components.V3IncidentsPostmortemsPostmortemResponse {
	if p == nil {
		return components.V3IncidentsPostmortemsPostmortemResponse{}
	}
	return p.Data
}

type PostmortemsDeletePostmortemByIncidentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *PostmortemsDeletePostmortemByIncidentResponseBody
}

func (p *PostmortemsDeletePostmortemByIncidentResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostmortemsDeletePostmortemByIncidentResponse) GetObject() *PostmortemsDeletePostmortemByIncidentResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
