// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type PostmortemsGetPostmortemByIncidentRequest struct {
	IncidentID string `pathParam:"style=simple,explode=false,name=incidentID"`
}

func (p *PostmortemsGetPostmortemByIncidentRequest) GetIncidentID() string {
	if p == nil {
		return ""
	}
	return p.IncidentID
}

// PostmortemsGetPostmortemByIncidentResponseBody - The request has succeeded.
type PostmortemsGetPostmortemByIncidentResponseBody struct {
	Data components.V3IncidentsPostmortemsPostmortemResponse `json:"data"`
}

func (p *PostmortemsGetPostmortemByIncidentResponseBody) GetData() components.V3IncidentsPostmortemsPostmortemResponse {
	if p == nil {
		return components.V3IncidentsPostmortemsPostmortemResponse{}
	}
	return p.Data
}

type PostmortemsGetPostmortemByIncidentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *PostmortemsGetPostmortemByIncidentResponseBody
}

func (p *PostmortemsGetPostmortemByIncidentResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostmortemsGetPostmortemByIncidentResponse) GetObject() *PostmortemsGetPostmortemByIncidentResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
