// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type PostmortemsCreatePostmortemRequest struct {
	IncidentID                                    string                                                   `pathParam:"style=simple,explode=false,name=incidentID"`
	V3IncidentsPostmortemsCreatePostmortemRequest components.V3IncidentsPostmortemsCreatePostmortemRequest `request:"mediaType=application/json"`
}

func (p *PostmortemsCreatePostmortemRequest) GetIncidentID() string {
	if p == nil {
		return ""
	}
	return p.IncidentID
}

func (p *PostmortemsCreatePostmortemRequest) GetV3IncidentsPostmortemsCreatePostmortemRequest() components.V3IncidentsPostmortemsCreatePostmortemRequest {
	if p == nil {
		return components.V3IncidentsPostmortemsCreatePostmortemRequest{}
	}
	return p.V3IncidentsPostmortemsCreatePostmortemRequest
}

// PostmortemsCreatePostmortemBody - The body type of the operation request or response.
type PostmortemsCreatePostmortemBody struct {
	Data components.V3IncidentsPostmortemsPostmortemResponse `json:"data"`
}

func (p *PostmortemsCreatePostmortemBody) GetData() components.V3IncidentsPostmortemsPostmortemResponse {
	if p == nil {
		return components.V3IncidentsPostmortemsPostmortemResponse{}
	}
	return p.Data
}

// PostmortemsCreatePostmortemResponseBody - The request has succeeded and a new resource has been created as a result.
type PostmortemsCreatePostmortemResponseBody struct {
	// The body type of the operation request or response.
	Body PostmortemsCreatePostmortemBody `json:"body"`
}

func (p *PostmortemsCreatePostmortemResponseBody) GetBody() PostmortemsCreatePostmortemBody {
	if p == nil {
		return PostmortemsCreatePostmortemBody{}
	}
	return p.Body
}

type PostmortemsCreatePostmortemResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *PostmortemsCreatePostmortemResponseBody
}

func (p *PostmortemsCreatePostmortemResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostmortemsCreatePostmortemResponse) GetObject() *PostmortemsCreatePostmortemResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
