// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type RotationsCreateRotationRequest struct {
	ScheduleID              string                             `pathParam:"style=simple,explode=false,name=scheduleID"`
	V4CreateRotationRequest components.V4CreateRotationRequest `request:"mediaType=application/json"`
}

func (r *RotationsCreateRotationRequest) GetScheduleID() string {
	if r == nil {
		return ""
	}
	return r.ScheduleID
}

func (r *RotationsCreateRotationRequest) GetV4CreateRotationRequest() components.V4CreateRotationRequest {
	if r == nil {
		return components.V4CreateRotationRequest{}
	}
	return r.V4CreateRotationRequest
}

// RotationsCreateRotationResponseBody - The request has succeeded and a new resource has been created as a result.
type RotationsCreateRotationResponseBody struct {
	Data components.V4RotationResponse `json:"data"`
}

func (r *RotationsCreateRotationResponseBody) GetData() components.V4RotationResponse {
	if r == nil {
		return components.V4RotationResponse{}
	}
	return r.Data
}

type RotationsCreateRotationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *RotationsCreateRotationResponseBody
}

func (r *RotationsCreateRotationResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RotationsCreateRotationResponse) GetObject() *RotationsCreateRotationResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
