// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type RotationsUpdateRotationRequest struct {
	ScheduleID              string                             `pathParam:"style=simple,explode=false,name=scheduleID"`
	RotationID              string                             `pathParam:"style=simple,explode=false,name=rotationID"`
	V4UpdateRotationRequest components.V4UpdateRotationRequest `request:"mediaType=application/json"`
}

func (r *RotationsUpdateRotationRequest) GetScheduleID() string {
	if r == nil {
		return ""
	}
	return r.ScheduleID
}

func (r *RotationsUpdateRotationRequest) GetRotationID() string {
	if r == nil {
		return ""
	}
	return r.RotationID
}

func (r *RotationsUpdateRotationRequest) GetV4UpdateRotationRequest() components.V4UpdateRotationRequest {
	if r == nil {
		return components.V4UpdateRotationRequest{}
	}
	return r.V4UpdateRotationRequest
}

// RotationsUpdateRotationResponseBody - The request has succeeded.
type RotationsUpdateRotationResponseBody struct {
	Data components.V4RotationResponse `json:"data"`
}

func (r *RotationsUpdateRotationResponseBody) GetData() components.V4RotationResponse {
	if r == nil {
		return components.V4RotationResponse{}
	}
	return r.Data
}

type RotationsUpdateRotationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *RotationsUpdateRotationResponseBody
}

func (r *RotationsUpdateRotationResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RotationsUpdateRotationResponse) GetObject() *RotationsUpdateRotationResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
