// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type RoutingRulesCreateOrUpdateRoutingRulesRequest struct {
	ServiceID                                               string                                                             `pathParam:"style=simple,explode=false,name=serviceID"`
	V3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest components.V3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest `request:"mediaType=application/json"`
}

func (r *RoutingRulesCreateOrUpdateRoutingRulesRequest) GetServiceID() string {
	if r == nil {
		return ""
	}
	return r.ServiceID
}

func (r *RoutingRulesCreateOrUpdateRoutingRulesRequest) GetV3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest() components.V3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest {
	if r == nil {
		return components.V3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest{}
	}
	return r.V3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest
}

type RoutingRulesCreateOrUpdateRoutingRulesData struct {
	Rules []components.V3ServicesRoutingRulesRoutingRuleResponse `json:"rules"`
}

func (r *RoutingRulesCreateOrUpdateRoutingRulesData) GetRules() []components.V3ServicesRoutingRulesRoutingRuleResponse {
	if r == nil {
		return []components.V3ServicesRoutingRulesRoutingRuleResponse{}
	}
	return r.Rules
}

// RoutingRulesCreateOrUpdateRoutingRulesResponseBody - The request has succeeded and a new resource has been created as a result.
type RoutingRulesCreateOrUpdateRoutingRulesResponseBody struct {
	Data RoutingRulesCreateOrUpdateRoutingRulesData `json:"data"`
}

func (r *RoutingRulesCreateOrUpdateRoutingRulesResponseBody) GetData() RoutingRulesCreateOrUpdateRoutingRulesData {
	if r == nil {
		return RoutingRulesCreateOrUpdateRoutingRulesData{}
	}
	return r.Data
}

type RoutingRulesCreateOrUpdateRoutingRulesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *RoutingRulesCreateOrUpdateRoutingRulesResponseBody
}

func (r *RoutingRulesCreateOrUpdateRoutingRulesResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RoutingRulesCreateOrUpdateRoutingRulesResponse) GetObject() *RoutingRulesCreateOrUpdateRoutingRulesResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
