// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type RunbooksRemoveRunbookRequest struct {
	RunbookID string `pathParam:"style=simple,explode=false,name=runbookID"`
}

func (r *RunbooksRemoveRunbookRequest) GetRunbookID() string {
	if r == nil {
		return ""
	}
	return r.RunbookID
}

// RunbooksRemoveRunbookResponseBody - There is no content to send for this request, but the headers may be useful.
type RunbooksRemoveRunbookResponseBody struct {
}

type RunbooksRemoveRunbookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (r *RunbooksRemoveRunbookResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RunbooksRemoveRunbookResponse) GetBody() []byte {
	if r == nil {
		return nil
	}
	return r.Body
}
