// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type RunbooksAttachRunbooksRequest struct {
	IncidentID                               string                                              `pathParam:"style=simple,explode=false,name=IncidentId"`
	V3IncidentsRunbooksAttachRunbooksRequest components.V3IncidentsRunbooksAttachRunbooksRequest `request:"mediaType=application/json"`
}

func (r *RunbooksAttachRunbooksRequest) GetIncidentID() string {
	if r == nil {
		return ""
	}
	return r.IncidentID
}

func (r *RunbooksAttachRunbooksRequest) GetV3IncidentsRunbooksAttachRunbooksRequest() components.V3IncidentsRunbooksAttachRunbooksRequest {
	if r == nil {
		return components.V3IncidentsRunbooksAttachRunbooksRequest{}
	}
	return r.V3IncidentsRunbooksAttachRunbooksRequest
}

// RunbooksAttachRunbooksResponseBody - The request has succeeded and a new resource has been created as a result.
type RunbooksAttachRunbooksResponseBody struct {
	Data []components.V3IncidentsRunbooksRunbookResponse `json:"data"`
}

func (r *RunbooksAttachRunbooksResponseBody) GetData() []components.V3IncidentsRunbooksRunbookResponse {
	if r == nil {
		return []components.V3IncidentsRunbooksRunbookResponse{}
	}
	return r.Data
}

type RunbooksAttachRunbooksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *RunbooksAttachRunbooksResponseBody
}

func (r *RunbooksAttachRunbooksResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RunbooksAttachRunbooksResponse) GetObject() *RunbooksAttachRunbooksResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
