// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type SchedulesDeleteScheduleRequest struct {
	ScheduleID string `pathParam:"style=simple,explode=false,name=scheduleID"`
}

func (s *SchedulesDeleteScheduleRequest) GetScheduleID() string {
	if s == nil {
		return ""
	}
	return s.ScheduleID
}

// SchedulesDeleteScheduleResponseBody - There is no content to send for this request, but the headers may be useful.
type SchedulesDeleteScheduleResponseBody struct {
}

type SchedulesDeleteScheduleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (s *SchedulesDeleteScheduleResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SchedulesDeleteScheduleResponse) GetBody() []byte {
	if s == nil {
		return nil
	}
	return s.Body
}
