// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type SchedulesUpdateScheduleRequest struct {
	ScheduleID              string                             `pathParam:"style=simple,explode=false,name=scheduleID"`
	V4UpdateScheduleRequest components.V4UpdateScheduleRequest `request:"mediaType=application/json"`
}

func (s *SchedulesUpdateScheduleRequest) GetScheduleID() string {
	if s == nil {
		return ""
	}
	return s.ScheduleID
}

func (s *SchedulesUpdateScheduleRequest) GetV4UpdateScheduleRequest() components.V4UpdateScheduleRequest {
	if s == nil {
		return components.V4UpdateScheduleRequest{}
	}
	return s.V4UpdateScheduleRequest
}

// SchedulesUpdateScheduleResponseBody - The request has succeeded.
type SchedulesUpdateScheduleResponseBody struct {
	Data components.V4ScheduleResponse `json:"data"`
}

func (s *SchedulesUpdateScheduleResponseBody) GetData() components.V4ScheduleResponse {
	if s == nil {
		return components.V4ScheduleResponse{}
	}
	return s.Data
}

type SchedulesUpdateScheduleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *SchedulesUpdateScheduleResponseBody
}

func (s *SchedulesUpdateScheduleResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SchedulesUpdateScheduleResponse) GetObject() *SchedulesUpdateScheduleResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
