// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type Action string

const (
	ActionPause  Action = "pause"
	ActionResume Action = "resume"
)

func (e Action) ToPointer() *Action {
	return &e
}
func (e *Action) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pause":
		fallthrough
	case "resume":
		*e = Action(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Action: %v", v)
	}
}

type SchedulesPauseresumeScheduleRequestBody struct {
	Action *Action `json:"action,omitempty"`
}

func (s *SchedulesPauseresumeScheduleRequestBody) GetAction() *Action {
	if s == nil {
		return nil
	}
	return s.Action
}

type SchedulesPauseresumeScheduleRequest struct {
	ScheduleID  string                                  `pathParam:"style=simple,explode=false,name=scheduleID"`
	RequestBody SchedulesPauseresumeScheduleRequestBody `request:"mediaType=application/json"`
}

func (s *SchedulesPauseresumeScheduleRequest) GetScheduleID() string {
	if s == nil {
		return ""
	}
	return s.ScheduleID
}

func (s *SchedulesPauseresumeScheduleRequest) GetRequestBody() SchedulesPauseresumeScheduleRequestBody {
	if s == nil {
		return SchedulesPauseresumeScheduleRequestBody{}
	}
	return s.RequestBody
}

// SchedulesPauseresumeScheduleResponseBody - The request has succeeded.
type SchedulesPauseresumeScheduleResponseBody struct {
	Data components.V4PauseResumeScheduleResponse `json:"data"`
}

func (s *SchedulesPauseresumeScheduleResponseBody) GetData() components.V4PauseResumeScheduleResponse {
	if s == nil {
		return components.V4PauseResumeScheduleResponse{}
	}
	return s.Data
}

type SchedulesPauseresumeScheduleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *SchedulesPauseresumeScheduleResponseBody
}

func (s *SchedulesPauseresumeScheduleResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SchedulesPauseresumeScheduleResponse) GetObject() *SchedulesPauseresumeScheduleResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
