// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type ServicesCreateOrUpdateIAGConfigRequest struct {
	ServiceID                  string                                `pathParam:"style=simple,explode=false,name=serviceID"`
	V3ServicesIAGConfigRequest components.V3ServicesIAGConfigRequest `request:"mediaType=application/json"`
}

func (s *ServicesCreateOrUpdateIAGConfigRequest) GetServiceID() string {
	if s == nil {
		return ""
	}
	return s.ServiceID
}

func (s *ServicesCreateOrUpdateIAGConfigRequest) GetV3ServicesIAGConfigRequest() components.V3ServicesIAGConfigRequest {
	if s == nil {
		return components.V3ServicesIAGConfigRequest{}
	}
	return s.V3ServicesIAGConfigRequest
}

type ServicesCreateOrUpdateIAGConfigData struct {
	Msg string `json:"msg"`
}

func (s *ServicesCreateOrUpdateIAGConfigData) GetMsg() string {
	if s == nil {
		return ""
	}
	return s.Msg
}

// ServicesCreateOrUpdateIAGConfigResponseBody - The request has succeeded.
type ServicesCreateOrUpdateIAGConfigResponseBody struct {
	Data ServicesCreateOrUpdateIAGConfigData `json:"data"`
}

func (s *ServicesCreateOrUpdateIAGConfigResponseBody) GetData() ServicesCreateOrUpdateIAGConfigData {
	if s == nil {
		return ServicesCreateOrUpdateIAGConfigData{}
	}
	return s.Data
}

type ServicesCreateOrUpdateIAGConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *ServicesCreateOrUpdateIAGConfigResponseBody
}

func (s *ServicesCreateOrUpdateIAGConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *ServicesCreateOrUpdateIAGConfigResponse) GetObject() *ServicesCreateOrUpdateIAGConfigResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
