// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type ServicesCreateOrUpdateAPTAConfigRequest struct {
	ServiceID                   string                                 `pathParam:"style=simple,explode=false,name=serviceID"`
	V3ServicesAPTAConfigRequest components.V3ServicesAPTAConfigRequest `request:"mediaType=application/json"`
}

func (s *ServicesCreateOrUpdateAPTAConfigRequest) GetServiceID() string {
	if s == nil {
		return ""
	}
	return s.ServiceID
}

func (s *ServicesCreateOrUpdateAPTAConfigRequest) GetV3ServicesAPTAConfigRequest() components.V3ServicesAPTAConfigRequest {
	if s == nil {
		return components.V3ServicesAPTAConfigRequest{}
	}
	return s.V3ServicesAPTAConfigRequest
}

type ServicesCreateOrUpdateAPTAConfigData struct {
	Msg string `json:"msg"`
}

func (s *ServicesCreateOrUpdateAPTAConfigData) GetMsg() string {
	if s == nil {
		return ""
	}
	return s.Msg
}

// ServicesCreateOrUpdateAPTAConfigResponseBody - The request has succeeded.
type ServicesCreateOrUpdateAPTAConfigResponseBody struct {
	Data ServicesCreateOrUpdateAPTAConfigData `json:"data"`
}

func (s *ServicesCreateOrUpdateAPTAConfigResponseBody) GetData() ServicesCreateOrUpdateAPTAConfigData {
	if s == nil {
		return ServicesCreateOrUpdateAPTAConfigData{}
	}
	return s.Data
}

type ServicesCreateOrUpdateAPTAConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *ServicesCreateOrUpdateAPTAConfigResponseBody
}

func (s *ServicesCreateOrUpdateAPTAConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *ServicesCreateOrUpdateAPTAConfigResponse) GetObject() *ServicesCreateOrUpdateAPTAConfigResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
