// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type SLOMarkSLOAffectedRequest struct {
	SloID                       int64                                  `pathParam:"style=simple,explode=false,name=sloID"`
	OwnerID                     string                                 `queryParam:"style=form,explode=true,name=owner_id"`
	V3SLOMarkSLOAffectedRequest components.V3SLOMarkSLOAffectedRequest `request:"mediaType=application/json"`
}

func (s *SLOMarkSLOAffectedRequest) GetSloID() int64 {
	if s == nil {
		return 0
	}
	return s.SloID
}

func (s *SLOMarkSLOAffectedRequest) GetOwnerID() string {
	if s == nil {
		return ""
	}
	return s.OwnerID
}

func (s *SLOMarkSLOAffectedRequest) GetV3SLOMarkSLOAffectedRequest() components.V3SLOMarkSLOAffectedRequest {
	if s == nil {
		return components.V3SLOMarkSLOAffectedRequest{}
	}
	return s.V3SLOMarkSLOAffectedRequest
}

type SLOMarkSLOAffectedData struct {
	SloViolatingIncident components.V3SLOSLOViolatingIncidentResponse `json:"slo_violating_incident"`
}

func (s *SLOMarkSLOAffectedData) GetSloViolatingIncident() components.V3SLOSLOViolatingIncidentResponse {
	if s == nil {
		return components.V3SLOSLOViolatingIncidentResponse{}
	}
	return s.SloViolatingIncident
}

// SLOMarkSLOAffectedResponseBody - The request has succeeded and a new resource has been created as a result.
type SLOMarkSLOAffectedResponseBody struct {
	Data SLOMarkSLOAffectedData `json:"data"`
}

func (s *SLOMarkSLOAffectedResponseBody) GetData() SLOMarkSLOAffectedData {
	if s == nil {
		return SLOMarkSLOAffectedData{}
	}
	return s.Data
}

type SLOMarkSLOAffectedResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *SLOMarkSLOAffectedResponseBody
}

func (s *SLOMarkSLOAffectedResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SLOMarkSLOAffectedResponse) GetObject() *SLOMarkSLOAffectedResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
