// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type SLORemoveSLORequest struct {
	SloID   int64  `pathParam:"style=simple,explode=false,name=sloID"`
	OwnerID string `queryParam:"style=form,explode=true,name=owner_id"`
}

func (s *SLORemoveSLORequest) GetSloID() int64 {
	if s == nil {
		return 0
	}
	return s.SloID
}

func (s *SLORemoveSLORequest) GetOwnerID() string {
	if s == nil {
		return ""
	}
	return s.OwnerID
}

// SLORemoveSLOResponseBody - The request has succeeded.
type SLORemoveSLOResponseBody struct {
	Data components.V3SLOSLOResponse `json:"data"`
}

func (s *SLORemoveSLOResponseBody) GetData() components.V3SLOSLOResponse {
	if s == nil {
		return components.V3SLOSLOResponse{}
	}
	return s.Data
}

type SLORemoveSLOResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *SLORemoveSLOResponseBody
}

func (s *SLORemoveSLOResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SLORemoveSLOResponse) GetObject() *SLORemoveSLOResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
