// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type SquadsDeleteSquadRequest struct {
	SquadID string `pathParam:"style=simple,explode=false,name=squadID"`
}

func (s *SquadsDeleteSquadRequest) GetSquadID() string {
	if s == nil {
		return ""
	}
	return s.SquadID
}

// SquadsDeleteSquadResponseBody - There is no content to send for this request, but the headers may be useful.
type SquadsDeleteSquadResponseBody struct {
}

type SquadsDeleteSquadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (s *SquadsDeleteSquadResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SquadsDeleteSquadResponse) GetBody() []byte {
	if s == nil {
		return nil
	}
	return s.Body
}
