// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type SquadsGetSquadByIDRequest struct {
	SquadID string `pathParam:"style=simple,explode=false,name=squadID"`
}

func (s *SquadsGetSquadByIDRequest) GetSquadID() string {
	if s == nil {
		return ""
	}
	return s.SquadID
}

// SquadsGetSquadByIDResponseBody - The request has succeeded.
type SquadsGetSquadByIDResponseBody struct {
	Data components.V4SquadsSquadResponse `json:"data"`
}

func (s *SquadsGetSquadByIDResponseBody) GetData() components.V4SquadsSquadResponse {
	if s == nil {
		return components.V4SquadsSquadResponse{}
	}
	return s.Data
}

type SquadsGetSquadByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *SquadsGetSquadByIDResponseBody
}

func (s *SquadsGetSquadByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SquadsGetSquadByIDResponse) GetObject() *SquadsGetSquadByIDResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
