// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type StatusPagesUpdateStatusPageByIDRequest struct {
	StatuspageID                             string                                              `pathParam:"style=simple,explode=false,name=statuspageID"`
	V4StatusPagesUpdateStatusPageByIDRequest components.V4StatusPagesUpdateStatusPageByIDRequest `request:"mediaType=application/json"`
}

func (s *StatusPagesUpdateStatusPageByIDRequest) GetStatuspageID() string {
	if s == nil {
		return ""
	}
	return s.StatuspageID
}

func (s *StatusPagesUpdateStatusPageByIDRequest) GetV4StatusPagesUpdateStatusPageByIDRequest() components.V4StatusPagesUpdateStatusPageByIDRequest {
	if s == nil {
		return components.V4StatusPagesUpdateStatusPageByIDRequest{}
	}
	return s.V4StatusPagesUpdateStatusPageByIDRequest
}

// StatusPagesUpdateStatusPageByIDResponseBody - The request has succeeded.
type StatusPagesUpdateStatusPageByIDResponseBody struct {
	Data components.V4StatusPagesUpdateStatusPageByIDResponse `json:"data"`
}

func (s *StatusPagesUpdateStatusPageByIDResponseBody) GetData() components.V4StatusPagesUpdateStatusPageByIDResponse {
	if s == nil {
		return components.V4StatusPagesUpdateStatusPageByIDResponse{}
	}
	return s.Data
}

type StatusPagesUpdateStatusPageByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *StatusPagesUpdateStatusPageByIDResponseBody
}

func (s *StatusPagesUpdateStatusPageByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StatusPagesUpdateStatusPageByIDResponse) GetObject() *StatusPagesUpdateStatusPageByIDResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
