// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type StatusPagesListSubscribersRequest struct {
	StatuspageID string `pathParam:"style=simple,explode=false,name=statuspageID"`
}

func (s *StatusPagesListSubscribersRequest) GetStatuspageID() string {
	if s == nil {
		return ""
	}
	return s.StatuspageID
}

type StatusPagesListSubscribersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	V4StatusPagesListSubscribersResponse *components.V4StatusPagesListSubscribersResponse
}

func (s *StatusPagesListSubscribersResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StatusPagesListSubscribersResponse) GetV4StatusPagesListSubscribersResponse() *components.V4StatusPagesListSubscribersResponse {
	if s == nil {
		return nil
	}
	return s.V4StatusPagesListSubscribersResponse
}
