// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// StatusPagesCreateStatusPageResponseBody - The request has succeeded.
type StatusPagesCreateStatusPageResponseBody struct {
	Data components.V4StatusPagesCreateStatusPageResponse `json:"data"`
}

func (s *StatusPagesCreateStatusPageResponseBody) GetData() components.V4StatusPagesCreateStatusPageResponse {
	if s == nil {
		return components.V4StatusPagesCreateStatusPageResponse{}
	}
	return s.Data
}

type StatusPagesCreateStatusPageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *StatusPagesCreateStatusPageResponseBody
}

func (s *StatusPagesCreateStatusPageResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StatusPagesCreateStatusPageResponse) GetObject() *StatusPagesCreateStatusPageResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
