// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type SuppressionRulesGetSuppressionRulesRequest struct {
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceID"`
}

func (s *SuppressionRulesGetSuppressionRulesRequest) GetServiceID() string {
	if s == nil {
		return ""
	}
	return s.ServiceID
}

type SuppressionRulesGetSuppressionRulesData struct {
	Rules []components.V3ServicesSuppressionRulesSuppressionRuleResponse `json:"rules"`
}

func (s *SuppressionRulesGetSuppressionRulesData) GetRules() []components.V3ServicesSuppressionRulesSuppressionRuleResponse {
	if s == nil {
		return []components.V3ServicesSuppressionRulesSuppressionRuleResponse{}
	}
	return s.Rules
}

// SuppressionRulesGetSuppressionRulesResponseBody - The request has succeeded.
type SuppressionRulesGetSuppressionRulesResponseBody struct {
	Data SuppressionRulesGetSuppressionRulesData `json:"data"`
}

func (s *SuppressionRulesGetSuppressionRulesResponseBody) GetData() SuppressionRulesGetSuppressionRulesData {
	if s == nil {
		return SuppressionRulesGetSuppressionRulesData{}
	}
	return s.Data
}

type SuppressionRulesGetSuppressionRulesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *SuppressionRulesGetSuppressionRulesResponseBody
}

func (s *SuppressionRulesGetSuppressionRulesResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SuppressionRulesGetSuppressionRulesResponse) GetObject() *SuppressionRulesGetSuppressionRulesResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
