// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// TeamsCreateTeamResponseBody - The request has succeeded and a new resource has been created as a result.
type TeamsCreateTeamResponseBody struct {
	Data components.V3TeamsTeamResponse `json:"data"`
}

func (t *TeamsCreateTeamResponseBody) GetData() components.V3TeamsTeamResponse {
	if t == nil {
		return components.V3TeamsTeamResponse{}
	}
	return t.Data
}

type TeamsCreateTeamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *TeamsCreateTeamResponseBody
}

func (t *TeamsCreateTeamResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TeamsCreateTeamResponse) GetObject() *TeamsCreateTeamResponseBody {
	if t == nil {
		return nil
	}
	return t.Object
}
