// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type TeamsUpdateTeamRequest struct {
	TeamID                   string                              `pathParam:"style=simple,explode=false,name=teamId"`
	V3TeamsUpdateTeamRequest components.V3TeamsUpdateTeamRequest `request:"mediaType=application/json"`
}

func (t *TeamsUpdateTeamRequest) GetTeamID() string {
	if t == nil {
		return ""
	}
	return t.TeamID
}

func (t *TeamsUpdateTeamRequest) GetV3TeamsUpdateTeamRequest() components.V3TeamsUpdateTeamRequest {
	if t == nil {
		return components.V3TeamsUpdateTeamRequest{}
	}
	return t.V3TeamsUpdateTeamRequest
}

// TeamsUpdateTeamResponseBody - The request has succeeded.
type TeamsUpdateTeamResponseBody struct {
	Data components.V3TeamsTeamResponse `json:"data"`
}

func (t *TeamsUpdateTeamResponseBody) GetData() components.V3TeamsTeamResponse {
	if t == nil {
		return components.V3TeamsTeamResponse{}
	}
	return t.Data
}

type TeamsUpdateTeamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *TeamsUpdateTeamResponseBody
}

func (t *TeamsUpdateTeamResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TeamsUpdateTeamResponse) GetObject() *TeamsUpdateTeamResponseBody {
	if t == nil {
		return nil
	}
	return t.Object
}
