// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type TeamsGetAllTeamMembersRequest struct {
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
}

func (t *TeamsGetAllTeamMembersRequest) GetTeamID() string {
	if t == nil {
		return ""
	}
	return t.TeamID
}

// TeamsGetAllTeamMembersResponseBody - The request has succeeded.
type TeamsGetAllTeamMembersResponseBody struct {
	Data []components.V3TeamsTeamMemberResponse `json:"data"`
}

func (t *TeamsGetAllTeamMembersResponseBody) GetData() []components.V3TeamsTeamMemberResponse {
	if t == nil {
		return []components.V3TeamsTeamMemberResponse{}
	}
	return t.Data
}

type TeamsGetAllTeamMembersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *TeamsGetAllTeamMembersResponseBody
}

func (t *TeamsGetAllTeamMembersResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TeamsGetAllTeamMembersResponse) GetObject() *TeamsGetAllTeamMembersResponseBody {
	if t == nil {
		return nil
	}
	return t.Object
}
