// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type TeamsGetAllTeamRolesRequest struct {
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
}

func (t *TeamsGetAllTeamRolesRequest) GetTeamID() string {
	if t == nil {
		return ""
	}
	return t.TeamID
}

// TeamsGetAllTeamRolesResponseBody - The request has succeeded.
type TeamsGetAllTeamRolesResponseBody struct {
	Data []components.V3TeamsTeamRoleResponse `json:"data"`
}

func (t *TeamsGetAllTeamRolesResponseBody) GetData() []components.V3TeamsTeamRoleResponse {
	if t == nil {
		return []components.V3TeamsTeamRoleResponse{}
	}
	return t.Data
}

type TeamsGetAllTeamRolesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *TeamsGetAllTeamRolesResponseBody
}

func (t *TeamsGetAllTeamRolesResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TeamsGetAllTeamRolesResponse) GetObject() *TeamsGetAllTeamRolesResponseBody {
	if t == nil {
		return nil
	}
	return t.Object
}
