// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type TeamsUpdateTeamMemberRequest struct {
	TeamID                         string                                    `pathParam:"style=simple,explode=false,name=teamId"`
	MemberID                       string                                    `pathParam:"style=simple,explode=false,name=memberId"`
	V3TeamsUpdateTeamMemberRequest components.V3TeamsUpdateTeamMemberRequest `request:"mediaType=application/json"`
}

func (t *TeamsUpdateTeamMemberRequest) GetTeamID() string {
	if t == nil {
		return ""
	}
	return t.TeamID
}

func (t *TeamsUpdateTeamMemberRequest) GetMemberID() string {
	if t == nil {
		return ""
	}
	return t.MemberID
}

func (t *TeamsUpdateTeamMemberRequest) GetV3TeamsUpdateTeamMemberRequest() components.V3TeamsUpdateTeamMemberRequest {
	if t == nil {
		return components.V3TeamsUpdateTeamMemberRequest{}
	}
	return t.V3TeamsUpdateTeamMemberRequest
}

// TeamsUpdateTeamMemberResponseBody - The request has succeeded.
type TeamsUpdateTeamMemberResponseBody struct {
	Data components.V3TeamsTeamMemberResponse `json:"data"`
}

func (t *TeamsUpdateTeamMemberResponseBody) GetData() components.V3TeamsTeamMemberResponse {
	if t == nil {
		return components.V3TeamsTeamMemberResponse{}
	}
	return t.Data
}

type TeamsUpdateTeamMemberResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *TeamsUpdateTeamMemberResponseBody
}

func (t *TeamsUpdateTeamMemberResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TeamsUpdateTeamMemberResponse) GetObject() *TeamsUpdateTeamMemberResponseBody {
	if t == nil {
		return nil
	}
	return t.Object
}
