// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type TeamsRemoveTeamRoleRequest struct {
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
	RoleID string `pathParam:"style=simple,explode=false,name=roleId"`
}

func (t *TeamsRemoveTeamRoleRequest) GetTeamID() string {
	if t == nil {
		return ""
	}
	return t.TeamID
}

func (t *TeamsRemoveTeamRoleRequest) GetRoleID() string {
	if t == nil {
		return ""
	}
	return t.RoleID
}

// TeamsRemoveTeamRoleResponseBody - There is no content to send for this request, but the headers may be useful.
type TeamsRemoveTeamRoleResponseBody struct {
}

type TeamsRemoveTeamRoleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (t *TeamsRemoveTeamRoleResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TeamsRemoveTeamRoleResponse) GetBody() []byte {
	if t == nil {
		return nil
	}
	return t.Body
}
