// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type UsersDeleteUserRequest struct {
	UserID            string `json:"user_id"`
	SwapUserID        string `json:"swap_user_id"`
	SuppressIncidents bool   `json:"suppress_incidents"`
	ReassignIncidents bool   `json:"reassign_incidents"`
}

func (u *UsersDeleteUserRequest) GetUserID() string {
	if u == nil {
		return ""
	}
	return u.UserID
}

func (u *UsersDeleteUserRequest) GetSwapUserID() string {
	if u == nil {
		return ""
	}
	return u.SwapUserID
}

func (u *UsersDeleteUserRequest) GetSuppressIncidents() bool {
	if u == nil {
		return false
	}
	return u.SuppressIncidents
}

func (u *UsersDeleteUserRequest) GetReassignIncidents() bool {
	if u == nil {
		return false
	}
	return u.ReassignIncidents
}

type UsersDeleteUserData struct {
}

// UsersDeleteUserResponseBody - The request has succeeded.
type UsersDeleteUserResponseBody struct {
	Data UsersDeleteUserData `json:"data"`
}

func (u *UsersDeleteUserResponseBody) GetData() UsersDeleteUserData {
	if u == nil {
		return UsersDeleteUserData{}
	}
	return u.Data
}

type UsersDeleteUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *UsersDeleteUserResponseBody
}

func (u *UsersDeleteUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UsersDeleteUserResponse) GetObject() *UsersDeleteUserResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
