// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// UsersAddUserResponseBody - The request has succeeded and a new resource has been created as a result.
type UsersAddUserResponseBody struct {
	Data components.V3UsersUserResponse `json:"data"`
}

func (u *UsersAddUserResponseBody) GetData() components.V3UsersUserResponse {
	if u == nil {
		return components.V3UsersUserResponse{}
	}
	return u.Data
}

type UsersAddUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded and a new resource has been created as a result.
	Object *UsersAddUserResponseBody
}

func (u *UsersAddUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UsersAddUserResponse) GetObject() *UsersAddUserResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
