// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type UsersRemoveTokenRequest struct {
	// (Required) refresh token id
	RefreshTokenID string `pathParam:"style=simple,explode=false,name=refreshTokenID"`
}

func (u *UsersRemoveTokenRequest) GetRefreshTokenID() string {
	if u == nil {
		return ""
	}
	return u.RefreshTokenID
}

// UsersRemoveTokenResponseBody - There is no content to send for this request, but the headers may be useful.
type UsersRemoveTokenResponseBody struct {
}

type UsersRemoveTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (u *UsersRemoveTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UsersRemoveTokenResponse) GetBody() []byte {
	if u == nil {
		return nil
	}
	return u.Body
}
