// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// UsersGetAllTokensResponseBody - The request has succeeded.
type UsersGetAllTokensResponseBody struct {
	Data []components.V3UsersAPITokenResponse `json:"data"`
}

func (u *UsersGetAllTokensResponseBody) GetData() []components.V3UsersAPITokenResponse {
	if u == nil {
		return []components.V3UsersAPITokenResponse{}
	}
	return u.Data
}

type UsersGetAllTokensResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *UsersGetAllTokensResponseBody
}

func (u *UsersGetAllTokensResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UsersGetAllTokensResponse) GetObject() *UsersGetAllTokensResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
