// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

// UsersGetAllUsersResponseBody - The request has succeeded.
type UsersGetAllUsersResponseBody struct {
	Data []components.V3UsersUserResponse `json:"data"`
}

func (u *UsersGetAllUsersResponseBody) GetData() []components.V3UsersUserResponse {
	if u == nil {
		return []components.V3UsersUserResponse{}
	}
	return u.Data
}

type UsersGetAllUsersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *UsersGetAllUsersResponseBody
}

func (u *UsersGetAllUsersResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UsersGetAllUsersResponse) GetObject() *UsersGetAllUsersResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
