// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type WebformsRemoveWebformRequest struct {
	WebformID int64  `pathParam:"style=simple,explode=false,name=webformId"`
	OwnerID   string `queryParam:"style=form,explode=false,name=owner_id"`
}

func (w *WebformsRemoveWebformRequest) GetWebformID() int64 {
	if w == nil {
		return 0
	}
	return w.WebformID
}

func (w *WebformsRemoveWebformRequest) GetOwnerID() string {
	if w == nil {
		return ""
	}
	return w.OwnerID
}

// WebformsRemoveWebformResponseBody - The request has succeeded.
type WebformsRemoveWebformResponseBody struct {
	Data string `json:"data"`
}

func (w *WebformsRemoveWebformResponseBody) GetData() string {
	if w == nil {
		return ""
	}
	return w.Data
}

type WebformsRemoveWebformResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *WebformsRemoveWebformResponseBody
}

func (w *WebformsRemoveWebformResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WebformsRemoveWebformResponse) GetObject() *WebformsRemoveWebformResponseBody {
	if w == nil {
		return nil
	}
	return w.Object
}
