// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type WebformsGetAllWebformsRequest struct {
	OwnerID    string `queryParam:"style=form,explode=false,name=owner_id"`
	PageNumber *int64 `queryParam:"style=form,explode=true,name=page_number"`
	PageSize   *int64 `queryParam:"style=form,explode=true,name=page_size"`
}

func (w *WebformsGetAllWebformsRequest) GetOwnerID() string {
	if w == nil {
		return ""
	}
	return w.OwnerID
}

func (w *WebformsGetAllWebformsRequest) GetPageNumber() *int64 {
	if w == nil {
		return nil
	}
	return w.PageNumber
}

func (w *WebformsGetAllWebformsRequest) GetPageSize() *int64 {
	if w == nil {
		return nil
	}
	return w.PageSize
}

type WebformsGetAllWebformsMeta struct {
	TotalCount int `json:"total_count"`
}

func (w *WebformsGetAllWebformsMeta) GetTotalCount() int {
	if w == nil {
		return 0
	}
	return w.TotalCount
}

// WebformsGetAllWebformsResponseBody - The request has succeeded.
type WebformsGetAllWebformsResponseBody struct {
	Data []components.V3WebformsWebformResponse `json:"data"`
	Meta WebformsGetAllWebformsMeta             `json:"meta"`
}

func (w *WebformsGetAllWebformsResponseBody) GetData() []components.V3WebformsWebformResponse {
	if w == nil {
		return []components.V3WebformsWebformResponse{}
	}
	return w.Data
}

func (w *WebformsGetAllWebformsResponseBody) GetMeta() WebformsGetAllWebformsMeta {
	if w == nil {
		return WebformsGetAllWebformsMeta{}
	}
	return w.Meta
}

type WebformsGetAllWebformsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *WebformsGetAllWebformsResponseBody

	Next func() (*WebformsGetAllWebformsResponse, error)
}

func (w *WebformsGetAllWebformsResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WebformsGetAllWebformsResponse) GetObject() *WebformsGetAllWebformsResponseBody {
	if w == nil {
		return nil
	}
	return w.Object
}
