// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type WebhooksGetAllWebhooksRequest struct {
	PageLimit *string `queryParam:"style=form,explode=true,name=page-limit"`
	Offset    *string `queryParam:"style=form,explode=true,name=offset"`
}

func (w *WebhooksGetAllWebhooksRequest) GetPageLimit() *string {
	if w == nil {
		return nil
	}
	return w.PageLimit
}

func (w *WebhooksGetAllWebhooksRequest) GetOffset() *string {
	if w == nil {
		return nil
	}
	return w.Offset
}

type WebhooksGetAllWebhooksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	V3ExtensionsWebhooksGetAllWebhooksResponse *components.V3ExtensionsWebhooksGetAllWebhooksResponse
}

func (w *WebhooksGetAllWebhooksResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WebhooksGetAllWebhooksResponse) GetV3ExtensionsWebhooksGetAllWebhooksResponse() *components.V3ExtensionsWebhooksGetAllWebhooksResponse {
	if w == nil {
		return nil
	}
	return w.V3ExtensionsWebhooksGetAllWebhooksResponse
}
