// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type WebhooksGetWebhookByIDRequest struct {
	// (Required) event webhook ID
	EventWebhookID string `pathParam:"style=simple,explode=false,name=eventWebhookID"`
}

func (w *WebhooksGetWebhookByIDRequest) GetEventWebhookID() string {
	if w == nil {
		return ""
	}
	return w.EventWebhookID
}

// WebhooksGetWebhookByIDResponseBody - The request has succeeded.
type WebhooksGetWebhookByIDResponseBody struct {
	Data components.V3ExtensionsWebhooksWebhookResponse `json:"data"`
}

func (w *WebhooksGetWebhookByIDResponseBody) GetData() components.V3ExtensionsWebhooksWebhookResponse {
	if w == nil {
		return components.V3ExtensionsWebhooksWebhookResponse{}
	}
	return w.Data
}

type WebhooksGetWebhookByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *WebhooksGetWebhookByIDResponseBody
}

func (w *WebhooksGetWebhookByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WebhooksGetWebhookByIDResponse) GetObject() *WebhooksGetWebhookByIDResponseBody {
	if w == nil {
		return nil
	}
	return w.Object
}
