// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type WorkflowsDeleteWorkflowRequest struct {
	WorkflowID string `pathParam:"style=simple,explode=false,name=workflowID"`
}

func (w *WorkflowsDeleteWorkflowRequest) GetWorkflowID() string {
	if w == nil {
		return ""
	}
	return w.WorkflowID
}

// WorkflowsDeleteWorkflowResponseBody - There is no content to send for this request, but the headers may be useful.
type WorkflowsDeleteWorkflowResponseBody struct {
}

type WorkflowsDeleteWorkflowResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Body     []byte
}

func (w *WorkflowsDeleteWorkflowResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WorkflowsDeleteWorkflowResponse) GetBody() []byte {
	if w == nil {
		return nil
	}
	return w.Body
}
