// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type WorkflowsGetWorkflowActionByIDRequest struct {
	WorkflowID string `pathParam:"style=simple,explode=false,name=workflowID"`
	ActionID   string `pathParam:"style=simple,explode=false,name=actionID"`
}

func (w *WorkflowsGetWorkflowActionByIDRequest) GetWorkflowID() string {
	if w == nil {
		return ""
	}
	return w.WorkflowID
}

func (w *WorkflowsGetWorkflowActionByIDRequest) GetActionID() string {
	if w == nil {
		return ""
	}
	return w.ActionID
}

// WorkflowsGetWorkflowActionByIDResponseBody - The request has succeeded.
type WorkflowsGetWorkflowActionByIDResponseBody struct {
	Data components.V3WorkflowsGetWorkflowActionByIDResponse `json:"data"`
}

func (w *WorkflowsGetWorkflowActionByIDResponseBody) GetData() components.V3WorkflowsGetWorkflowActionByIDResponse {
	if w == nil {
		return components.V3WorkflowsGetWorkflowActionByIDResponse{}
	}
	return w.Data
}

type WorkflowsGetWorkflowActionByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	Object *WorkflowsGetWorkflowActionByIDResponseBody
}

func (w *WorkflowsGetWorkflowActionByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WorkflowsGetWorkflowActionByIDResponse) GetObject() *WorkflowsGetWorkflowActionByIDResponseBody {
	if w == nil {
		return nil
	}
	return w.Object
}
