// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type WorkflowsGetWorkflowLogsRequest struct {
	WorkflowID string `pathParam:"style=simple,explode=false,name=workflowID"`
	PageSize   *int64 `queryParam:"style=form,explode=false,name=page_size"`
	PageNumber *int64 `queryParam:"style=form,explode=false,name=page_number"`
}

func (w *WorkflowsGetWorkflowLogsRequest) GetWorkflowID() string {
	if w == nil {
		return ""
	}
	return w.WorkflowID
}

func (w *WorkflowsGetWorkflowLogsRequest) GetPageSize() *int64 {
	if w == nil {
		return nil
	}
	return w.PageSize
}

func (w *WorkflowsGetWorkflowLogsRequest) GetPageNumber() *int64 {
	if w == nil {
		return nil
	}
	return w.PageNumber
}

type WorkflowsGetWorkflowLogsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	V3WorkflowsGetWorkflowLogsResponse *components.V3WorkflowsGetWorkflowLogsResponse

	Next func() (*WorkflowsGetWorkflowLogsResponse, error)
}

func (w *WorkflowsGetWorkflowLogsResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WorkflowsGetWorkflowLogsResponse) GetV3WorkflowsGetWorkflowLogsResponse() *components.V3WorkflowsGetWorkflowLogsResponse {
	if w == nil {
		return nil
	}
	return w.V3WorkflowsGetWorkflowLogsResponse
}
