// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type WorkflowsListWorkflowsRequest struct {
	OwnerID    string   `queryParam:"style=form,explode=false,name=owner_id"`
	PageSize   *int64   `queryParam:"style=form,explode=false,name=page_size"`
	PageNumber *int64   `queryParam:"style=form,explode=false,name=page_number"`
	Search     *string  `queryParam:"style=form,explode=false,name=search"`
	Event      []string `queryParam:"style=form,explode=false,name=event"`
	Actions    []string `queryParam:"style=form,explode=false,name=actions"`
	Tags       []string `queryParam:"style=form,explode=false,name=tags"`
	Owner      []string `queryParam:"style=form,explode=false,name=owner"`
	CreatedBy  []string `queryParam:"style=form,explode=false,name=created_by"`
	UpdatedBy  []string `queryParam:"style=form,explode=false,name=updated_by"`
	Enabled    *string  `queryParam:"style=form,explode=false,name=enabled"`
}

func (w *WorkflowsListWorkflowsRequest) GetOwnerID() string {
	if w == nil {
		return ""
	}
	return w.OwnerID
}

func (w *WorkflowsListWorkflowsRequest) GetPageSize() *int64 {
	if w == nil {
		return nil
	}
	return w.PageSize
}

func (w *WorkflowsListWorkflowsRequest) GetPageNumber() *int64 {
	if w == nil {
		return nil
	}
	return w.PageNumber
}

func (w *WorkflowsListWorkflowsRequest) GetSearch() *string {
	if w == nil {
		return nil
	}
	return w.Search
}

func (w *WorkflowsListWorkflowsRequest) GetEvent() []string {
	if w == nil {
		return nil
	}
	return w.Event
}

func (w *WorkflowsListWorkflowsRequest) GetActions() []string {
	if w == nil {
		return nil
	}
	return w.Actions
}

func (w *WorkflowsListWorkflowsRequest) GetTags() []string {
	if w == nil {
		return nil
	}
	return w.Tags
}

func (w *WorkflowsListWorkflowsRequest) GetOwner() []string {
	if w == nil {
		return nil
	}
	return w.Owner
}

func (w *WorkflowsListWorkflowsRequest) GetCreatedBy() []string {
	if w == nil {
		return nil
	}
	return w.CreatedBy
}

func (w *WorkflowsListWorkflowsRequest) GetUpdatedBy() []string {
	if w == nil {
		return nil
	}
	return w.UpdatedBy
}

func (w *WorkflowsListWorkflowsRequest) GetEnabled() *string {
	if w == nil {
		return nil
	}
	return w.Enabled
}

type WorkflowsListWorkflowsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	V3WorkflowsListWorkflowAPIResponse *components.V3WorkflowsListWorkflowAPIResponse

	Next func() (*WorkflowsListWorkflowsResponse, error)
}

func (w *WorkflowsListWorkflowsResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WorkflowsListWorkflowsResponse) GetV3WorkflowsListWorkflowAPIResponse() *components.V3WorkflowsListWorkflowAPIResponse {
	if w == nil {
		return nil
	}
	return w.V3WorkflowsListWorkflowAPIResponse
}
