// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/SquadcastHub/squadcast-sdk-go/models/components"
)

type WorkflowsGetWorkflowByIDRequest struct {
	WorkflowID string `pathParam:"style=simple,explode=false,name=workflowID"`
}

func (w *WorkflowsGetWorkflowByIDRequest) GetWorkflowID() string {
	if w == nil {
		return ""
	}
	return w.WorkflowID
}

type WorkflowsGetWorkflowByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The request has succeeded.
	V3WorkflowsGetWorkflowByIDResponse *components.V3WorkflowsGetWorkflowByIDResponse
}

func (w *WorkflowsGetWorkflowByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if w == nil {
		return components.HTTPMetadata{}
	}
	return w.HTTPMeta
}

func (w *WorkflowsGetWorkflowByIDResponse) GetV3WorkflowsGetWorkflowByIDResponse() *components.V3WorkflowsGetWorkflowByIDResponse {
	if w == nil {
		return nil
	}
	return w.V3WorkflowsGetWorkflowByIDResponse
}
