// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CommonV4PageInfo struct {
	PageSize       int     `json:"pageSize"`
	HasNext        bool    `json:"hasNext"`
	HasPrevious    bool    `json:"hasPrevious"`
	NextCursor     *string `json:"nextCursor,omitempty"`
	PreviousCursor *string `json:"previousCursor,omitempty"`
}

func (c *CommonV4PageInfo) GetPageSize() int {
	if c == nil {
		return 0
	}
	return c.PageSize
}

func (c *CommonV4PageInfo) GetHasNext() bool {
	if c == nil {
		return false
	}
	return c.HasNext
}

func (c *CommonV4PageInfo) GetHasPrevious() bool {
	if c == nil {
		return false
	}
	return c.HasPrevious
}

func (c *CommonV4PageInfo) GetNextCursor() *string {
	if c == nil {
		return nil
	}
	return c.NextCursor
}

func (c *CommonV4PageInfo) GetPreviousCursor() *string {
	if c == nil {
		return nil
	}
	return c.PreviousCursor
}
