// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Abilities - A map of abilities granted to the user.
type Abilities struct {
}

// CommonV3RBACEntityPermission - Represents a permission granted to a user for a specific entity.
type CommonV3RBACEntityPermission struct {
	// The ID of the user receiving the permission.
	UserID string `json:"user_id"`
	// A map of abilities granted to the user.
	Abilities Abilities `json:"abilities"`
}

func (c *CommonV3RBACEntityPermission) GetUserID() string {
	if c == nil {
		return ""
	}
	return c.UserID
}

func (c *CommonV3RBACEntityPermission) GetAbilities() Abilities {
	if c == nil {
		return Abilities{}
	}
	return c.Abilities
}
