// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3AnalyticsAnalyticsResponse struct {
	Mtta float64 `json:"mtta"`
	Mttr float64 `json:"mttr"`
}

func (v *V3AnalyticsAnalyticsResponse) GetMtta() float64 {
	if v == nil {
		return 0.0
	}
	return v.Mtta
}

func (v *V3AnalyticsAnalyticsResponse) GetMttr() float64 {
	if v == nil {
		return 0.0
	}
	return v.Mttr
}
