// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3AuditLogsExportAuditLogsResponseData struct {
	ID      string `json:"id"`
	Message string `json:"message"`
}

func (v *V3AuditLogsExportAuditLogsResponseData) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3AuditLogsExportAuditLogsResponseData) GetMessage() string {
	if v == nil {
		return ""
	}
	return v.Message
}

// V3AuditLogsExportAuditLogsResponse - Response model for exporting audit logs
type V3AuditLogsExportAuditLogsResponse struct {
	Data V3AuditLogsExportAuditLogsResponseData `json:"data"`
}

func (v *V3AuditLogsExportAuditLogsResponse) GetData() V3AuditLogsExportAuditLogsResponseData {
	if v == nil {
		return V3AuditLogsExportAuditLogsResponseData{}
	}
	return v.Data
}
