// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3AuditLogsAuditLogResponse - Represents an audit log entry response
type V3AuditLogsAuditLogResponse struct {
	ID       int    `json:"id"`
	Resource string `json:"resource"`
	Action   string `json:"action"`
	// Represents an actor (user) in audit logs
	Actor     V3AuditLogsActor `json:"actor"`
	Client    string           `json:"client"`
	Timestamp string           `json:"timestamp"`
	// Represents a team in audit logs
	Team V3AuditLogsTeam `json:"team"`
}

func (v *V3AuditLogsAuditLogResponse) GetID() int {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V3AuditLogsAuditLogResponse) GetResource() string {
	if v == nil {
		return ""
	}
	return v.Resource
}

func (v *V3AuditLogsAuditLogResponse) GetAction() string {
	if v == nil {
		return ""
	}
	return v.Action
}

func (v *V3AuditLogsAuditLogResponse) GetActor() V3AuditLogsActor {
	if v == nil {
		return V3AuditLogsActor{}
	}
	return v.Actor
}

func (v *V3AuditLogsAuditLogResponse) GetClient() string {
	if v == nil {
		return ""
	}
	return v.Client
}

func (v *V3AuditLogsAuditLogResponse) GetTimestamp() string {
	if v == nil {
		return ""
	}
	return v.Timestamp
}

func (v *V3AuditLogsAuditLogResponse) GetTeam() V3AuditLogsTeam {
	if v == nil {
		return V3AuditLogsTeam{}
	}
	return v.Team
}
