// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3AuditLogsAuditLogsExportHistoryResponse - Response model for audit logs export history
type V3AuditLogsAuditLogsExportHistoryResponse struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	ExportedAt  string `json:"exportedAt"`
	// Represents an actor (user) in audit logs
	RequestedBy  V3AuditLogsActor `json:"requestedBy"`
	DownloadLink string           `json:"downloadLink"`
	Status       string           `json:"status"`
	// Represents filters used in audit log queries
	Filters V3AuditLogsFilters `json:"filters"`
}

func (v *V3AuditLogsAuditLogsExportHistoryResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3AuditLogsAuditLogsExportHistoryResponse) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3AuditLogsAuditLogsExportHistoryResponse) GetDescription() string {
	if v == nil {
		return ""
	}
	return v.Description
}

func (v *V3AuditLogsAuditLogsExportHistoryResponse) GetExportedAt() string {
	if v == nil {
		return ""
	}
	return v.ExportedAt
}

func (v *V3AuditLogsAuditLogsExportHistoryResponse) GetRequestedBy() V3AuditLogsActor {
	if v == nil {
		return V3AuditLogsActor{}
	}
	return v.RequestedBy
}

func (v *V3AuditLogsAuditLogsExportHistoryResponse) GetDownloadLink() string {
	if v == nil {
		return ""
	}
	return v.DownloadLink
}

func (v *V3AuditLogsAuditLogsExportHistoryResponse) GetStatus() string {
	if v == nil {
		return ""
	}
	return v.Status
}

func (v *V3AuditLogsAuditLogsExportHistoryResponse) GetFilters() V3AuditLogsFilters {
	if v == nil {
		return V3AuditLogsFilters{}
	}
	return v.Filters
}
