// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ExtensionsWebhooksWebhookListItem struct {
	ID                        string `json:"id"`
	Name                      string `json:"name"`
	Description               string `json:"description"`
	TriggerType               string `json:"trigger_type"`
	PayloadType               string `json:"payload_type"`
	CustomPayloadTemplateName string `json:"custom_payload_template_name"`
}

func (v *V3ExtensionsWebhooksWebhookListItem) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3ExtensionsWebhooksWebhookListItem) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3ExtensionsWebhooksWebhookListItem) GetDescription() string {
	if v == nil {
		return ""
	}
	return v.Description
}

func (v *V3ExtensionsWebhooksWebhookListItem) GetTriggerType() string {
	if v == nil {
		return ""
	}
	return v.TriggerType
}

func (v *V3ExtensionsWebhooksWebhookListItem) GetPayloadType() string {
	if v == nil {
		return ""
	}
	return v.PayloadType
}

func (v *V3ExtensionsWebhooksWebhookListItem) GetCustomPayloadTemplateName() string {
	if v == nil {
		return ""
	}
	return v.CustomPayloadTemplateName
}
