// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3ExtensionsMSTeamsTriggers - Defines the trigger conditions for sending alerts.
type V3ExtensionsMSTeamsTriggers struct {
	// If true, all alerts are sent, and the 'custom' list is ignored.
	AllActive bool `json:"all_active"`
	// A list of specific event classes to send alerts for. This is used when 'all_active' is false.
	Custom []V3ExtensionsMSTeamsEventClass `json:"custom"`
}

func (v *V3ExtensionsMSTeamsTriggers) GetAllActive() bool {
	if v == nil {
		return false
	}
	return v.AllActive
}

func (v *V3ExtensionsMSTeamsTriggers) GetCustom() []V3ExtensionsMSTeamsEventClass {
	if v == nil {
		return []V3ExtensionsMSTeamsEventClass{}
	}
	return v.Custom
}
