// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3ExtensionsMSTeamsIncidentActionAlertState - A set of booleans to easily configure which incident-related alerts are sent to MS Teams.
type V3ExtensionsMSTeamsIncidentActionAlertState struct {
	IsTriggerActive         bool `json:"is_trigger_active"`
	IsRetriggerActive       bool `json:"is_retrigger_active"`
	IsAcknowledgeActive     bool `json:"is_acknowledge_active"`
	IsResolveActive         bool `json:"is_resolve_active"`
	IsReassignActive        bool `json:"is_reassign_active"`
	IsNotesAddedActive      bool `json:"is_notes_added_active"`
	IsPostmortemActive      bool `json:"is_postmortem_active"`
	IsPriorityUpdatedActive bool `json:"is_priority_updated_active"`
}

func (v *V3ExtensionsMSTeamsIncidentActionAlertState) GetIsTriggerActive() bool {
	if v == nil {
		return false
	}
	return v.IsTriggerActive
}

func (v *V3ExtensionsMSTeamsIncidentActionAlertState) GetIsRetriggerActive() bool {
	if v == nil {
		return false
	}
	return v.IsRetriggerActive
}

func (v *V3ExtensionsMSTeamsIncidentActionAlertState) GetIsAcknowledgeActive() bool {
	if v == nil {
		return false
	}
	return v.IsAcknowledgeActive
}

func (v *V3ExtensionsMSTeamsIncidentActionAlertState) GetIsResolveActive() bool {
	if v == nil {
		return false
	}
	return v.IsResolveActive
}

func (v *V3ExtensionsMSTeamsIncidentActionAlertState) GetIsReassignActive() bool {
	if v == nil {
		return false
	}
	return v.IsReassignActive
}

func (v *V3ExtensionsMSTeamsIncidentActionAlertState) GetIsNotesAddedActive() bool {
	if v == nil {
		return false
	}
	return v.IsNotesAddedActive
}

func (v *V3ExtensionsMSTeamsIncidentActionAlertState) GetIsPostmortemActive() bool {
	if v == nil {
		return false
	}
	return v.IsPostmortemActive
}

func (v *V3ExtensionsMSTeamsIncidentActionAlertState) GetIsPriorityUpdatedActive() bool {
	if v == nil {
		return false
	}
	return v.IsPriorityUpdatedActive
}
