// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ExportExportResponse struct {
	ID                   string  `json:"id"`
	Type                 string  `json:"type"`
	Status               string  `json:"status"`
	DownloadURL          *string `json:"download_url,omitempty"`
	DownloadURLExpiresAt *string `json:"download_url_expires_at,omitempty"`
	Format               string  `json:"format"`
	ErrorMessage         *string `json:"error_message,omitempty"`
}

func (v *V3ExportExportResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3ExportExportResponse) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *V3ExportExportResponse) GetStatus() string {
	if v == nil {
		return ""
	}
	return v.Status
}

func (v *V3ExportExportResponse) GetDownloadURL() *string {
	if v == nil {
		return nil
	}
	return v.DownloadURL
}

func (v *V3ExportExportResponse) GetDownloadURLExpiresAt() *string {
	if v == nil {
		return nil
	}
	return v.DownloadURLExpiresAt
}

func (v *V3ExportExportResponse) GetFormat() string {
	if v == nil {
		return ""
	}
	return v.Format
}

func (v *V3ExportExportResponse) GetErrorMessage() *string {
	if v == nil {
		return nil
	}
	return v.ErrorMessage
}
