// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3ExtensionsMSTeamsConnectedTeams - Represents a connected MS Team and its channel configurations.
type V3ExtensionsMSTeamsConnectedTeams struct {
	// The MongoDB ObjectID for this connected team entry.
	ID *string `json:"id,omitempty"`
	// The unique identifier for the team in MS Teams.
	TeamID string `json:"team_id"`
	// The display name of the team in MS Teams.
	TeamName string `json:"team_name"`
	// A list of channel routing configurations for this team.
	ChannelConfigurations []V3ExtensionsMSTeamsChannelConfiguration `json:"channel_configurations"`
}

func (v *V3ExtensionsMSTeamsConnectedTeams) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V3ExtensionsMSTeamsConnectedTeams) GetTeamID() string {
	if v == nil {
		return ""
	}
	return v.TeamID
}

func (v *V3ExtensionsMSTeamsConnectedTeams) GetTeamName() string {
	if v == nil {
		return ""
	}
	return v.TeamName
}

func (v *V3ExtensionsMSTeamsConnectedTeams) GetChannelConfigurations() []V3ExtensionsMSTeamsChannelConfiguration {
	if v == nil {
		return []V3ExtensionsMSTeamsChannelConfiguration{}
	}
	return v.ChannelConfigurations
}
