// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ea3832cc8b28

package components

type V3ExtensionsWebhooksWebhookURL struct {
	URL    *string `json:"url,omitempty"`
	Method *string `json:"method,omitempty"`
}

func (v *V3ExtensionsWebhooksWebhookURL) GetURL() *string {
	if v == nil {
		return nil
	}
	return v.URL
}

func (v *V3ExtensionsWebhooksWebhookURL) GetMethod() *string {
	if v == nil {
		return nil
	}
	return v.Method
}
