// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3GlobalEventRulesRuleAction struct {
	// The service ID to which the alert should be routed.
	RouteTo string `json:"route_to"`
}

func (v *V3GlobalEventRulesRuleAction) GetRouteTo() string {
	if v == nil {
		return ""
	}
	return v.RouteTo
}
