// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3GlobalEventRulesCreateRulesetRequest struct {
	AlertSourceShortname string                        `json:"alert_source_shortname"`
	AlertSourceVersion   string                        `json:"alert_source_version"`
	CatchAllAction       *V3GlobalEventRulesRuleAction `json:"catch_all_action,omitempty"`
}

func (v *V3GlobalEventRulesCreateRulesetRequest) GetAlertSourceShortname() string {
	if v == nil {
		return ""
	}
	return v.AlertSourceShortname
}

func (v *V3GlobalEventRulesCreateRulesetRequest) GetAlertSourceVersion() string {
	if v == nil {
		return ""
	}
	return v.AlertSourceVersion
}

func (v *V3GlobalEventRulesCreateRulesetRequest) GetCatchAllAction() *V3GlobalEventRulesRuleAction {
	if v == nil {
		return nil
	}
	return v.CatchAllAction
}
