// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3GlobalEventRulesCreateOrUpdateRuleRequest struct {
	Description string                       `json:"description"`
	Expression  string                       `json:"expression"`
	Action      V3GlobalEventRulesRuleAction `json:"action"`
}

func (v *V3GlobalEventRulesCreateOrUpdateRuleRequest) GetDescription() string {
	if v == nil {
		return ""
	}
	return v.Description
}

func (v *V3GlobalEventRulesCreateOrUpdateRuleRequest) GetExpression() string {
	if v == nil {
		return ""
	}
	return v.Expression
}

func (v *V3GlobalEventRulesCreateOrUpdateRuleRequest) GetAction() V3GlobalEventRulesRuleAction {
	if v == nil {
		return V3GlobalEventRulesRuleAction{}
	}
	return v.Action
}
