// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest struct {
	IsEnabled bool                              `json:"is_enabled"`
	Rules     []V3GlobalOncallReminderRulesRule `json:"rules"`
}

func (v *V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest) GetIsEnabled() bool {
	if v == nil {
		return false
	}
	return v.IsEnabled
}

func (v *V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest) GetRules() []V3GlobalOncallReminderRulesRule {
	if v == nil {
		return []V3GlobalOncallReminderRulesRule{}
	}
	return v.Rules
}
