// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V3GlobalEventRulesRulesetResponse struct {
	ID                   *int64                        `json:"id,omitempty"`
	GlobalEventRuleID    *int64                        `json:"global_event_rule_id,omitempty"`
	AlertSourceShortname *string                       `json:"alert_source_shortname,omitempty"`
	AlertSourceVersion   *string                       `json:"alert_source_version,omitempty"`
	Ordering             []int64                       `json:"ordering,omitempty"`
	CatchAllAction       *V3GlobalEventRulesRuleAction `json:"catch_all_action,omitempty"`
	CreatedAt            *time.Time                    `json:"created_at,omitempty"`
	CreatedBy            *string                       `json:"created_by,omitempty"`
	UpdatedAt            *time.Time                    `json:"updated_at,omitempty"`
	UpdatedBy            *string                       `json:"updated_by,omitempty"`
}

func (v V3GlobalEventRulesRulesetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3GlobalEventRulesRulesetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V3GlobalEventRulesRulesetResponse) GetID() *int64 {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V3GlobalEventRulesRulesetResponse) GetGlobalEventRuleID() *int64 {
	if v == nil {
		return nil
	}
	return v.GlobalEventRuleID
}

func (v *V3GlobalEventRulesRulesetResponse) GetAlertSourceShortname() *string {
	if v == nil {
		return nil
	}
	return v.AlertSourceShortname
}

func (v *V3GlobalEventRulesRulesetResponse) GetAlertSourceVersion() *string {
	if v == nil {
		return nil
	}
	return v.AlertSourceVersion
}

func (v *V3GlobalEventRulesRulesetResponse) GetOrdering() []int64 {
	if v == nil {
		return nil
	}
	return v.Ordering
}

func (v *V3GlobalEventRulesRulesetResponse) GetCatchAllAction() *V3GlobalEventRulesRuleAction {
	if v == nil {
		return nil
	}
	return v.CatchAllAction
}

func (v *V3GlobalEventRulesRulesetResponse) GetCreatedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.CreatedAt
}

func (v *V3GlobalEventRulesRulesetResponse) GetCreatedBy() *string {
	if v == nil {
		return nil
	}
	return v.CreatedBy
}

func (v *V3GlobalEventRulesRulesetResponse) GetUpdatedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.UpdatedAt
}

func (v *V3GlobalEventRulesRulesetResponse) GetUpdatedBy() *string {
	if v == nil {
		return nil
	}
	return v.UpdatedBy
}
