// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3GlobalEventRulesUpdateGlobalEventRuleRequest struct {
	Name        *string                              `json:"name,omitempty"`
	Description *string                              `json:"description,omitempty"`
	EntityOwner *V3GlobalEventRulesEntityOwnerUpdate `json:"entity_owner,omitempty"`
}

func (v *V3GlobalEventRulesUpdateGlobalEventRuleRequest) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V3GlobalEventRulesUpdateGlobalEventRuleRequest) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V3GlobalEventRulesUpdateGlobalEventRuleRequest) GetEntityOwner() *V3GlobalEventRulesEntityOwnerUpdate {
	if v == nil {
		return nil
	}
	return v.EntityOwner
}
