// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3GlobalOncallReminderRulesCreateGlobalOncallReminderRulesRequest struct {
	IsEnabled bool                              `json:"is_enabled"`
	OwnerID   string                            `json:"owner_id"`
	Rules     []V3GlobalOncallReminderRulesRule `json:"rules"`
}

func (v *V3GlobalOncallReminderRulesCreateGlobalOncallReminderRulesRequest) GetIsEnabled() bool {
	if v == nil {
		return false
	}
	return v.IsEnabled
}

func (v *V3GlobalOncallReminderRulesCreateGlobalOncallReminderRulesRequest) GetOwnerID() string {
	if v == nil {
		return ""
	}
	return v.OwnerID
}

func (v *V3GlobalOncallReminderRulesCreateGlobalOncallReminderRulesRequest) GetRules() []V3GlobalOncallReminderRulesRule {
	if v == nil {
		return []V3GlobalOncallReminderRulesRule{}
	}
	return v.Rules
}
