// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dcdb75783062

package components

type V3GlobalEventRulesReorderRulesetRequest struct {
	Ordering []int64 `json:"ordering,omitempty"`
}

func (v *V3GlobalEventRulesReorderRulesetRequest) GetOrdering() []int64 {
	if v == nil {
		return nil
	}
	return v.Ordering
}
