// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

// V3IncidentsAdditionalResponderDetails - Details for an additional responder.
type V3IncidentsAdditionalResponderDetails struct {
	ID               string    `json:"id"`
	Type             string    `json:"type"`
	TimeOfAssignment time.Time `json:"timeOfAssignment"`
	Reason           string    `json:"reason"`
	Name             string    `json:"name"`
	LastNotifiedAt   time.Time `json:"last_notified_at"`
}

func (v V3IncidentsAdditionalResponderDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3IncidentsAdditionalResponderDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"id", "type", "timeOfAssignment", "reason", "name", "last_notified_at"}); err != nil {
		return err
	}
	return nil
}

func (v *V3IncidentsAdditionalResponderDetails) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3IncidentsAdditionalResponderDetails) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *V3IncidentsAdditionalResponderDetails) GetTimeOfAssignment() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.TimeOfAssignment
}

func (v *V3IncidentsAdditionalResponderDetails) GetReason() string {
	if v == nil {
		return ""
	}
	return v.Reason
}

func (v *V3IncidentsAdditionalResponderDetails) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3IncidentsAdditionalResponderDetails) GetLastNotifiedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.LastNotifiedAt
}
