// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V3IncidentsTagsLogsAdditionalInfo struct {
}

// V3IncidentsTagsLogs - Represents a log entry for an incident action.
type V3IncidentsTagsLogs struct {
	Action                 string                             `json:"action"`
	IsManuallyCreated      *bool                              `json:"is_manually_created,omitempty"`
	CreatedBy              *string                            `json:"created_by,omitempty"`
	UpdatedBy              *string                            `json:"updated_by,omitempty"`
	AssignedTo             *string                            `json:"assignedTo,omitempty"`
	AssignedBy             *string                            `json:"assignedBy,omitempty"`
	ID                     *string                            `json:"id,omitempty"`
	WorkflowID             *int64                             `json:"workflow_id,omitempty"`
	Time                   time.Time                          `json:"time"`
	Reason                 string                             `json:"reason"`
	AdditionalInfo         *V3IncidentsTagsLogsAdditionalInfo `json:"additionalInfo,omitempty"`
	Type                   *string                            `json:"type,omitempty"`
	ShouldShowInPostmortem *bool                              `json:"should_show_in_postmortem,omitempty"`
}

func (v V3IncidentsTagsLogs) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3IncidentsTagsLogs) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"action", "time", "reason"}); err != nil {
		return err
	}
	return nil
}

func (v *V3IncidentsTagsLogs) GetAction() string {
	if v == nil {
		return ""
	}
	return v.Action
}

func (v *V3IncidentsTagsLogs) GetIsManuallyCreated() *bool {
	if v == nil {
		return nil
	}
	return v.IsManuallyCreated
}

func (v *V3IncidentsTagsLogs) GetCreatedBy() *string {
	if v == nil {
		return nil
	}
	return v.CreatedBy
}

func (v *V3IncidentsTagsLogs) GetUpdatedBy() *string {
	if v == nil {
		return nil
	}
	return v.UpdatedBy
}

func (v *V3IncidentsTagsLogs) GetAssignedTo() *string {
	if v == nil {
		return nil
	}
	return v.AssignedTo
}

func (v *V3IncidentsTagsLogs) GetAssignedBy() *string {
	if v == nil {
		return nil
	}
	return v.AssignedBy
}

func (v *V3IncidentsTagsLogs) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V3IncidentsTagsLogs) GetWorkflowID() *int64 {
	if v == nil {
		return nil
	}
	return v.WorkflowID
}

func (v *V3IncidentsTagsLogs) GetTime() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.Time
}

func (v *V3IncidentsTagsLogs) GetReason() string {
	if v == nil {
		return ""
	}
	return v.Reason
}

func (v *V3IncidentsTagsLogs) GetAdditionalInfo() *V3IncidentsTagsLogsAdditionalInfo {
	if v == nil {
		return nil
	}
	return v.AdditionalInfo
}

func (v *V3IncidentsTagsLogs) GetType() *string {
	if v == nil {
		return nil
	}
	return v.Type
}

func (v *V3IncidentsTagsLogs) GetShouldShowInPostmortem() *bool {
	if v == nil {
		return nil
	}
	return v.ShouldShowInPostmortem
}
