// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2bec0c858882

package components

// V3IncidentsPostmortemsPostmortemFollowUp - Represents a single follow-up task in a postmortem.
type V3IncidentsPostmortemsPostmortemFollowUp struct {
	Task   string `json:"task"`
	IsDone bool   `json:"is_done"`
}

func (v *V3IncidentsPostmortemsPostmortemFollowUp) GetTask() string {
	if v == nil {
		return ""
	}
	return v.Task
}

func (v *V3IncidentsPostmortemsPostmortemFollowUp) GetIsDone() bool {
	if v == nil {
		return false
	}
	return v.IsDone
}
