// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V3IncidentsTagsIncidentForTagsResponseTags struct {
}

type V3IncidentsTagsIncidentForTagsResponseRetriggerPolicy struct {
	EscalationPolicyID string     `json:"escalationPolicyId"`
	RetriggerAt        *time.Time `json:"retriggerAt,omitempty"`
	RetriggeredAt      *time.Time `json:"retriggeredAt,omitempty"`
}

func (v V3IncidentsTagsIncidentForTagsResponseRetriggerPolicy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3IncidentsTagsIncidentForTagsResponseRetriggerPolicy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"escalationPolicyId"}); err != nil {
		return err
	}
	return nil
}

func (v *V3IncidentsTagsIncidentForTagsResponseRetriggerPolicy) GetEscalationPolicyID() string {
	if v == nil {
		return ""
	}
	return v.EscalationPolicyID
}

func (v *V3IncidentsTagsIncidentForTagsResponseRetriggerPolicy) GetRetriggerAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.RetriggerAt
}

func (v *V3IncidentsTagsIncidentForTagsResponseRetriggerPolicy) GetRetriggeredAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.RetriggeredAt
}

type V3IncidentsTagsIncidentForTagsResponse struct {
	ID                   string                                      `json:"id"`
	ServiceID            string                                      `json:"service_id"`
	AlertSourceID        string                                      `json:"alert_source_id"`
	OrganizationID       string                                      `json:"organization_id"`
	SloID                *int64                                      `json:"slo_id,omitempty"`
	IncidentNumber       int64                                       `json:"incidentNumber"`
	Message              string                                      `json:"message"`
	AssignedTo           []V3IncidentsTagsAssignedTo                 `json:"assignedTo"`
	AdditionalResponders []V3IncidentsTagsAdditionalResponderDetails `json:"additional_responders"`
	Description          string                                      `json:"description"`
	Status               string                                      `json:"status"`
	TimeOfCreation       time.Time                                   `json:"timeOfCreation"`
	UpdatedAt            time.Time                                   `json:"updated_at"`
	LastAcknowledgedAt   *time.Time                                  `json:"last_acknowledged_at,omitempty"`
	Tags                 V3IncidentsTagsIncidentForTagsResponseTags  `json:"tags"`
	Logs                 []V3IncidentsTagsLogs                       `json:"logs"`
	// Incident analytics data.
	Analytics      V3IncidentsTagsAnalytics       `json:"analytics"`
	PinnedMessages []V3IncidentsTagsPinnedMessage `json:"pinned_messages"`
	CreatedBy      *string                        `json:"created_by,omitempty"`
	SenderEmail    *string                        `json:"sender_email,omitempty"`
	Deleted        bool                           `json:"deleted"`
	EventCount     int64                          `json:"event_count"`
	DedupData      V3IncidentsTagsDedupData       `json:"dedup_data"`
	// Represents the RBAC owner of an entity.
	Owner                                    CommonV3RBACOwner                                      `json:"owner"`
	AccessControl                            []CommonV3RBACEntityPermission                         `json:"access_control"`
	RelevantUsers                            []string                                               `json:"relevantUsers"`
	RelevantEscalationPolicies               []string                                               `json:"relevantEscalationPolicies"`
	RelevantSquads                           []string                                               `json:"relevantSquads"`
	RelevantSchedules                        []string                                               `json:"relevantSchedules"`
	RelevantPeopleLogs                       []V3IncidentsTagsRelevantPeopleLog                     `json:"relevantPeopleLogs"`
	ResponseNotes                            []V3IncidentsTagsResponseNote                          `json:"responseNotes"`
	Attachments                              []string                                               `json:"attachments"`
	RetriggerPolicy                          *V3IncidentsTagsIncidentForTagsResponseRetriggerPolicy `json:"retriggerPolicy,omitempty"`
	WebformID                                *int64                                                 `json:"webform_id,omitempty"`
	WebformSubmissionID                      *int64                                                 `json:"webform_submission_id,omitempty"`
	IsChild                                  bool                                                   `json:"is_child"`
	Parent                                   *V3IncidentsTagsMergeIncidentEntityReference           `json:"parent,omitempty"`
	Children                                 []V3IncidentsTagsMergeIncidentEntityReference          `json:"children"`
	DidAutoPause                             bool                                                   `json:"did_auto_pause"`
	DidAutoPauseTimeout                      bool                                                   `json:"did_auto_pause_timeout"`
	AutoPauseEndsAt                          time.Time                                              `json:"auto_pause_ends_at"`
	ManuallyMarkedTransientAlertFeedbackType string                                                 `json:"manually_marked_transient_alert_feedback_type"`
	ClassificationID                         int64                                                  `json:"classification_id"`
	GroupedAlertCount                        int64                                                  `json:"grouped_alert_count"`
	// Represents the priority of an incident.
	Priority             *V3IncidentsTagsIncidentPriority `json:"priority,omitempty"`
	HasPriority          bool                             `json:"has_priority"`
	SnoozeDetails        V3IncidentsTagsSnoozeDetails     `json:"snooze_details"`
	DidNotificationDelay bool                             `json:"did_notification_delay"`
	// Policy for delaying notifications.
	NotificationDelayPolicy V3IncidentsTagsNotificationDelayPolicy `json:"notification_delay_policy"`
	DigestID                string                                 `json:"digest_id"`
}

func (v V3IncidentsTagsIncidentForTagsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3IncidentsTagsIncidentForTagsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"id", "service_id", "alert_source_id", "organization_id", "incidentNumber", "message", "assignedTo", "additional_responders", "description", "status", "timeOfCreation", "updated_at", "tags", "logs", "analytics", "deleted", "event_count", "dedup_data", "owner", "is_child", "children", "did_auto_pause", "did_auto_pause_timeout", "auto_pause_ends_at", "manually_marked_transient_alert_feedback_type", "classification_id", "grouped_alert_count", "has_priority", "snooze_details", "did_notification_delay", "notification_delay_policy", "digest_id"}); err != nil {
		return err
	}
	return nil
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetAlertSourceID() string {
	if v == nil {
		return ""
	}
	return v.AlertSourceID
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetSloID() *int64 {
	if v == nil {
		return nil
	}
	return v.SloID
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetIncidentNumber() int64 {
	if v == nil {
		return 0
	}
	return v.IncidentNumber
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetMessage() string {
	if v == nil {
		return ""
	}
	return v.Message
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetAssignedTo() []V3IncidentsTagsAssignedTo {
	if v == nil {
		return []V3IncidentsTagsAssignedTo{}
	}
	return v.AssignedTo
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetAdditionalResponders() []V3IncidentsTagsAdditionalResponderDetails {
	if v == nil {
		return []V3IncidentsTagsAdditionalResponderDetails{}
	}
	return v.AdditionalResponders
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetDescription() string {
	if v == nil {
		return ""
	}
	return v.Description
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetStatus() string {
	if v == nil {
		return ""
	}
	return v.Status
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetTimeOfCreation() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.TimeOfCreation
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetUpdatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.UpdatedAt
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetLastAcknowledgedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.LastAcknowledgedAt
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetTags() V3IncidentsTagsIncidentForTagsResponseTags {
	if v == nil {
		return V3IncidentsTagsIncidentForTagsResponseTags{}
	}
	return v.Tags
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetLogs() []V3IncidentsTagsLogs {
	if v == nil {
		return []V3IncidentsTagsLogs{}
	}
	return v.Logs
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetAnalytics() V3IncidentsTagsAnalytics {
	if v == nil {
		return V3IncidentsTagsAnalytics{}
	}
	return v.Analytics
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetPinnedMessages() []V3IncidentsTagsPinnedMessage {
	if v == nil {
		return nil
	}
	return v.PinnedMessages
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetCreatedBy() *string {
	if v == nil {
		return nil
	}
	return v.CreatedBy
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetSenderEmail() *string {
	if v == nil {
		return nil
	}
	return v.SenderEmail
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetDeleted() bool {
	if v == nil {
		return false
	}
	return v.Deleted
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetEventCount() int64 {
	if v == nil {
		return 0
	}
	return v.EventCount
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetDedupData() V3IncidentsTagsDedupData {
	if v == nil {
		return V3IncidentsTagsDedupData{}
	}
	return v.DedupData
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetOwner() CommonV3RBACOwner {
	if v == nil {
		return CommonV3RBACOwner{}
	}
	return v.Owner
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetAccessControl() []CommonV3RBACEntityPermission {
	if v == nil {
		return nil
	}
	return v.AccessControl
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetRelevantUsers() []string {
	if v == nil {
		return nil
	}
	return v.RelevantUsers
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetRelevantEscalationPolicies() []string {
	if v == nil {
		return nil
	}
	return v.RelevantEscalationPolicies
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetRelevantSquads() []string {
	if v == nil {
		return nil
	}
	return v.RelevantSquads
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetRelevantSchedules() []string {
	if v == nil {
		return nil
	}
	return v.RelevantSchedules
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetRelevantPeopleLogs() []V3IncidentsTagsRelevantPeopleLog {
	if v == nil {
		return nil
	}
	return v.RelevantPeopleLogs
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetResponseNotes() []V3IncidentsTagsResponseNote {
	if v == nil {
		return nil
	}
	return v.ResponseNotes
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetAttachments() []string {
	if v == nil {
		return nil
	}
	return v.Attachments
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetRetriggerPolicy() *V3IncidentsTagsIncidentForTagsResponseRetriggerPolicy {
	if v == nil {
		return nil
	}
	return v.RetriggerPolicy
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetWebformID() *int64 {
	if v == nil {
		return nil
	}
	return v.WebformID
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetWebformSubmissionID() *int64 {
	if v == nil {
		return nil
	}
	return v.WebformSubmissionID
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetIsChild() bool {
	if v == nil {
		return false
	}
	return v.IsChild
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetParent() *V3IncidentsTagsMergeIncidentEntityReference {
	if v == nil {
		return nil
	}
	return v.Parent
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetChildren() []V3IncidentsTagsMergeIncidentEntityReference {
	if v == nil {
		return []V3IncidentsTagsMergeIncidentEntityReference{}
	}
	return v.Children
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetDidAutoPause() bool {
	if v == nil {
		return false
	}
	return v.DidAutoPause
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetDidAutoPauseTimeout() bool {
	if v == nil {
		return false
	}
	return v.DidAutoPauseTimeout
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetAutoPauseEndsAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.AutoPauseEndsAt
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetManuallyMarkedTransientAlertFeedbackType() string {
	if v == nil {
		return ""
	}
	return v.ManuallyMarkedTransientAlertFeedbackType
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetClassificationID() int64 {
	if v == nil {
		return 0
	}
	return v.ClassificationID
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetGroupedAlertCount() int64 {
	if v == nil {
		return 0
	}
	return v.GroupedAlertCount
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetPriority() *V3IncidentsTagsIncidentPriority {
	if v == nil {
		return nil
	}
	return v.Priority
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetHasPriority() bool {
	if v == nil {
		return false
	}
	return v.HasPriority
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetSnoozeDetails() V3IncidentsTagsSnoozeDetails {
	if v == nil {
		return V3IncidentsTagsSnoozeDetails{}
	}
	return v.SnoozeDetails
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetDidNotificationDelay() bool {
	if v == nil {
		return false
	}
	return v.DidNotificationDelay
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetNotificationDelayPolicy() V3IncidentsTagsNotificationDelayPolicy {
	if v == nil {
		return V3IncidentsTagsNotificationDelayPolicy{}
	}
	return v.NotificationDelayPolicy
}

func (v *V3IncidentsTagsIncidentForTagsResponse) GetDigestID() string {
	if v == nil {
		return ""
	}
	return v.DigestID
}
