// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3IncidentsSnoozeNotificationsSnoozeIncidentRequest struct {
	SnoozeDurationInMins int `json:"snooze_duration_in_mins"`
}

func (v *V3IncidentsSnoozeNotificationsSnoozeIncidentRequest) GetSnoozeDurationInMins() int {
	if v == nil {
		return 0
	}
	return v.SnoozeDurationInMins
}
