// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4b7b51bad9cc

package components

type V3IncidentsSnoozeNotificationsUnsnoozeIncidentRequest struct {
	ReassignTo V3IncidentsSnoozeNotificationsReassignTo `json:"reassign_to"`
}

func (v *V3IncidentsSnoozeNotificationsUnsnoozeIncidentRequest) GetReassignTo() V3IncidentsSnoozeNotificationsReassignTo {
	if v == nil {
		return V3IncidentsSnoozeNotificationsReassignTo{}
	}
	return v.ReassignTo
}
