// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsTagsAssignTo - Represents the assignment target for delayed notifications.
type V3IncidentsTagsAssignTo struct {
	ID   string  `json:"id"`
	Type *string `json:"type,omitempty"`
}

func (v *V3IncidentsTagsAssignTo) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3IncidentsTagsAssignTo) GetType() *string {
	if v == nil {
		return nil
	}
	return v.Type
}
