// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
)

// V3IncidentsIncidentActionsCircleCIErrorMeta - Represents the metadata for a CircleCI error response.
type V3IncidentsIncidentActionsCircleCIErrorMeta struct {
	StatusCode   int64  `json:"status_code"`
	ErrorMessage string `json:"error_message"`
}

func (v V3IncidentsIncidentActionsCircleCIErrorMeta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3IncidentsIncidentActionsCircleCIErrorMeta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"status_code", "error_message"}); err != nil {
		return err
	}
	return nil
}

func (v *V3IncidentsIncidentActionsCircleCIErrorMeta) GetStatusCode() int64 {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3IncidentsIncidentActionsCircleCIErrorMeta) GetErrorMessage() string {
	if v == nil {
		return ""
	}
	return v.ErrorMessage
}
