// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsPostmortemsPostmortemAttachmentRequest - Represents an attachment in a postmortem request.
type V3IncidentsPostmortemsPostmortemAttachmentRequest struct {
	Key      *string `json:"key,omitempty"`
	MimeType *string `json:"mime_type,omitempty"`
	FileSize *string `json:"file_size,omitempty"`
}

func (v *V3IncidentsPostmortemsPostmortemAttachmentRequest) GetKey() *string {
	if v == nil {
		return nil
	}
	return v.Key
}

func (v *V3IncidentsPostmortemsPostmortemAttachmentRequest) GetMimeType() *string {
	if v == nil {
		return nil
	}
	return v.MimeType
}

func (v *V3IncidentsPostmortemsPostmortemAttachmentRequest) GetFileSize() *string {
	if v == nil {
		return nil
	}
	return v.FileSize
}
