// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3IncidentsSnoozeNotificationsUnsnoozeIncidentResponse struct {
	IncidentID string                                   `json:"incident_id"`
	IsSnoozed  bool                                     `json:"is_snoozed"`
	ReassignTo V3IncidentsSnoozeNotificationsReassignTo `json:"reassign_to"`
}

func (v *V3IncidentsSnoozeNotificationsUnsnoozeIncidentResponse) GetIncidentID() string {
	if v == nil {
		return ""
	}
	return v.IncidentID
}

func (v *V3IncidentsSnoozeNotificationsUnsnoozeIncidentResponse) GetIsSnoozed() bool {
	if v == nil {
		return false
	}
	return v.IsSnoozed
}

func (v *V3IncidentsSnoozeNotificationsUnsnoozeIncidentResponse) GetReassignTo() V3IncidentsSnoozeNotificationsReassignTo {
	if v == nil {
		return V3IncidentsSnoozeNotificationsReassignTo{}
	}
	return v.ReassignTo
}
