// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResolutionReason struct {
	Message string `json:"message"`
}

func (r *ResolutionReason) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

// V3IncidentsResolveIncidentRequest - Request body for resolving an incident.
type V3IncidentsResolveIncidentRequest struct {
	ResolutionReason ResolutionReason `json:"resolution_reason"`
}

func (v *V3IncidentsResolveIncidentRequest) GetResolutionReason() ResolutionReason {
	if v == nil {
		return ResolutionReason{}
	}
	return v.ResolutionReason
}
