// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsIncidentPriorityUpdateRequest - Request body for updating incident priority.
type V3IncidentsIncidentPriorityUpdateRequest struct {
	Priority *string `json:"priority,omitempty"`
}

func (v *V3IncidentsIncidentPriorityUpdateRequest) GetPriority() *string {
	if v == nil {
		return nil
	}
	return v.Priority
}
