// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3IncidentsIncidentExportAsyncResponse struct {
	Message   string
	RequestID string
}

func (v *V3IncidentsIncidentExportAsyncResponse) GetMessage() string {
	if v == nil {
		return ""
	}
	return v.Message
}

func (v *V3IncidentsIncidentExportAsyncResponse) GetRequestID() string {
	if v == nil {
		return ""
	}
	return v.RequestID
}
