// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsPostmortemsUpdatePostmortemRequest - Request body for updating an existing postmortem.
type V3IncidentsPostmortemsUpdatePostmortemRequest struct {
	OwnerID        *string                                             `json:"owner_id,omitempty"`
	Postmortem     *string                                             `json:"postmortem,omitempty"`
	FollowUps      []V3IncidentsPostmortemsPostmortemFollowUp          `json:"follow_ups,omitempty"`
	NewAttachments []V3IncidentsPostmortemsPostmortemAttachmentRequest `json:"new_attachments,omitempty"`
	Title          *string                                             `json:"title,omitempty"`
	// Represents the status of a postmortem.
	Status *V3IncidentsPostmortemsPostmortemStatus `json:"status,omitempty"`
}

func (v *V3IncidentsPostmortemsUpdatePostmortemRequest) GetOwnerID() *string {
	if v == nil {
		return nil
	}
	return v.OwnerID
}

func (v *V3IncidentsPostmortemsUpdatePostmortemRequest) GetPostmortem() *string {
	if v == nil {
		return nil
	}
	return v.Postmortem
}

func (v *V3IncidentsPostmortemsUpdatePostmortemRequest) GetFollowUps() []V3IncidentsPostmortemsPostmortemFollowUp {
	if v == nil {
		return nil
	}
	return v.FollowUps
}

func (v *V3IncidentsPostmortemsUpdatePostmortemRequest) GetNewAttachments() []V3IncidentsPostmortemsPostmortemAttachmentRequest {
	if v == nil {
		return nil
	}
	return v.NewAttachments
}

func (v *V3IncidentsPostmortemsUpdatePostmortemRequest) GetTitle() *string {
	if v == nil {
		return nil
	}
	return v.Title
}

func (v *V3IncidentsPostmortemsUpdatePostmortemRequest) GetStatus() *V3IncidentsPostmortemsPostmortemStatus {
	if v == nil {
		return nil
	}
	return v.Status
}
