// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsReassignIncidentRequest - Request body for reassigning an incident.
type V3IncidentsReassignIncidentRequest struct {
	// Assignment target for an incident.
	ReassignTo V3IncidentsAssignee `json:"reassignTo"`
}

func (v *V3IncidentsReassignIncidentRequest) GetReassignTo() V3IncidentsAssignee {
	if v == nil {
		return V3IncidentsAssignee{}
	}
	return v.ReassignTo
}

// #region class-body-v3incidentsreassignincidentrequest
// #endregion class-body-v3incidentsreassignincidentrequest
