// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 84479c27ba42

package components

// V3IncidentsCommunicationCardsCreateSlackChannelRequest - Request body for creating a Slack channel in a communication card.
type V3IncidentsCommunicationCardsCreateSlackChannelRequest struct {
	ChannelName string `json:"channel_name"`
	IncidentID  string `json:"incident_id"`
}

func (v *V3IncidentsCommunicationCardsCreateSlackChannelRequest) GetChannelName() string {
	if v == nil {
		return ""
	}
	return v.ChannelName
}

func (v *V3IncidentsCommunicationCardsCreateSlackChannelRequest) GetIncidentID() string {
	if v == nil {
		return ""
	}
	return v.IncidentID
}
