// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/solarwinds/squadcast-sdk-go/internal/utils"
)

type V3IncidentsMergeNewParentIncidentRequestTags struct {
}

func (v V3IncidentsMergeNewParentIncidentRequestTags) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3IncidentsMergeNewParentIncidentRequestTags) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

// #region class-body-v3incidentsmergenewparentincidentrequesttags
// #endregion class-body-v3incidentsmergenewparentincidentrequesttags

// V3IncidentsMergeNewParentIncidentRequest - Details used to create a new parent incident while merging incidents.
type V3IncidentsMergeNewParentIncidentRequest struct {
	Message     string  `json:"message"`
	Description *string `json:"description,omitempty"`
	// Represents the priority of an incident.
	Priority *V3IncidentsIncidentPriority                  `json:"priority,omitempty"`
	Tags     *V3IncidentsMergeNewParentIncidentRequestTags `json:"tags,omitempty"`
	// Assignment target for an incident.
	Assignee  V3IncidentsAssignee `json:"assignee"`
	ServiceID string              `json:"service_id"`
}

func (v V3IncidentsMergeNewParentIncidentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3IncidentsMergeNewParentIncidentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"message", "assignee", "service_id"}); err != nil {
		return err
	}
	return nil
}

func (v *V3IncidentsMergeNewParentIncidentRequest) GetMessage() string {
	if v == nil {
		return ""
	}
	return v.Message
}

func (v *V3IncidentsMergeNewParentIncidentRequest) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V3IncidentsMergeNewParentIncidentRequest) GetPriority() *V3IncidentsIncidentPriority {
	if v == nil {
		return nil
	}
	return v.Priority
}

func (v *V3IncidentsMergeNewParentIncidentRequest) GetTags() *V3IncidentsMergeNewParentIncidentRequestTags {
	if v == nil {
		return nil
	}
	return v.Tags
}

func (v *V3IncidentsMergeNewParentIncidentRequest) GetAssignee() V3IncidentsAssignee {
	if v == nil {
		return V3IncidentsAssignee{}
	}
	return v.Assignee
}

func (v *V3IncidentsMergeNewParentIncidentRequest) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

// #region class-body-v3incidentsmergenewparentincidentrequest
// #endregion class-body-v3incidentsmergenewparentincidentrequest
