// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

// V3IncidentsResponseNote - Represents a response note in an incident.
type V3IncidentsResponseNote struct {
	TimeOfNote time.Time `json:"timeOfNote"`
	Note       string    `json:"note"`
	UserID     string    `json:"userId"`
}

func (v V3IncidentsResponseNote) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3IncidentsResponseNote) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"timeOfNote", "note", "userId"}); err != nil {
		return err
	}
	return nil
}

func (v *V3IncidentsResponseNote) GetTimeOfNote() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.TimeOfNote
}

func (v *V3IncidentsResponseNote) GetNote() string {
	if v == nil {
		return ""
	}
	return v.Note
}

func (v *V3IncidentsResponseNote) GetUserID() string {
	if v == nil {
		return ""
	}
	return v.UserID
}
