// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// V3IncidentsTagsIncidentPriority - Represents the priority of an incident.
type V3IncidentsTagsIncidentPriority string

const (
	V3IncidentsTagsIncidentPriorityP1 V3IncidentsTagsIncidentPriority = "P1"
	V3IncidentsTagsIncidentPriorityP2 V3IncidentsTagsIncidentPriority = "P2"
	V3IncidentsTagsIncidentPriorityP3 V3IncidentsTagsIncidentPriority = "P3"
	V3IncidentsTagsIncidentPriorityP4 V3IncidentsTagsIncidentPriority = "P4"
	V3IncidentsTagsIncidentPriorityP5 V3IncidentsTagsIncidentPriority = "P5"
)

func (e V3IncidentsTagsIncidentPriority) ToPointer() *V3IncidentsTagsIncidentPriority {
	return &e
}
func (e *V3IncidentsTagsIncidentPriority) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "P1":
		fallthrough
	case "P2":
		fallthrough
	case "P3":
		fallthrough
	case "P4":
		fallthrough
	case "P5":
		*e = V3IncidentsTagsIncidentPriority(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3IncidentsTagsIncidentPriority: %v", v)
	}
}
