// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsAnalytics - Incident analytics data.
type V3IncidentsAnalytics struct {
	// Analytics metrics for TTA (Time to Acknowledge) and TTR (Time to Resolve).
	Tta V3IncidentsAnalyticsMetrics `json:"tta"`
	// Analytics metrics for TTA (Time to Acknowledge) and TTR (Time to Resolve).
	Ttr V3IncidentsAnalyticsMetrics `json:"ttr"`
}

func (v *V3IncidentsAnalytics) GetTta() V3IncidentsAnalyticsMetrics {
	if v == nil {
		return V3IncidentsAnalyticsMetrics{}
	}
	return v.Tta
}

func (v *V3IncidentsAnalytics) GetTtr() V3IncidentsAnalyticsMetrics {
	if v == nil {
		return V3IncidentsAnalyticsMetrics{}
	}
	return v.Ttr
}
