// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// V3IncidentsIncidentPriority - Represents the priority of an incident.
type V3IncidentsIncidentPriority string

const (
	V3IncidentsIncidentPriorityP1 V3IncidentsIncidentPriority = "P1"
	V3IncidentsIncidentPriorityP2 V3IncidentsIncidentPriority = "P2"
	V3IncidentsIncidentPriorityP3 V3IncidentsIncidentPriority = "P3"
	V3IncidentsIncidentPriorityP4 V3IncidentsIncidentPriority = "P4"
	V3IncidentsIncidentPriorityP5 V3IncidentsIncidentPriority = "P5"
)

func (e V3IncidentsIncidentPriority) ToPointer() *V3IncidentsIncidentPriority {
	return &e
}
func (e *V3IncidentsIncidentPriority) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "P1":
		fallthrough
	case "P2":
		fallthrough
	case "P3":
		fallthrough
	case "P4":
		fallthrough
	case "P5":
		*e = V3IncidentsIncidentPriority(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3IncidentsIncidentPriority: %v", v)
	}
}
