// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3IncidentsSnoozeNotificationsSnoozeIncidentResponse struct {
	IncidentID    string `json:"incident_id"`
	IsSnoozed     bool   `json:"is_snoozed"`
	SnoozeEndTime string `json:"snooze_end_time"`
}

func (v *V3IncidentsSnoozeNotificationsSnoozeIncidentResponse) GetIncidentID() string {
	if v == nil {
		return ""
	}
	return v.IncidentID
}

func (v *V3IncidentsSnoozeNotificationsSnoozeIncidentResponse) GetIsSnoozed() bool {
	if v == nil {
		return false
	}
	return v.IsSnoozed
}

func (v *V3IncidentsSnoozeNotificationsSnoozeIncidentResponse) GetSnoozeEndTime() string {
	if v == nil {
		return ""
	}
	return v.SnoozeEndTime
}
