// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsBulkIncidentIDsRequest - Request body for bulk incident operations (acknowledge, resolve).
type V3IncidentsBulkIncidentIDsRequest struct {
	IncidentIds []string `json:"incident_ids"`
}

func (v *V3IncidentsBulkIncidentIDsRequest) GetIncidentIds() []string {
	if v == nil {
		return []string{}
	}
	return v.IncidentIds
}
