// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3IncidentsSnoozeNotificationsReassignTo struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

func (v *V3IncidentsSnoozeNotificationsReassignTo) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3IncidentsSnoozeNotificationsReassignTo) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}
