// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3IncidentsTagsDedupData struct {
	Key  *string `json:"key,omitempty"`
	Hash *string `json:"hash,omitempty"`
}

func (v *V3IncidentsTagsDedupData) GetKey() *string {
	if v == nil {
		return nil
	}
	return v.Key
}

func (v *V3IncidentsTagsDedupData) GetHash() *string {
	if v == nil {
		return nil
	}
	return v.Hash
}
