// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsNotesCreateNoteRequest - Request body for creating a new note.
type V3IncidentsNotesCreateNoteRequest struct {
	Message     string   `json:"message"`
	Attachments []string `json:"attachments"`
}

func (v *V3IncidentsNotesCreateNoteRequest) GetMessage() string {
	if v == nil {
		return ""
	}
	return v.Message
}

func (v *V3IncidentsNotesCreateNoteRequest) GetAttachments() []string {
	if v == nil {
		return []string{}
	}
	return v.Attachments
}
