// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3IncidentsTagsAppendTagRequestTags struct {
}

// #region class-body-v3incidentstagsappendtagrequesttags
// #endregion class-body-v3incidentstagsappendtagrequesttags

type V3IncidentsTagsAppendTagRequest struct {
	Tags *V3IncidentsTagsAppendTagRequestTags `json:"tags,omitempty"`
}

func (v *V3IncidentsTagsAppendTagRequest) GetTags() *V3IncidentsTagsAppendTagRequestTags {
	if v == nil {
		return nil
	}
	return v.Tags
}

// #region class-body-v3incidentstagsappendtagrequest
// #endregion class-body-v3incidentstagsappendtagrequest
