// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Deleted   bool   `json:"deleted"`
}

func (u *User) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *User) GetFirstName() string {
	if u == nil {
		return ""
	}
	return u.FirstName
}

func (u *User) GetLastName() string {
	if u == nil {
		return ""
	}
	return u.LastName
}

func (u *User) GetDeleted() bool {
	if u == nil {
		return false
	}
	return u.Deleted
}

// V3IncidentsNotesNoteResponse - Represents a note associated with an incident.
type V3IncidentsNotesNoteResponse struct {
	ID              string   `json:"id"`
	CreatedAt       string   `json:"created_at"`
	UpdatedAt       string   `json:"updated_at"`
	OrganizationID  string   `json:"organization_id"`
	IncidentID      string   `json:"incident_id"`
	UserID          string   `json:"user_id"`
	Message         string   `json:"message"`
	Type            string   `json:"type"`
	Attachments     []string `json:"attachments"`
	User            User     `json:"user"`
	ReplacedMessage string   `json:"replaced_message"`
}

func (v *V3IncidentsNotesNoteResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3IncidentsNotesNoteResponse) GetCreatedAt() string {
	if v == nil {
		return ""
	}
	return v.CreatedAt
}

func (v *V3IncidentsNotesNoteResponse) GetUpdatedAt() string {
	if v == nil {
		return ""
	}
	return v.UpdatedAt
}

func (v *V3IncidentsNotesNoteResponse) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V3IncidentsNotesNoteResponse) GetIncidentID() string {
	if v == nil {
		return ""
	}
	return v.IncidentID
}

func (v *V3IncidentsNotesNoteResponse) GetUserID() string {
	if v == nil {
		return ""
	}
	return v.UserID
}

func (v *V3IncidentsNotesNoteResponse) GetMessage() string {
	if v == nil {
		return ""
	}
	return v.Message
}

func (v *V3IncidentsNotesNoteResponse) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *V3IncidentsNotesNoteResponse) GetAttachments() []string {
	if v == nil {
		return []string{}
	}
	return v.Attachments
}

func (v *V3IncidentsNotesNoteResponse) GetUser() User {
	if v == nil {
		return User{}
	}
	return v.User
}

func (v *V3IncidentsNotesNoteResponse) GetReplacedMessage() string {
	if v == nil {
		return ""
	}
	return v.ReplacedMessage
}
