// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsIncidentActionsEventWebhookTrigger - Represents a webhook trigger with event class and type.
type V3IncidentsIncidentActionsEventWebhookTrigger struct {
	EventClass string `json:"event_class"`
	EventType  string `json:"event_type"`
}

func (v *V3IncidentsIncidentActionsEventWebhookTrigger) GetEventClass() string {
	if v == nil {
		return ""
	}
	return v.EventClass
}

func (v *V3IncidentsIncidentActionsEventWebhookTrigger) GetEventType() string {
	if v == nil {
		return ""
	}
	return v.EventType
}

// #region class-body-v3incidentsincidentactionseventwebhooktrigger
// #endregion class-body-v3incidentsincidentactionseventwebhooktrigger
