// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsServiceOwnerFilter - Filter criteria for service owner in an export.
type V3IncidentsServiceOwnerFilter struct {
	UserIDs               []string `json:"userIDs"`
	SquadIDs              []string `json:"squadIDs"`
	UserIDsAndTheirSquads []string `json:"userIDsAndTheirSquads,omitempty"`
}

func (v *V3IncidentsServiceOwnerFilter) GetUserIDs() []string {
	if v == nil {
		return []string{}
	}
	return v.UserIDs
}

func (v *V3IncidentsServiceOwnerFilter) GetSquadIDs() []string {
	if v == nil {
		return []string{}
	}
	return v.SquadIDs
}

func (v *V3IncidentsServiceOwnerFilter) GetUserIDsAndTheirSquads() []string {
	if v == nil {
		return nil
	}
	return v.UserIDsAndTheirSquads
}
