// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IncidentsPostmortemsTotalPostmortemCount - Represents the total count of postmortems.
type V3IncidentsPostmortemsTotalPostmortemCount struct {
	Count int64 `json:"count"`
}

func (v *V3IncidentsPostmortemsTotalPostmortemCount) GetCount() int64 {
	if v == nil {
		return 0
	}
	return v.Count
}
