// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1e7cf2031a1a

package components

type V3ServicesSuppressionRulesBasicExpression struct {
	LHS string `json:"lhs"`
	Op  string `json:"op"`
	RHS string `json:"rhs"`
}

func (v *V3ServicesSuppressionRulesBasicExpression) GetLHS() string {
	if v == nil {
		return ""
	}
	return v.LHS
}

func (v *V3ServicesSuppressionRulesBasicExpression) GetOp() string {
	if v == nil {
		return ""
	}
	return v.Op
}

func (v *V3ServicesSuppressionRulesBasicExpression) GetRHS() string {
	if v == nil {
		return ""
	}
	return v.RHS
}
