// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3ServicesEscalationPolicyBasic - Represents the basic details of an Escalation Policy for a service.
type V3ServicesEscalationPolicyBasic struct {
	// The unique identifier for the escalation policy.
	ID string `json:"id"`
	// The name of the escalation policy.
	Name string `json:"name"`
	// A description of the escalation policy.
	Description string `json:"description"`
	// The URL-friendly slug for the policy name.
	Slug string `json:"slug"`
}

func (v *V3ServicesEscalationPolicyBasic) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3ServicesEscalationPolicyBasic) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3ServicesEscalationPolicyBasic) GetDescription() string {
	if v == nil {
		return ""
	}
	return v.Description
}

func (v *V3ServicesEscalationPolicyBasic) GetSlug() string {
	if v == nil {
		return ""
	}
	return v.Slug
}
