// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V3ServicesSuppressionRulesSuppressionRulesContainerResponse struct {
	ID             string                                      `json:"id"`
	CreatedAt      time.Time                                   `json:"created_at"`
	UpdatedAt      time.Time                                   `json:"updated_at"`
	ServiceID      string                                      `json:"service_id"`
	OrganizationID string                                      `json:"organization_id"`
	Rules          []V3ServicesSuppressionRulesSuppressionRule `json:"rules"`
}

func (v V3ServicesSuppressionRulesSuppressionRulesContainerResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3ServicesSuppressionRulesSuppressionRulesContainerResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"id", "created_at", "updated_at", "service_id", "organization_id", "rules"}); err != nil {
		return err
	}
	return nil
}

func (v *V3ServicesSuppressionRulesSuppressionRulesContainerResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3ServicesSuppressionRulesSuppressionRulesContainerResponse) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *V3ServicesSuppressionRulesSuppressionRulesContainerResponse) GetUpdatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.UpdatedAt
}

func (v *V3ServicesSuppressionRulesSuppressionRulesContainerResponse) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *V3ServicesSuppressionRulesSuppressionRulesContainerResponse) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V3ServicesSuppressionRulesSuppressionRulesContainerResponse) GetRules() []V3ServicesSuppressionRulesSuppressionRule {
	if v == nil {
		return []V3ServicesSuppressionRulesSuppressionRule{}
	}
	return v.Rules
}
