// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 54e0c38c53fe

package components

type V3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest struct {
	Rules []V3ServicesRoutingRulesRoutingRule `json:"rules"`
}

func (v *V3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest) GetRules() []V3ServicesRoutingRulesRoutingRule {
	if v == nil {
		return []V3ServicesRoutingRulesRoutingRule{}
	}
	return v.Rules
}
