// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ServicesSuppressionRulesTimeslot struct {
	TimeZone   string                                     `json:"time_zone"`
	StartTime  string                                     `json:"start_time"`
	EndTime    string                                     `json:"end_time"`
	IsAllday   bool                                       `json:"is_allday"`
	Repetition string                                     `json:"repetition"`
	IsCustom   bool                                       `json:"is_custom"`
	Custom     V3ServicesSuppressionRulesCustomRepetition `json:"custom"`
	EndsNever  bool                                       `json:"ends_never"`
	EndsOn     string                                     `json:"ends_on"`
}

func (v *V3ServicesSuppressionRulesTimeslot) GetTimeZone() string {
	if v == nil {
		return ""
	}
	return v.TimeZone
}

func (v *V3ServicesSuppressionRulesTimeslot) GetStartTime() string {
	if v == nil {
		return ""
	}
	return v.StartTime
}

func (v *V3ServicesSuppressionRulesTimeslot) GetEndTime() string {
	if v == nil {
		return ""
	}
	return v.EndTime
}

func (v *V3ServicesSuppressionRulesTimeslot) GetIsAllday() bool {
	if v == nil {
		return false
	}
	return v.IsAllday
}

func (v *V3ServicesSuppressionRulesTimeslot) GetRepetition() string {
	if v == nil {
		return ""
	}
	return v.Repetition
}

func (v *V3ServicesSuppressionRulesTimeslot) GetIsCustom() bool {
	if v == nil {
		return false
	}
	return v.IsCustom
}

func (v *V3ServicesSuppressionRulesTimeslot) GetCustom() V3ServicesSuppressionRulesCustomRepetition {
	if v == nil {
		return V3ServicesSuppressionRulesCustomRepetition{}
	}
	return v.Custom
}

func (v *V3ServicesSuppressionRulesTimeslot) GetEndsNever() bool {
	if v == nil {
		return false
	}
	return v.EndsNever
}

func (v *V3ServicesSuppressionRulesTimeslot) GetEndsOn() string {
	if v == nil {
		return ""
	}
	return v.EndsOn
}
