// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DedupKeyOverlay struct {
	Template string `json:"template"`
	Duration int64  `json:"duration"`
}

func (d *DedupKeyOverlay) GetTemplate() string {
	if d == nil {
		return ""
	}
	return d.Template
}

func (d *DedupKeyOverlay) GetDuration() int64 {
	if d == nil {
		return 0
	}
	return d.Duration
}

type V3ServicesOverlayUpdateDedupKeyOverlayRequest struct {
	OverlayTemplateType string          `json:"overlay_template_type"`
	DedupKeyOverlay     DedupKeyOverlay `json:"dedup_key_overlay"`
}

func (v *V3ServicesOverlayUpdateDedupKeyOverlayRequest) GetOverlayTemplateType() string {
	if v == nil {
		return ""
	}
	return v.OverlayTemplateType
}

func (v *V3ServicesOverlayUpdateDedupKeyOverlayRequest) GetDedupKeyOverlay() DedupKeyOverlay {
	if v == nil {
		return DedupKeyOverlay{}
	}
	return v.DedupKeyOverlay
}
