// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 922a2ac9de16

package components

type V3ServicesOverlayOptInForKeyBasedDeduplicationRequest struct {
	DedupKeyEnabled *bool `json:"dedup_key_enabled,omitempty"`
}

func (v *V3ServicesOverlayOptInForKeyBasedDeduplicationRequest) GetDedupKeyEnabled() *bool {
	if v == nil {
		return nil
	}
	return v.DedupKeyEnabled
}
