// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest struct {
	Rules []V3ServicesRoutingRulesRoutingRule `json:"rules"`
}

func (v *V3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest) GetRules() []V3ServicesRoutingRulesRoutingRule {
	if v == nil {
		return []V3ServicesRoutingRulesRoutingRule{}
	}
	return v.Rules
}

// #region class-body-v3servicesroutingrulescreateorupdateroutingrulesrequest
// #endregion class-body-v3servicesroutingrulescreateorupdateroutingrulesrequest
