// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e7d3043456d4

package components

type V3ServicesJiraStatusMap struct {
	JiraStatus   string `json:"jira_status"`
	SystemStatus string `json:"system_status"`
}

func (v *V3ServicesJiraStatusMap) GetJiraStatus() string {
	if v == nil {
		return ""
	}
	return v.JiraStatus
}

func (v *V3ServicesJiraStatusMap) GetSystemStatus() string {
	if v == nil {
		return ""
	}
	return v.SystemStatus
}
