// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ServicesOverlayCustomContent struct {
	Message     string `json:"message"`
	Description string `json:"description"`
}

func (v *V3ServicesOverlayCustomContent) GetMessage() string {
	if v == nil {
		return ""
	}
	return v.Message
}

func (v *V3ServicesOverlayCustomContent) GetDescription() string {
	if v == nil {
		return ""
	}
	return v.Description
}
