// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ServicesAPTAConfig struct {
	IsEnabled     bool    `json:"is_enabled"`
	TimeoutInMins float64 `json:"timeout_in_mins"`
}

func (v *V3ServicesAPTAConfig) GetIsEnabled() bool {
	if v == nil {
		return false
	}
	return v.IsEnabled
}

func (v *V3ServicesAPTAConfig) GetTimeoutInMins() float64 {
	if v == nil {
		return 0.0
	}
	return v.TimeoutInMins
}
