// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ServicesNotificationDelayConfigRequestFixedTimeslotConfig struct {
	StartTime  *string `json:"start_time,omitempty"`
	EndTime    *string `json:"end_time,omitempty"`
	RepeatDays []int   `json:"repeat_days,omitempty"`
}

func (v *V3ServicesNotificationDelayConfigRequestFixedTimeslotConfig) GetStartTime() *string {
	if v == nil {
		return nil
	}
	return v.StartTime
}

func (v *V3ServicesNotificationDelayConfigRequestFixedTimeslotConfig) GetEndTime() *string {
	if v == nil {
		return nil
	}
	return v.EndTime
}

func (v *V3ServicesNotificationDelayConfigRequestFixedTimeslotConfig) GetRepeatDays() []int {
	if v == nil {
		return nil
	}
	return v.RepeatDays
}

type V3ServicesNotificationDelayConfigRequestCustomTimeslots struct {
}

type V3ServicesNotificationDelayConfigRequestAssignedTo struct {
	ID   *string `json:"id,omitempty"`
	Type *string `json:"type,omitempty"`
}

func (v *V3ServicesNotificationDelayConfigRequestAssignedTo) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V3ServicesNotificationDelayConfigRequestAssignedTo) GetType() *string {
	if v == nil {
		return nil
	}
	return v.Type
}

type V3ServicesNotificationDelayConfigRequest struct {
	IsEnabled              bool                                                         `json:"is_enabled"`
	Timezone               *string                                                      `json:"timezone,omitempty"`
	FixedTimeslotConfig    *V3ServicesNotificationDelayConfigRequestFixedTimeslotConfig `json:"fixed_timeslot_config,omitempty"`
	CustomTimeslotsEnabled *bool                                                        `json:"custom_timeslots_enabled,omitempty"`
	CustomTimeslots        *V3ServicesNotificationDelayConfigRequestCustomTimeslots     `json:"custom_timeslots,omitempty"`
	AssignedTo             *V3ServicesNotificationDelayConfigRequestAssignedTo          `json:"assigned_to,omitempty"`
}

func (v *V3ServicesNotificationDelayConfigRequest) GetIsEnabled() bool {
	if v == nil {
		return false
	}
	return v.IsEnabled
}

func (v *V3ServicesNotificationDelayConfigRequest) GetTimezone() *string {
	if v == nil {
		return nil
	}
	return v.Timezone
}

func (v *V3ServicesNotificationDelayConfigRequest) GetFixedTimeslotConfig() *V3ServicesNotificationDelayConfigRequestFixedTimeslotConfig {
	if v == nil {
		return nil
	}
	return v.FixedTimeslotConfig
}

func (v *V3ServicesNotificationDelayConfigRequest) GetCustomTimeslotsEnabled() *bool {
	if v == nil {
		return nil
	}
	return v.CustomTimeslotsEnabled
}

func (v *V3ServicesNotificationDelayConfigRequest) GetCustomTimeslots() *V3ServicesNotificationDelayConfigRequestCustomTimeslots {
	if v == nil {
		return nil
	}
	return v.CustomTimeslots
}

func (v *V3ServicesNotificationDelayConfigRequest) GetAssignedTo() *V3ServicesNotificationDelayConfigRequestAssignedTo {
	if v == nil {
		return nil
	}
	return v.AssignedTo
}
