// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ServicesCreateServiceRequest struct {
	Name                            string                                    `json:"name"`
	EscalationPolicyID              string                                    `json:"escalation_policy_id"`
	Description                     *string                                   `json:"description,omitempty"`
	EmailPrefix                     *string                                   `json:"email_prefix,omitempty"`
	Maintainer                      *V3ServicesServiceMaintainer              `json:"maintainer,omitempty"`
	Tags                            []V3ServicesServiceTag                    `json:"tags,omitempty"`
	AutoPauseTransientAlertsConfig  *V3ServicesAPTAConfig                     `json:"auto_pause_transient_alerts_config,omitempty"`
	IntelligentAlertsGroupingConfig *V3ServicesIAGConfig                      `json:"intelligent_alerts_grouping_config,omitempty"`
	DelayNotificationConfig         *V3ServicesNotificationDelayConfigRequest `json:"delay_notification_config,omitempty"`
	DedupInitConfig                 *V3ServicesDedupInitConfig                `json:"dedup_init_config,omitempty"`
}

func (v *V3ServicesCreateServiceRequest) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3ServicesCreateServiceRequest) GetEscalationPolicyID() string {
	if v == nil {
		return ""
	}
	return v.EscalationPolicyID
}

func (v *V3ServicesCreateServiceRequest) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V3ServicesCreateServiceRequest) GetEmailPrefix() *string {
	if v == nil {
		return nil
	}
	return v.EmailPrefix
}

func (v *V3ServicesCreateServiceRequest) GetMaintainer() *V3ServicesServiceMaintainer {
	if v == nil {
		return nil
	}
	return v.Maintainer
}

func (v *V3ServicesCreateServiceRequest) GetTags() []V3ServicesServiceTag {
	if v == nil {
		return nil
	}
	return v.Tags
}

func (v *V3ServicesCreateServiceRequest) GetAutoPauseTransientAlertsConfig() *V3ServicesAPTAConfig {
	if v == nil {
		return nil
	}
	return v.AutoPauseTransientAlertsConfig
}

func (v *V3ServicesCreateServiceRequest) GetIntelligentAlertsGroupingConfig() *V3ServicesIAGConfig {
	if v == nil {
		return nil
	}
	return v.IntelligentAlertsGroupingConfig
}

func (v *V3ServicesCreateServiceRequest) GetDelayNotificationConfig() *V3ServicesNotificationDelayConfigRequest {
	if v == nil {
		return nil
	}
	return v.DelayNotificationConfig
}

func (v *V3ServicesCreateServiceRequest) GetDedupInitConfig() *V3ServicesDedupInitConfig {
	if v == nil {
		return nil
	}
	return v.DedupInitConfig
}
