// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ServicesJiraProject struct {
	ID   string `json:"id"`
	Key  string `json:"key"`
	Name string `json:"name"`
}

func (v *V3ServicesJiraProject) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3ServicesJiraProject) GetKey() string {
	if v == nil {
		return ""
	}
	return v.Key
}

func (v *V3ServicesJiraProject) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}
