// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ServicesIAGConfigRequest struct {
	IsEnabled           bool  `json:"is_enabled"`
	RollingWindowInMins int64 `json:"rolling_window_in_mins"`
}

func (v *V3ServicesIAGConfigRequest) GetIsEnabled() bool {
	if v == nil {
		return false
	}
	return v.IsEnabled
}

func (v *V3ServicesIAGConfigRequest) GetRollingWindowInMins() int64 {
	if v == nil {
		return 0
	}
	return v.RollingWindowInMins
}
