// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V3ServicesSuppressionRulesSuppressionRule struct {
	RuleID          string                                      `json:"rule_id"`
	CreatedAt       time.Time                                   `json:"created_at"`
	UpdatedAt       time.Time                                   `json:"updated_at"`
	CreatedBy       string                                      `json:"created_by"`
	UpdatedBy       string                                      `json:"updated_by"`
	Description     string                                      `json:"description"`
	Expression      string                                      `json:"expression"`
	IsBasic         bool                                        `json:"is_basic"`
	IsTimebased     bool                                        `json:"is_timebased"`
	Timeslots       []V3ServicesSuppressionRulesTimeslot        `json:"timeslots"`
	BasicExpression []V3ServicesSuppressionRulesBasicExpression `json:"basic_expression"`
}

func (v V3ServicesSuppressionRulesSuppressionRule) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3ServicesSuppressionRulesSuppressionRule) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"rule_id", "created_at", "updated_at", "created_by", "updated_by", "description", "expression", "is_basic", "is_timebased", "basic_expression"}); err != nil {
		return err
	}
	return nil
}

func (v *V3ServicesSuppressionRulesSuppressionRule) GetRuleID() string {
	if v == nil {
		return ""
	}
	return v.RuleID
}

func (v *V3ServicesSuppressionRulesSuppressionRule) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *V3ServicesSuppressionRulesSuppressionRule) GetUpdatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.UpdatedAt
}

func (v *V3ServicesSuppressionRulesSuppressionRule) GetCreatedBy() string {
	if v == nil {
		return ""
	}
	return v.CreatedBy
}

func (v *V3ServicesSuppressionRulesSuppressionRule) GetUpdatedBy() string {
	if v == nil {
		return ""
	}
	return v.UpdatedBy
}

func (v *V3ServicesSuppressionRulesSuppressionRule) GetDescription() string {
	if v == nil {
		return ""
	}
	return v.Description
}

func (v *V3ServicesSuppressionRulesSuppressionRule) GetExpression() string {
	if v == nil {
		return ""
	}
	return v.Expression
}

func (v *V3ServicesSuppressionRulesSuppressionRule) GetIsBasic() bool {
	if v == nil {
		return false
	}
	return v.IsBasic
}

func (v *V3ServicesSuppressionRulesSuppressionRule) GetIsTimebased() bool {
	if v == nil {
		return false
	}
	return v.IsTimebased
}

func (v *V3ServicesSuppressionRulesSuppressionRule) GetTimeslots() []V3ServicesSuppressionRulesTimeslot {
	if v == nil {
		return nil
	}
	return v.Timeslots
}

func (v *V3ServicesSuppressionRulesSuppressionRule) GetBasicExpression() []V3ServicesSuppressionRulesBasicExpression {
	if v == nil {
		return []V3ServicesSuppressionRulesBasicExpression{}
	}
	return v.BasicExpression
}
