// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ServicesMaintenanceModeCreateOrUpdateMaintenanceModeRequest struct {
	OnMaintenance      bool                                          `json:"onMaintenance"`
	ServiceMaintenance []V3ServicesMaintenanceModeServiceMaintenance `json:"serviceMaintenance"`
}

func (v *V3ServicesMaintenanceModeCreateOrUpdateMaintenanceModeRequest) GetOnMaintenance() bool {
	if v == nil {
		return false
	}
	return v.OnMaintenance
}

func (v *V3ServicesMaintenanceModeCreateOrUpdateMaintenanceModeRequest) GetServiceMaintenance() []V3ServicesMaintenanceModeServiceMaintenance {
	if v == nil {
		return []V3ServicesMaintenanceModeServiceMaintenance{}
	}
	return v.ServiceMaintenance
}
