// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/solarwinds/squadcast-sdk-go/internal/utils"
	"time"
)

type V3ServicesOverlayOverlayResponse struct {
	CreatedAt            time.Time                        `json:"created_at"`
	UpdatedAt            time.Time                        `json:"updated_at"`
	DeletedAt            *time.Time                       `json:"deleted_at"`
	OrgID                string                           `json:"org_id"`
	ServiceID            string                           `json:"service_id"`
	AlertSourceVersion   string                           `json:"alert_source_version"`
	AlertSourceShortname string                           `json:"alert_source_shortname"`
	OverlayTemplateType  string                           `json:"overlay_template_type"`
	Overlay              V3ServicesOverlayDedupKeyOverlay `json:"overlay"`
	CreatedBy            string                           `json:"created_by"`
	UpdatedBy            string                           `json:"updated_by"`
	AlertSourceType      string                           `json:"alert_source_type"`
}

func (v V3ServicesOverlayOverlayResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3ServicesOverlayOverlayResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"created_at", "updated_at", "org_id", "service_id", "alert_source_version", "alert_source_shortname", "overlay_template_type", "overlay", "created_by", "updated_by", "alert_source_type"}); err != nil {
		return err
	}
	return nil
}

func (v *V3ServicesOverlayOverlayResponse) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *V3ServicesOverlayOverlayResponse) GetUpdatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.UpdatedAt
}

func (v *V3ServicesOverlayOverlayResponse) GetDeletedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.DeletedAt
}

func (v *V3ServicesOverlayOverlayResponse) GetOrgID() string {
	if v == nil {
		return ""
	}
	return v.OrgID
}

func (v *V3ServicesOverlayOverlayResponse) GetServiceID() string {
	if v == nil {
		return ""
	}
	return v.ServiceID
}

func (v *V3ServicesOverlayOverlayResponse) GetAlertSourceVersion() string {
	if v == nil {
		return ""
	}
	return v.AlertSourceVersion
}

func (v *V3ServicesOverlayOverlayResponse) GetAlertSourceShortname() string {
	if v == nil {
		return ""
	}
	return v.AlertSourceShortname
}

func (v *V3ServicesOverlayOverlayResponse) GetOverlayTemplateType() string {
	if v == nil {
		return ""
	}
	return v.OverlayTemplateType
}

func (v *V3ServicesOverlayOverlayResponse) GetOverlay() V3ServicesOverlayDedupKeyOverlay {
	if v == nil {
		return V3ServicesOverlayDedupKeyOverlay{}
	}
	return v.Overlay
}

func (v *V3ServicesOverlayOverlayResponse) GetCreatedBy() string {
	if v == nil {
		return ""
	}
	return v.CreatedBy
}

func (v *V3ServicesOverlayOverlayResponse) GetUpdatedBy() string {
	if v == nil {
		return ""
	}
	return v.UpdatedBy
}

func (v *V3ServicesOverlayOverlayResponse) GetAlertSourceType() string {
	if v == nil {
		return ""
	}
	return v.AlertSourceType
}

// #region class-body-v3servicesoverlayoverlayresponse
// #endregion class-body-v3servicesoverlayoverlayresponse
