// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type V3SLOSLOActionType string

const (
	V3SLOSLOActionTypeService V3SLOSLOActionType = "SERVICE"
	V3SLOSLOActionTypeUser    V3SLOSLOActionType = "USER"
	V3SLOSLOActionTypeSquad   V3SLOSLOActionType = "SQUAD"
)

func (e V3SLOSLOActionType) ToPointer() *V3SLOSLOActionType {
	return &e
}
func (e *V3SLOSLOActionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SERVICE":
		fallthrough
	case "USER":
		fallthrough
	case "SQUAD":
		*e = V3SLOSLOActionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3SLOSLOActionType: %v", v)
	}
}
