// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V3SLOSLOTags struct {
}

type V3SloSlo struct {
	ID                   int64                     `json:"id"`
	Name                 string                    `json:"name"`
	Description          *string                   `json:"description,omitempty"`
	TimeIntervalType     V3SLOTimeIntervalType     `json:"time_interval_type"`
	ServiceIds           []string                  `json:"service_ids"`
	Slis                 []string                  `json:"slis"`
	TargetSlo            float32                   `json:"target_slo"`
	CurrentSlo           *float32                  `json:"current_slo,omitempty"`
	StartTime            time.Time                 `json:"start_time"`
	EndTime              time.Time                 `json:"end_time"`
	IsHealthy            *bool                     `json:"is_healthy,omitempty"`
	RemainingErrorBudget *float32                  `json:"remaining_error_budget,omitempty"`
	AllocatedErrorBudget float32                   `json:"allocated_error_budget"`
	IsActive             bool                      `json:"is_active"`
	Tags                 *V3SLOSLOTags             `json:"tags,omitempty"`
	IncidentCount        *int64                    `json:"incident_count,omitempty"`
	FalsePositiveCount   *int64                    `json:"false_positive_count,omitempty"`
	SloMonitoringChecks  []V3SLOSLOMonitoringCheck `json:"slo_monitoring_checks,omitempty"`
	SloActions           []V3SLOSLOAction          `json:"slo_actions,omitempty"`
	OwnerType            string                    `json:"owner_type"`
	OwnerID              string                    `json:"owner_id"`
	OrgID                string                    `json:"org_id"`
	SloOwnerID           *string                   `json:"slo_owner_id,omitempty"`
	SloOwnerType         *V3SLOSLOOwnerType        `json:"slo_owner_type,omitempty"`
	CreatedAt            *time.Time                `json:"created_at,omitempty"`
	UpdatedAt            *time.Time                `json:"updated_at,omitempty"`
	DeletedAt            *time.Time                `json:"deleted_at,omitempty"`
	DurationInDays       *int64                    `json:"duration_in_days,omitempty"`
}

func (v V3SloSlo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3SloSlo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"id", "name", "time_interval_type", "service_ids", "slis", "target_slo", "start_time", "end_time", "allocated_error_budget", "is_active", "owner_type", "owner_id", "org_id"}); err != nil {
		return err
	}
	return nil
}

func (v *V3SloSlo) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V3SloSlo) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3SloSlo) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V3SloSlo) GetTimeIntervalType() V3SLOTimeIntervalType {
	if v == nil {
		return V3SLOTimeIntervalType("")
	}
	return v.TimeIntervalType
}

func (v *V3SloSlo) GetServiceIds() []string {
	if v == nil {
		return []string{}
	}
	return v.ServiceIds
}

func (v *V3SloSlo) GetSlis() []string {
	if v == nil {
		return []string{}
	}
	return v.Slis
}

func (v *V3SloSlo) GetTargetSlo() float32 {
	if v == nil {
		return 0.0
	}
	return v.TargetSlo
}

func (v *V3SloSlo) GetCurrentSlo() *float32 {
	if v == nil {
		return nil
	}
	return v.CurrentSlo
}

func (v *V3SloSlo) GetStartTime() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.StartTime
}

func (v *V3SloSlo) GetEndTime() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.EndTime
}

func (v *V3SloSlo) GetIsHealthy() *bool {
	if v == nil {
		return nil
	}
	return v.IsHealthy
}

func (v *V3SloSlo) GetRemainingErrorBudget() *float32 {
	if v == nil {
		return nil
	}
	return v.RemainingErrorBudget
}

func (v *V3SloSlo) GetAllocatedErrorBudget() float32 {
	if v == nil {
		return 0.0
	}
	return v.AllocatedErrorBudget
}

func (v *V3SloSlo) GetIsActive() bool {
	if v == nil {
		return false
	}
	return v.IsActive
}

func (v *V3SloSlo) GetTags() *V3SLOSLOTags {
	if v == nil {
		return nil
	}
	return v.Tags
}

func (v *V3SloSlo) GetIncidentCount() *int64 {
	if v == nil {
		return nil
	}
	return v.IncidentCount
}

func (v *V3SloSlo) GetFalsePositiveCount() *int64 {
	if v == nil {
		return nil
	}
	return v.FalsePositiveCount
}

func (v *V3SloSlo) GetSloMonitoringChecks() []V3SLOSLOMonitoringCheck {
	if v == nil {
		return nil
	}
	return v.SloMonitoringChecks
}

func (v *V3SloSlo) GetSloActions() []V3SLOSLOAction {
	if v == nil {
		return nil
	}
	return v.SloActions
}

func (v *V3SloSlo) GetOwnerType() string {
	if v == nil {
		return ""
	}
	return v.OwnerType
}

func (v *V3SloSlo) GetOwnerID() string {
	if v == nil {
		return ""
	}
	return v.OwnerID
}

func (v *V3SloSlo) GetOrgID() string {
	if v == nil {
		return ""
	}
	return v.OrgID
}

func (v *V3SloSlo) GetSloOwnerID() *string {
	if v == nil {
		return nil
	}
	return v.SloOwnerID
}

func (v *V3SloSlo) GetSloOwnerType() *V3SLOSLOOwnerType {
	if v == nil {
		return nil
	}
	return v.SloOwnerType
}

func (v *V3SloSlo) GetCreatedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.CreatedAt
}

func (v *V3SloSlo) GetUpdatedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.UpdatedAt
}

func (v *V3SloSlo) GetDeletedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.DeletedAt
}

func (v *V3SloSlo) GetDurationInDays() *int64 {
	if v == nil {
		return nil
	}
	return v.DurationInDays
}
