// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3SLOMarkSLOAffectedRequest struct {
	IncidentID       string   `json:"incident_id"`
	Slis             []string `json:"slis"`
	ErrorBudgetSpent float32  `json:"error_budget_spent"`
	OwnerType        string   `json:"owner_type"`
	OwnerID          string   `json:"owner_id"`
	OrgID            string   `json:"org_id"`
}

func (v *V3SLOMarkSLOAffectedRequest) GetIncidentID() string {
	if v == nil {
		return ""
	}
	return v.IncidentID
}

func (v *V3SLOMarkSLOAffectedRequest) GetSlis() []string {
	if v == nil {
		return []string{}
	}
	return v.Slis
}

func (v *V3SLOMarkSLOAffectedRequest) GetErrorBudgetSpent() float32 {
	if v == nil {
		return 0.0
	}
	return v.ErrorBudgetSpent
}

func (v *V3SLOMarkSLOAffectedRequest) GetOwnerType() string {
	if v == nil {
		return ""
	}
	return v.OwnerType
}

func (v *V3SLOMarkSLOAffectedRequest) GetOwnerID() string {
	if v == nil {
		return ""
	}
	return v.OwnerID
}

func (v *V3SLOMarkSLOAffectedRequest) GetOrgID() string {
	if v == nil {
		return ""
	}
	return v.OrgID
}
