// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Insights struct {
	ErrorBudgetConsumptionForPast30days int64 `json:"error_budget_consumption_for_past_30days"`
}

func (i *Insights) GetErrorBudgetConsumptionForPast30days() int64 {
	if i == nil {
		return 0
	}
	return i.ErrorBudgetConsumptionForPast30days
}

type V3SLOSLOWithInsightsResponse struct {
	Insights *Insights `json:"insights,omitempty"`
	Slo      V3SloSlo  `json:"slo"`
}

func (v *V3SLOSLOWithInsightsResponse) GetInsights() *Insights {
	if v == nil {
		return nil
	}
	return v.Insights
}

func (v *V3SLOSLOWithInsightsResponse) GetSlo() V3SloSlo {
	if v == nil {
		return V3SloSlo{}
	}
	return v.Slo
}
