// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3TeamsUpdateTeamRequestMember struct {
	UserID string `json:"user_id"`
	// this field is required if you are using OBAC permission model
	Role *string `json:"role,omitempty"`
	// this field is required if you are using RBAC permission model
	RoleIds []string `json:"role_ids"`
}

func (v *V3TeamsUpdateTeamRequestMember) GetUserID() string {
	if v == nil {
		return ""
	}
	return v.UserID
}

func (v *V3TeamsUpdateTeamRequestMember) GetRole() *string {
	if v == nil {
		return nil
	}
	return v.Role
}

func (v *V3TeamsUpdateTeamRequestMember) GetRoleIds() []string {
	if v == nil {
		return []string{}
	}
	return v.RoleIds
}

type V3TeamsUpdateTeamRequest struct {
	Name        *string                          `json:"name,omitempty"`
	Description *string                          `json:"description,omitempty"`
	Members     []V3TeamsUpdateTeamRequestMember `json:"members"`
}

func (v *V3TeamsUpdateTeamRequest) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V3TeamsUpdateTeamRequest) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V3TeamsUpdateTeamRequest) GetMembers() []V3TeamsUpdateTeamRequestMember {
	if v == nil {
		return []V3TeamsUpdateTeamRequestMember{}
	}
	return v.Members
}
