// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3TeamsAddBulkTeamMemberRequestMember struct {
	UserID string `json:"user_id"`
	// this field is required if you are using OBAC permission model
	Role *string `json:"role,omitempty"`
	// this field is required if you are using RBAC permission model
	RoleIds []string `json:"role_ids"`
}

func (v *V3TeamsAddBulkTeamMemberRequestMember) GetUserID() string {
	if v == nil {
		return ""
	}
	return v.UserID
}

func (v *V3TeamsAddBulkTeamMemberRequestMember) GetRole() *string {
	if v == nil {
		return nil
	}
	return v.Role
}

func (v *V3TeamsAddBulkTeamMemberRequestMember) GetRoleIds() []string {
	if v == nil {
		return []string{}
	}
	return v.RoleIds
}

type V3TeamsAddBulkTeamMemberRequest struct {
	Members []V3TeamsAddBulkTeamMemberRequestMember `json:"members"`
}

func (v *V3TeamsAddBulkTeamMemberRequest) GetMembers() []V3TeamsAddBulkTeamMemberRequestMember {
	if v == nil {
		return []V3TeamsAddBulkTeamMemberRequestMember{}
	}
	return v.Members
}
