// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3TeamsTeamMember struct {
	UserID    string            `json:"user_id"`
	Role      *string           `json:"role,omitempty"`
	RoleIds   []string          `json:"role_ids,omitempty"`
	Abilities *V3TeamsAbilities `json:"abilities,omitempty"`
}

func (v *V3TeamsTeamMember) GetUserID() string {
	if v == nil {
		return ""
	}
	return v.UserID
}

func (v *V3TeamsTeamMember) GetRole() *string {
	if v == nil {
		return nil
	}
	return v.Role
}

func (v *V3TeamsTeamMember) GetRoleIds() []string {
	if v == nil {
		return nil
	}
	return v.RoleIds
}

func (v *V3TeamsTeamMember) GetAbilities() *V3TeamsAbilities {
	if v == nil {
		return nil
	}
	return v.Abilities
}
