// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// V3UsersGlobalRBACAbilityName - Represents the name of a global RBAC ability.
type V3UsersGlobalRBACAbilityName string

const (
	V3UsersGlobalRBACAbilityNameManageAPITokens             V3UsersGlobalRBACAbilityName = "manage-api-tokens"
	V3UsersGlobalRBACAbilityNameManageBilling               V3UsersGlobalRBACAbilityName = "manage-billing"
	V3UsersGlobalRBACAbilityNameManageExtensions            V3UsersGlobalRBACAbilityName = "manage-extensions"
	V3UsersGlobalRBACAbilityNameManageTeams                 V3UsersGlobalRBACAbilityName = "manage-teams"
	V3UsersGlobalRBACAbilityNameManageUsers                 V3UsersGlobalRBACAbilityName = "manage-users"
	V3UsersGlobalRBACAbilityNameManageWebhooks              V3UsersGlobalRBACAbilityName = "manage-webhooks"
	V3UsersGlobalRBACAbilityNameManageOrganizationAnalytics V3UsersGlobalRBACAbilityName = "manage-organization-analytics"
	V3UsersGlobalRBACAbilityNameManagePostmortemTemplates   V3UsersGlobalRBACAbilityName = "manage-postmortem-templates"
	V3UsersGlobalRBACAbilityNameManageAuditLogs             V3UsersGlobalRBACAbilityName = "manage-audit-logs"
	V3UsersGlobalRBACAbilityNameManageFeatureSettings       V3UsersGlobalRBACAbilityName = "manage-feature-settings"
)

func (e V3UsersGlobalRBACAbilityName) ToPointer() *V3UsersGlobalRBACAbilityName {
	return &e
}
func (e *V3UsersGlobalRBACAbilityName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "manage-api-tokens":
		fallthrough
	case "manage-billing":
		fallthrough
	case "manage-extensions":
		fallthrough
	case "manage-teams":
		fallthrough
	case "manage-users":
		fallthrough
	case "manage-webhooks":
		fallthrough
	case "manage-organization-analytics":
		fallthrough
	case "manage-postmortem-templates":
		fallthrough
	case "manage-audit-logs":
		fallthrough
	case "manage-feature-settings":
		*e = V3UsersGlobalRBACAbilityName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3UsersGlobalRBACAbilityName: %v", v)
	}
}
