// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3UsersUpdateUserAbilitiesRequestData struct {
	UserID    string                         `json:"user_id"`
	Abilities []V3UsersGlobalRBACAbilityName `json:"abilities"`
}

func (v *V3UsersUpdateUserAbilitiesRequestData) GetUserID() string {
	if v == nil {
		return ""
	}
	return v.UserID
}

func (v *V3UsersUpdateUserAbilitiesRequestData) GetAbilities() []V3UsersGlobalRBACAbilityName {
	if v == nil {
		return []V3UsersGlobalRBACAbilityName{}
	}
	return v.Abilities
}

type V3UsersUpdateUserAbilitiesRequest struct {
	Data []V3UsersUpdateUserAbilitiesRequestData `json:"data"`
}

func (v *V3UsersUpdateUserAbilitiesRequest) GetData() []V3UsersUpdateUserAbilitiesRequestData {
	if v == nil {
		return []V3UsersUpdateUserAbilitiesRequestData{}
	}
	return v.Data
}
