// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3UsersUserRoleResponse struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Limit int64  `json:"limit"`
	Order int64  `json:"order"`
}

func (v *V3UsersUserRoleResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3UsersUserRoleResponse) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3UsersUserRoleResponse) GetLimit() int64 {
	if v == nil {
		return 0
	}
	return v.Limit
}

func (v *V3UsersUserRoleResponse) GetOrder() int64 {
	if v == nil {
		return 0
	}
	return v.Order
}
