// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3UsersContact struct {
	DialCode    string `json:"dial_code"`
	PhoneNumber string `json:"phone_number"`
}

func (v *V3UsersContact) GetDialCode() string {
	if v == nil {
		return ""
	}
	return v.DialCode
}

func (v *V3UsersContact) GetPhoneNumber() string {
	if v == nil {
		return ""
	}
	return v.PhoneNumber
}
