// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3UsersNotificationRule struct {
	Type string `json:"type"`
	Time int64  `json:"time"`
}

func (v *V3UsersNotificationRule) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *V3UsersNotificationRule) GetTime() int64 {
	if v == nil {
		return 0
	}
	return v.Time
}
