// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3UsersAPITokenResponse struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
	Token          string `json:"token"`
	LastRefresh    string `json:"last_refresh"`
	RateLimit      int64  `json:"rate_limit"`
	Deleted        bool   `json:"deleted"`
}

func (v *V3UsersAPITokenResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3UsersAPITokenResponse) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V3UsersAPITokenResponse) GetUserID() string {
	if v == nil {
		return ""
	}
	return v.UserID
}

func (v *V3UsersAPITokenResponse) GetToken() string {
	if v == nil {
		return ""
	}
	return v.Token
}

func (v *V3UsersAPITokenResponse) GetLastRefresh() string {
	if v == nil {
		return ""
	}
	return v.LastRefresh
}

func (v *V3UsersAPITokenResponse) GetRateLimit() int64 {
	if v == nil {
		return 0
	}
	return v.RateLimit
}

func (v *V3UsersAPITokenResponse) GetDeleted() bool {
	if v == nil {
		return false
	}
	return v.Deleted
}
