// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bf36b2df8843

package components

// V3WebformsRecaptchaSecrets - reCAPTCHA credentials to be validated
type V3WebformsRecaptchaSecrets struct {
	// reCAPTCHA site key
	SiteKey string `json:"site_key"`
	// reCAPTCHA secret key
	Secret string `json:"secret"`
}

func (v *V3WebformsRecaptchaSecrets) GetSiteKey() string {
	if v == nil {
		return ""
	}
	return v.SiteKey
}

func (v *V3WebformsRecaptchaSecrets) GetSecret() string {
	if v == nil {
		return ""
	}
	return v.Secret
}
