// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3WebformsCreateOrUpdateWebformRequestTags - Key-value tags for the webform
type V3WebformsCreateOrUpdateWebformRequestTags struct {
}

// V3WebformsCreateOrUpdateWebformRequest - Public API request for creating a webform
type V3WebformsCreateOrUpdateWebformRequest struct {
	// Unique identifier of the owner (string or UUID)
	OwnerID string `json:"owner_id"`
	// Name of the webform
	Name string `json:"name"`
	// Indicates if a custom domain (CNAME) is used
	IsCname bool `json:"is_cname"`
	// Custom hostname if CNAME is enabled
	HostName *string `json:"host_name,omitempty"`
	// Key-value tags for the webform
	Tags *V3WebformsCreateOrUpdateWebformRequestTags `json:"tags,omitempty"`
	// Whether CAPTCHA is enabled on the form
	IsCaptchaEnabled bool `json:"is_captcha_enabled"`
	// CAPTCHA credentials to be validated
	CaptchaSecret V3WebformsRecaptchaSecrets `json:"captcha_secret"`
	// Entity type that owns the form (e.g., team, user)
	FormOwnerType string `json:"form_owner_type"`
	// Identifier for the owner entity
	FormOwnerID string `json:"form_owner_id"`
	// List of services tied to this webform
	Services []V3WebformsWFService `json:"services"`
	// Input fields to be rendered on the form
	InputField []V3WebformsWFInputField `json:"input_field,omitempty"`
	// Header text shown on the form
	Header string `json:"header"`
	// Title of the webform
	Title string `json:"title"`
	// URL to the organization's logo
	LogoURL *string `json:"logo_url,omitempty"`
	// Text displayed in the footer
	FooterText string `json:"footer_text"`
	// Hyperlink in the footer (mailto or https)
	FooterLink string `json:"footer_link"`
	// Emails to notify on submission
	EmailOn []string `json:"email_on,omitempty"`
	// Optional description for the webform
	Description *string `json:"description,omitempty"`
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetOwnerID() string {
	if v == nil {
		return ""
	}
	return v.OwnerID
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetIsCname() bool {
	if v == nil {
		return false
	}
	return v.IsCname
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetHostName() *string {
	if v == nil {
		return nil
	}
	return v.HostName
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetTags() *V3WebformsCreateOrUpdateWebformRequestTags {
	if v == nil {
		return nil
	}
	return v.Tags
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetIsCaptchaEnabled() bool {
	if v == nil {
		return false
	}
	return v.IsCaptchaEnabled
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetCaptchaSecret() V3WebformsRecaptchaSecrets {
	if v == nil {
		return V3WebformsRecaptchaSecrets{}
	}
	return v.CaptchaSecret
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetFormOwnerType() string {
	if v == nil {
		return ""
	}
	return v.FormOwnerType
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetFormOwnerID() string {
	if v == nil {
		return ""
	}
	return v.FormOwnerID
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetServices() []V3WebformsWFService {
	if v == nil {
		return []V3WebformsWFService{}
	}
	return v.Services
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetInputField() []V3WebformsWFInputField {
	if v == nil {
		return nil
	}
	return v.InputField
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetHeader() string {
	if v == nil {
		return ""
	}
	return v.Header
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetTitle() string {
	if v == nil {
		return ""
	}
	return v.Title
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetLogoURL() *string {
	if v == nil {
		return nil
	}
	return v.LogoURL
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetFooterText() string {
	if v == nil {
		return ""
	}
	return v.FooterText
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetFooterLink() string {
	if v == nil {
		return ""
	}
	return v.FooterLink
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetEmailOn() []string {
	if v == nil {
		return nil
	}
	return v.EmailOn
}

func (v *V3WebformsCreateOrUpdateWebformRequest) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}
