// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3WebformsWFInputField - Input field definition for a webform
type V3WebformsWFInputField struct {
	// Field label
	Label string `json:"label"`
	// Selectable options for this field
	Options []string `json:"options"`
}

func (v *V3WebformsWFInputField) GetLabel() string {
	if v == nil {
		return ""
	}
	return v.Label
}

func (v *V3WebformsWFInputField) GetOptions() []string {
	if v == nil {
		return []string{}
	}
	return v.Options
}
