// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3WorkflowsUpdateActionsOrderResponseData struct {
	ActionOrder []int `json:"action_order"`
}

func (v *V3WorkflowsUpdateActionsOrderResponseData) GetActionOrder() []int {
	if v == nil {
		return []int{}
	}
	return v.ActionOrder
}

type V3WorkflowsUpdateActionsOrderResponse struct {
	Data V3WorkflowsUpdateActionsOrderResponseData `json:"data"`
}

func (v *V3WorkflowsUpdateActionsOrderResponse) GetData() V3WorkflowsUpdateActionsOrderResponseData {
	if v == nil {
		return V3WorkflowsUpdateActionsOrderResponseData{}
	}
	return v.Data
}
