// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
)

type V3WorkflowsMsTeamsMessageUserUpdateName string

const (
	V3WorkflowsMsTeamsMessageUserUpdateNameMsteamsMessageUser V3WorkflowsMsTeamsMessageUserUpdateName = "msteams_message_user"
)

func (e V3WorkflowsMsTeamsMessageUserUpdateName) ToPointer() *V3WorkflowsMsTeamsMessageUserUpdateName {
	return &e
}
func (e *V3WorkflowsMsTeamsMessageUserUpdateName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "msteams_message_user":
		*e = V3WorkflowsMsTeamsMessageUserUpdateName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3WorkflowsMsTeamsMessageUserUpdateName: %v", v)
	}
}

type V3WorkflowsMsTeamsMessageUserUpdateData struct {
	MemberID *string `json:"member_id,omitempty"`
	Message  *string `json:"message,omitempty"`
}

func (v V3WorkflowsMsTeamsMessageUserUpdateData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WorkflowsMsTeamsMessageUserUpdateData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V3WorkflowsMsTeamsMessageUserUpdateData) GetMemberID() *string {
	if v == nil {
		return nil
	}
	return v.MemberID
}

func (v *V3WorkflowsMsTeamsMessageUserUpdateData) GetMessage() *string {
	if v == nil {
		return nil
	}
	return v.Message
}

type V3WorkflowsMsTeamsMessageUserUpdate struct {
	Name V3WorkflowsMsTeamsMessageUserUpdateName  `json:"name"`
	Data *V3WorkflowsMsTeamsMessageUserUpdateData `json:"data,omitempty"`
}

func (v V3WorkflowsMsTeamsMessageUserUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WorkflowsMsTeamsMessageUserUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"name"}); err != nil {
		return err
	}
	return nil
}

func (v *V3WorkflowsMsTeamsMessageUserUpdate) GetName() V3WorkflowsMsTeamsMessageUserUpdateName {
	if v == nil {
		return V3WorkflowsMsTeamsMessageUserUpdateName("")
	}
	return v.Name
}

func (v *V3WorkflowsMsTeamsMessageUserUpdate) GetData() *V3WorkflowsMsTeamsMessageUserUpdateData {
	if v == nil {
		return nil
	}
	return v.Data
}
