// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3fa24292afd9

package components

type V3WorkflowsGetWorkflowByIDResponse struct {
	Data V3WorkflowsWorkflowAPIResponse `json:"data"`
}

func (v *V3WorkflowsGetWorkflowByIDResponse) GetData() V3WorkflowsWorkflowAPIResponse {
	if v == nil {
		return V3WorkflowsWorkflowAPIResponse{}
	}
	return v.Data
}
