// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c3588eeaa0de

package components

type V3WorkflowsEntityOwner struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

func (v *V3WorkflowsEntityOwner) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3WorkflowsEntityOwner) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}
