// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
)

type V3WorkflowsSlackMessageUserName string

const (
	V3WorkflowsSlackMessageUserNameSlackMessageUser V3WorkflowsSlackMessageUserName = "slack_message_user"
)

func (e V3WorkflowsSlackMessageUserName) ToPointer() *V3WorkflowsSlackMessageUserName {
	return &e
}
func (e *V3WorkflowsSlackMessageUserName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "slack_message_user":
		*e = V3WorkflowsSlackMessageUserName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3WorkflowsSlackMessageUserName: %v", v)
	}
}

type V3WorkflowsSlackMessageUserData struct {
	MemberID string `json:"member_id"`
	Message  string `json:"message"`
}

func (v V3WorkflowsSlackMessageUserData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WorkflowsSlackMessageUserData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"member_id", "message"}); err != nil {
		return err
	}
	return nil
}

func (v *V3WorkflowsSlackMessageUserData) GetMemberID() string {
	if v == nil {
		return ""
	}
	return v.MemberID
}

func (v *V3WorkflowsSlackMessageUserData) GetMessage() string {
	if v == nil {
		return ""
	}
	return v.Message
}

type V3WorkflowsSlackMessageUser struct {
	Name V3WorkflowsSlackMessageUserName `json:"name"`
	Data V3WorkflowsSlackMessageUserData `json:"data"`
}

func (v V3WorkflowsSlackMessageUser) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WorkflowsSlackMessageUser) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"name", "data"}); err != nil {
		return err
	}
	return nil
}

func (v *V3WorkflowsSlackMessageUser) GetName() V3WorkflowsSlackMessageUserName {
	if v == nil {
		return V3WorkflowsSlackMessageUserName("")
	}
	return v.Name
}

func (v *V3WorkflowsSlackMessageUser) GetData() V3WorkflowsSlackMessageUserData {
	if v == nil {
		return V3WorkflowsSlackMessageUserData{}
	}
	return v.Data
}
