// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3WorkflowsUpdateWorkflowAPIResponse struct {
	ID          *int                        `json:"id,omitempty"`
	OwnerID     *string                     `json:"owner_id,omitempty"`
	Title       *string                     `json:"title,omitempty"`
	Description *string                     `json:"description,omitempty"`
	Enabled     *bool                       `json:"enabled,omitempty"`
	Trigger     *string                     `json:"trigger,omitempty"`
	Filters     *V3WorkflowsWorkflowFilters `json:"filters,omitempty"`
	Tags        []V3WorkflowsTag            `json:"tags,omitempty"`
	Actions     []V3WorkflowsActionResponse `json:"actions,omitempty"`
	CreatedAt   *string                     `json:"created_at,omitempty"`
	CreatedBy   *string                     `json:"created_by,omitempty"`
	UpdatedAt   *string                     `json:"updated_at,omitempty"`
	UpdatedBy   *string                     `json:"updated_by,omitempty"`
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetID() *int {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetOwnerID() *string {
	if v == nil {
		return nil
	}
	return v.OwnerID
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetTitle() *string {
	if v == nil {
		return nil
	}
	return v.Title
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetEnabled() *bool {
	if v == nil {
		return nil
	}
	return v.Enabled
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetTrigger() *string {
	if v == nil {
		return nil
	}
	return v.Trigger
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetFilters() *V3WorkflowsWorkflowFilters {
	if v == nil {
		return nil
	}
	return v.Filters
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetTags() []V3WorkflowsTag {
	if v == nil {
		return nil
	}
	return v.Tags
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetActions() []V3WorkflowsActionResponse {
	if v == nil {
		return nil
	}
	return v.Actions
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetCreatedAt() *string {
	if v == nil {
		return nil
	}
	return v.CreatedAt
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetCreatedBy() *string {
	if v == nil {
		return nil
	}
	return v.CreatedBy
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetUpdatedAt() *string {
	if v == nil {
		return nil
	}
	return v.UpdatedAt
}

func (v *V3WorkflowsUpdateWorkflowAPIResponse) GetUpdatedBy() *string {
	if v == nil {
		return nil
	}
	return v.UpdatedBy
}
