// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
)

type V3WorkflowsSqAddIncidentNoteUpdateName string

const (
	V3WorkflowsSqAddIncidentNoteUpdateNameSqAddIncidentNote V3WorkflowsSqAddIncidentNoteUpdateName = "sq_add_incident_note"
)

func (e V3WorkflowsSqAddIncidentNoteUpdateName) ToPointer() *V3WorkflowsSqAddIncidentNoteUpdateName {
	return &e
}
func (e *V3WorkflowsSqAddIncidentNoteUpdateName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sq_add_incident_note":
		*e = V3WorkflowsSqAddIncidentNoteUpdateName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3WorkflowsSqAddIncidentNoteUpdateName: %v", v)
	}
}

type V3WorkflowsSqAddIncidentNoteUpdateData struct {
	Note *string `json:"note,omitempty"`
}

func (v V3WorkflowsSqAddIncidentNoteUpdateData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WorkflowsSqAddIncidentNoteUpdateData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V3WorkflowsSqAddIncidentNoteUpdateData) GetNote() *string {
	if v == nil {
		return nil
	}
	return v.Note
}

type V3WorkflowsSqAddIncidentNoteUpdate struct {
	Name V3WorkflowsSqAddIncidentNoteUpdateName  `json:"name"`
	Data *V3WorkflowsSqAddIncidentNoteUpdateData `json:"data,omitempty"`
}

func (v V3WorkflowsSqAddIncidentNoteUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WorkflowsSqAddIncidentNoteUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"name"}); err != nil {
		return err
	}
	return nil
}

func (v *V3WorkflowsSqAddIncidentNoteUpdate) GetName() V3WorkflowsSqAddIncidentNoteUpdateName {
	if v == nil {
		return V3WorkflowsSqAddIncidentNoteUpdateName("")
	}
	return v.Name
}

func (v *V3WorkflowsSqAddIncidentNoteUpdate) GetData() *V3WorkflowsSqAddIncidentNoteUpdateData {
	if v == nil {
		return nil
	}
	return v.Data
}
