// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3WorkflowsGetWorkflowActionByIDResponse struct {
	ID         int    `json:"id"`
	WorkflowID int    `json:"workflow_id"`
	Name       string `json:"name"`
	Data       any    `json:"data"`
}

func (v *V3WorkflowsGetWorkflowActionByIDResponse) GetID() int {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V3WorkflowsGetWorkflowActionByIDResponse) GetWorkflowID() int {
	if v == nil {
		return 0
	}
	return v.WorkflowID
}

func (v *V3WorkflowsGetWorkflowActionByIDResponse) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3WorkflowsGetWorkflowActionByIDResponse) GetData() any {
	if v == nil {
		return nil
	}
	return v.Data
}
