// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3WorkflowsEntityOwnerUpdate struct {
	ID   *string `json:"id,omitempty"`
	Type *string `json:"type,omitempty"`
}

func (v *V3WorkflowsEntityOwnerUpdate) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V3WorkflowsEntityOwnerUpdate) GetType() *string {
	if v == nil {
		return nil
	}
	return v.Type
}
