// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Condition string

const (
	ConditionAnd Condition = "and"
	ConditionOr  Condition = "or"
)

func (e Condition) ToPointer() *Condition {
	return &e
}
func (e *Condition) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "and":
		fallthrough
	case "or":
		*e = Condition(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Condition: %v", v)
	}
}

type V3WorkflowsWorkflowFilters struct {
	Type      *string                      `json:"type,omitempty"`
	Key       *string                      `json:"key,omitempty"`
	Value     *string                      `json:"value,omitempty"`
	Condition *Condition                   `json:"condition,omitempty"`
	Filters   []V3WorkflowsWorkflowFilters `json:"filters,omitempty"`
}

func (v *V3WorkflowsWorkflowFilters) GetType() *string {
	if v == nil {
		return nil
	}
	return v.Type
}

func (v *V3WorkflowsWorkflowFilters) GetKey() *string {
	if v == nil {
		return nil
	}
	return v.Key
}

func (v *V3WorkflowsWorkflowFilters) GetValue() *string {
	if v == nil {
		return nil
	}
	return v.Value
}

func (v *V3WorkflowsWorkflowFilters) GetCondition() *Condition {
	if v == nil {
		return nil
	}
	return v.Condition
}

func (v *V3WorkflowsWorkflowFilters) GetFilters() []V3WorkflowsWorkflowFilters {
	if v == nil {
		return nil
	}
	return v.Filters
}
