// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
)

type V3WorkflowsIssueStatusAndMessage struct {
	Messages []string `json:"messages"`
	StatusID int      `json:"status_id"`
}

func (v V3WorkflowsIssueStatusAndMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WorkflowsIssueStatusAndMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"messages", "status_id"}); err != nil {
		return err
	}
	return nil
}

func (v *V3WorkflowsIssueStatusAndMessage) GetMessages() []string {
	if v == nil {
		return []string{}
	}
	return v.Messages
}

func (v *V3WorkflowsIssueStatusAndMessage) GetStatusID() int {
	if v == nil {
		return 0
	}
	return v.StatusID
}
