// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
)

type V3WorkflowsSlackArchiveChannelUpdateName string

const (
	V3WorkflowsSlackArchiveChannelUpdateNameSlackArchiveChannel V3WorkflowsSlackArchiveChannelUpdateName = "slack_archive_channel"
)

func (e V3WorkflowsSlackArchiveChannelUpdateName) ToPointer() *V3WorkflowsSlackArchiveChannelUpdateName {
	return &e
}
func (e *V3WorkflowsSlackArchiveChannelUpdateName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "slack_archive_channel":
		*e = V3WorkflowsSlackArchiveChannelUpdateName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3WorkflowsSlackArchiveChannelUpdateName: %v", v)
	}
}

type V3WorkflowsSlackArchiveChannelUpdate struct {
	Name V3WorkflowsSlackArchiveChannelUpdateName `json:"name"`
}

func (v V3WorkflowsSlackArchiveChannelUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WorkflowsSlackArchiveChannelUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"name"}); err != nil {
		return err
	}
	return nil
}

func (v *V3WorkflowsSlackArchiveChannelUpdate) GetName() V3WorkflowsSlackArchiveChannelUpdateName {
	if v == nil {
		return V3WorkflowsSlackArchiveChannelUpdateName("")
	}
	return v.Name
}
