// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ad9f101261a0

package components

type V3WorkflowsEnableDisableWorkflowRequest struct {
	Enabled *bool `json:"enabled,omitempty"`
}

func (v *V3WorkflowsEnableDisableWorkflowRequest) GetEnabled() *bool {
	if v == nil {
		return nil
	}
	return v.Enabled
}
