// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d7208a5b5916

package components

type V4ChangeTimezoneResponse struct {
	TimeZone string `json:"timeZone"`
}

func (v *V4ChangeTimezoneResponse) GetTimeZone() string {
	if v == nil {
		return ""
	}
	return v.TimeZone
}
