// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4CreateRotationRequest struct {
	Name                        string               `json:"name"`
	Color                       *string              `json:"color,omitempty"`
	StartDate                   string               `json:"startDate"`
	Period                      string               `json:"period"`
	CustomPeriodFrequency       *int64               `json:"customPeriodFrequency,omitempty"`
	CustomPeriodUnit            *string              `json:"customPeriodUnit,omitempty"`
	ShiftTimeSlots              []V4ShiftTimeSlot    `json:"shiftTimeSlots,omitempty"`
	ChangeParticipantsFrequency int64                `json:"changeParticipantsFrequency"`
	ChangeParticipantsUnit      string               `json:"changeParticipantsUnit"`
	EndDate                     *string              `json:"endDate,omitempty"`
	EndsAfterIterations         *int64               `json:"endsAfterIterations,omitempty"`
	ParticipantGroups           []V4ParticipantGroup `json:"participantGroups"`
}

func (v *V4CreateRotationRequest) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V4CreateRotationRequest) GetColor() *string {
	if v == nil {
		return nil
	}
	return v.Color
}

func (v *V4CreateRotationRequest) GetStartDate() string {
	if v == nil {
		return ""
	}
	return v.StartDate
}

func (v *V4CreateRotationRequest) GetPeriod() string {
	if v == nil {
		return ""
	}
	return v.Period
}

func (v *V4CreateRotationRequest) GetCustomPeriodFrequency() *int64 {
	if v == nil {
		return nil
	}
	return v.CustomPeriodFrequency
}

func (v *V4CreateRotationRequest) GetCustomPeriodUnit() *string {
	if v == nil {
		return nil
	}
	return v.CustomPeriodUnit
}

func (v *V4CreateRotationRequest) GetShiftTimeSlots() []V4ShiftTimeSlot {
	if v == nil {
		return nil
	}
	return v.ShiftTimeSlots
}

func (v *V4CreateRotationRequest) GetChangeParticipantsFrequency() int64 {
	if v == nil {
		return 0
	}
	return v.ChangeParticipantsFrequency
}

func (v *V4CreateRotationRequest) GetChangeParticipantsUnit() string {
	if v == nil {
		return ""
	}
	return v.ChangeParticipantsUnit
}

func (v *V4CreateRotationRequest) GetEndDate() *string {
	if v == nil {
		return nil
	}
	return v.EndDate
}

func (v *V4CreateRotationRequest) GetEndsAfterIterations() *int64 {
	if v == nil {
		return nil
	}
	return v.EndsAfterIterations
}

func (v *V4CreateRotationRequest) GetParticipantGroups() []V4ParticipantGroup {
	if v == nil {
		return []V4ParticipantGroup{}
	}
	return v.ParticipantGroups
}
