// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4GetRotationParticipantsResponse struct {
	RotationID   int64                `json:"rotationID"`
	Participants []V4ParticipantGroup `json:"participants"`
}

func (v *V4GetRotationParticipantsResponse) GetRotationID() int64 {
	if v == nil {
		return 0
	}
	return v.RotationID
}

func (v *V4GetRotationParticipantsResponse) GetParticipants() []V4ParticipantGroup {
	if v == nil {
		return []V4ParticipantGroup{}
	}
	return v.Participants
}
