// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4OverrideParticipantGroup struct {
	Group []V4Participant `json:"group"`
}

func (v *V4OverrideParticipantGroup) GetGroup() []V4Participant {
	if v == nil {
		return []V4Participant{}
	}
	return v.Group
}
