// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4PauseResumeScheduleResponse struct {
	Action  string `json:"action"`
	Success bool   `json:"success"`
}

func (v *V4PauseResumeScheduleResponse) GetAction() string {
	if v == nil {
		return ""
	}
	return v.Action
}

func (v *V4PauseResumeScheduleResponse) GetSuccess() bool {
	if v == nil {
		return false
	}
	return v.Success
}
