// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fadf33752df5

package components

type V4SquadsUpdateSquadNameResponse struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (v *V4SquadsUpdateSquadNameResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V4SquadsUpdateSquadNameResponse) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}
