// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 486cb2bf06dc

package components

type V4SquadsUpdateSquadMemberRequest struct {
	Role string `json:"role"`
}

func (v *V4SquadsUpdateSquadMemberRequest) GetRole() string {
	if v == nil {
		return ""
	}
	return v.Role
}
