// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4SquadsRemoveSquadMemberResponse struct {
	ID      string                `json:"id"`
	Members []V4SquadsSquadMember `json:"members"`
}

func (v *V4SquadsRemoveSquadMemberResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V4SquadsRemoveSquadMemberResponse) GetMembers() []V4SquadsSquadMember {
	if v == nil {
		return []V4SquadsSquadMember{}
	}
	return v.Members
}
