// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4SquadsUpdateSquadRequest struct {
	Name    *string               `json:"name,omitempty"`
	Members []V4SquadsSquadMember `json:"members,omitempty"`
}

func (v *V4SquadsUpdateSquadRequest) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V4SquadsUpdateSquadRequest) GetMembers() []V4SquadsSquadMember {
	if v == nil {
		return nil
	}
	return v.Members
}
