// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4SquadsCreateSquadRequest struct {
	OwnerID string                `json:"owner_id"`
	Name    string                `json:"name"`
	Members []V4SquadsSquadMember `json:"members"`
}

func (v *V4SquadsCreateSquadRequest) GetOwnerID() string {
	if v == nil {
		return ""
	}
	return v.OwnerID
}

func (v *V4SquadsCreateSquadRequest) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V4SquadsCreateSquadRequest) GetMembers() []V4SquadsSquadMember {
	if v == nil {
		return []V4SquadsSquadMember{}
	}
	return v.Members
}
