// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6850ba1b2a7c

package components

type V4SquadsUpdateSquadMemberResponse struct {
	ID      string                `json:"id"`
	Members []V4SquadsSquadMember `json:"members"`
}

func (v *V4SquadsUpdateSquadMemberResponse) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V4SquadsUpdateSquadMemberResponse) GetMembers() []V4SquadsSquadMember {
	if v == nil {
		return []V4SquadsSquadMember{}
	}
	return v.Members
}
