// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesIssuesComponentStatus struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
	Slug  string `json:"slug"`
}

func (v *V4StatusPagesIssuesComponentStatus) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V4StatusPagesIssuesComponentStatus) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V4StatusPagesIssuesComponentStatus) GetColor() string {
	if v == nil {
		return ""
	}
	return v.Color
}

func (v *V4StatusPagesIssuesComponentStatus) GetSlug() string {
	if v == nil {
		return ""
	}
	return v.Slug
}
