// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesMaintenancesListMaintenancesResponseMeta struct {
	TotalCount int64 `json:"totalCount"`
}

func (v *V4StatusPagesMaintenancesListMaintenancesResponseMeta) GetTotalCount() int64 {
	if v == nil {
		return 0
	}
	return v.TotalCount
}

type V4StatusPagesMaintenancesListMaintenancesResponse struct {
	Data []V4StatusPagesMaintenancesMaintenance                `json:"data"`
	Meta V4StatusPagesMaintenancesListMaintenancesResponseMeta `json:"meta"`
}

func (v *V4StatusPagesMaintenancesListMaintenancesResponse) GetData() []V4StatusPagesMaintenancesMaintenance {
	if v == nil {
		return []V4StatusPagesMaintenancesMaintenance{}
	}
	return v.Data
}

func (v *V4StatusPagesMaintenancesListMaintenancesResponse) GetMeta() V4StatusPagesMaintenancesListMaintenancesResponseMeta {
	if v == nil {
		return V4StatusPagesMaintenancesListMaintenancesResponseMeta{}
	}
	return v.Meta
}
