// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V4StatusPagesMaintenancesMaintenanceComponent struct {
	ID        *int64  `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	GroupName *string `json:"groupName,omitempty"`
}

func (v *V4StatusPagesMaintenancesMaintenanceComponent) GetID() *int64 {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V4StatusPagesMaintenancesMaintenanceComponent) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V4StatusPagesMaintenancesMaintenanceComponent) GetGroupName() *string {
	if v == nil {
		return nil
	}
	return v.GroupName
}

type V4StatusPagesMaintenancesMaintenance struct {
	ID               *int64                                          `json:"id,omitempty"`
	Title            *string                                         `json:"title,omitempty"`
	PageID           *int64                                          `json:"pageID,omitempty"`
	Note             *string                                         `json:"note,omitempty"`
	Components       []V4StatusPagesMaintenancesMaintenanceComponent `json:"components,omitempty"`
	StartTime        *time.Time                                      `json:"startTime,omitempty"`
	EndTime          *time.Time                                      `json:"endTime,omitempty"`
	MaintenanceState *string                                         `json:"maintenanceState,omitempty"`
}

func (v V4StatusPagesMaintenancesMaintenance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V4StatusPagesMaintenancesMaintenance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V4StatusPagesMaintenancesMaintenance) GetID() *int64 {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V4StatusPagesMaintenancesMaintenance) GetTitle() *string {
	if v == nil {
		return nil
	}
	return v.Title
}

func (v *V4StatusPagesMaintenancesMaintenance) GetPageID() *int64 {
	if v == nil {
		return nil
	}
	return v.PageID
}

func (v *V4StatusPagesMaintenancesMaintenance) GetNote() *string {
	if v == nil {
		return nil
	}
	return v.Note
}

func (v *V4StatusPagesMaintenancesMaintenance) GetComponents() []V4StatusPagesMaintenancesMaintenanceComponent {
	if v == nil {
		return nil
	}
	return v.Components
}

func (v *V4StatusPagesMaintenancesMaintenance) GetStartTime() *time.Time {
	if v == nil {
		return nil
	}
	return v.StartTime
}

func (v *V4StatusPagesMaintenancesMaintenance) GetEndTime() *time.Time {
	if v == nil {
		return nil
	}
	return v.EndTime
}

func (v *V4StatusPagesMaintenancesMaintenance) GetMaintenanceState() *string {
	if v == nil {
		return nil
	}
	return v.MaintenanceState
}
