// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesListSubscribersResponse struct {
	Data []V4StatusPagesStatusPageSubscriber       `json:"data"`
	Meta *V4StatusPagesListSubscribersResponseMeta `json:"meta,omitempty"`
}

func (v *V4StatusPagesListSubscribersResponse) GetData() []V4StatusPagesStatusPageSubscriber {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *V4StatusPagesListSubscribersResponse) GetMeta() *V4StatusPagesListSubscribersResponseMeta {
	if v == nil {
		return nil
	}
	return v.Meta
}
