// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V4StatusPagesIssuesUpdateIssueRequestComponent struct {
	ID       *int64 `json:"id,omitempty"`
	StatusID *int64 `json:"statusID,omitempty"`
}

func (v *V4StatusPagesIssuesUpdateIssueRequestComponent) GetID() *int64 {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V4StatusPagesIssuesUpdateIssueRequestComponent) GetStatusID() *int64 {
	if v == nil {
		return nil
	}
	return v.StatusID
}

type V4StatusPagesIssuesUpdateIssueRequestStateMessage struct {
	Text      *string    `json:"text,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

func (v V4StatusPagesIssuesUpdateIssueRequestStateMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V4StatusPagesIssuesUpdateIssueRequestStateMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V4StatusPagesIssuesUpdateIssueRequestStateMessage) GetText() *string {
	if v == nil {
		return nil
	}
	return v.Text
}

func (v *V4StatusPagesIssuesUpdateIssueRequestStateMessage) GetTimestamp() *time.Time {
	if v == nil {
		return nil
	}
	return v.Timestamp
}

type V4StatusPagesIssuesUpdateIssueRequestIssue struct {
	StateID       *int64                                              `json:"stateID,omitempty"`
	StateMessages []V4StatusPagesIssuesUpdateIssueRequestStateMessage `json:"stateMessages,omitempty"`
}

func (v *V4StatusPagesIssuesUpdateIssueRequestIssue) GetStateID() *int64 {
	if v == nil {
		return nil
	}
	return v.StateID
}

func (v *V4StatusPagesIssuesUpdateIssueRequestIssue) GetStateMessages() []V4StatusPagesIssuesUpdateIssueRequestStateMessage {
	if v == nil {
		return nil
	}
	return v.StateMessages
}

type V4StatusPagesIssuesUpdateIssueRequest struct {
	Title      string                                           `json:"title"`
	StatusID   *int64                                           `json:"statusID,omitempty"`
	Components []V4StatusPagesIssuesUpdateIssueRequestComponent `json:"components"`
	Issues     []V4StatusPagesIssuesUpdateIssueRequestIssue     `json:"issues"`
}

func (v *V4StatusPagesIssuesUpdateIssueRequest) GetTitle() string {
	if v == nil {
		return ""
	}
	return v.Title
}

func (v *V4StatusPagesIssuesUpdateIssueRequest) GetStatusID() *int64 {
	if v == nil {
		return nil
	}
	return v.StatusID
}

func (v *V4StatusPagesIssuesUpdateIssueRequest) GetComponents() []V4StatusPagesIssuesUpdateIssueRequestComponent {
	if v == nil {
		return []V4StatusPagesIssuesUpdateIssueRequestComponent{}
	}
	return v.Components
}

func (v *V4StatusPagesIssuesUpdateIssueRequest) GetIssues() []V4StatusPagesIssuesUpdateIssueRequestIssue {
	if v == nil {
		return []V4StatusPagesIssuesUpdateIssueRequestIssue{}
	}
	return v.Issues
}
