// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesComponentGroupsComponentGroupResponse struct {
	ID                int64                                        `json:"id"`
	Type              string                                       `json:"type"`
	Name              string                                       `json:"name"`
	AllowSubscription bool                                         `json:"allowSubscription"`
	Description       *string                                      `json:"description,omitempty"`
	Status            *V4StatusPagesComponentGroupsComponentStatus `json:"status,omitempty"`
	UnderMaintenance  *bool                                        `json:"underMaintenance,omitempty"`
	StatusMaintenance *V4StatusPagesComponentGroupsComponentStatus `json:"statusMaintenance,omitempty"`
	Components        []V4StatusPagesComponentGroupsComponent      `json:"components,omitempty"`
	IsHidden          *bool                                        `json:"isHidden,omitempty"`
}

func (v *V4StatusPagesComponentGroupsComponentGroupResponse) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V4StatusPagesComponentGroupsComponentGroupResponse) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *V4StatusPagesComponentGroupsComponentGroupResponse) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V4StatusPagesComponentGroupsComponentGroupResponse) GetAllowSubscription() bool {
	if v == nil {
		return false
	}
	return v.AllowSubscription
}

func (v *V4StatusPagesComponentGroupsComponentGroupResponse) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V4StatusPagesComponentGroupsComponentGroupResponse) GetStatus() *V4StatusPagesComponentGroupsComponentStatus {
	if v == nil {
		return nil
	}
	return v.Status
}

func (v *V4StatusPagesComponentGroupsComponentGroupResponse) GetUnderMaintenance() *bool {
	if v == nil {
		return nil
	}
	return v.UnderMaintenance
}

func (v *V4StatusPagesComponentGroupsComponentGroupResponse) GetStatusMaintenance() *V4StatusPagesComponentGroupsComponentStatus {
	if v == nil {
		return nil
	}
	return v.StatusMaintenance
}

func (v *V4StatusPagesComponentGroupsComponentGroupResponse) GetComponents() []V4StatusPagesComponentGroupsComponent {
	if v == nil {
		return nil
	}
	return v.Components
}

func (v *V4StatusPagesComponentGroupsComponentGroupResponse) GetIsHidden() *bool {
	if v == nil {
		return nil
	}
	return v.IsHidden
}
