// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesComponentsGetComponentByIDResponse struct {
	ID               int64  `json:"id"`
	PageID           int64  `json:"pageID"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	StatusID         *int64 `json:"statusID,omitempty"`
	UnderMaintenance bool   `json:"underMaintenance"`
}

func (v *V4StatusPagesComponentsGetComponentByIDResponse) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V4StatusPagesComponentsGetComponentByIDResponse) GetPageID() int64 {
	if v == nil {
		return 0
	}
	return v.PageID
}

func (v *V4StatusPagesComponentsGetComponentByIDResponse) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V4StatusPagesComponentsGetComponentByIDResponse) GetDescription() string {
	if v == nil {
		return ""
	}
	return v.Description
}

func (v *V4StatusPagesComponentsGetComponentByIDResponse) GetStatusID() *int64 {
	if v == nil {
		return nil
	}
	return v.StatusID
}

func (v *V4StatusPagesComponentsGetComponentByIDResponse) GetUnderMaintenance() bool {
	if v == nil {
		return false
	}
	return v.UnderMaintenance
}
