// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesStatusPageStatusesResponse struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Status      string `json:"status"`
	Description string `json:"description"`
	Color       string `json:"color"`
}

func (v *V4StatusPagesStatusPageStatusesResponse) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V4StatusPagesStatusPageStatusesResponse) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V4StatusPagesStatusPageStatusesResponse) GetStatus() string {
	if v == nil {
		return ""
	}
	return v.Status
}

func (v *V4StatusPagesStatusPageStatusesResponse) GetDescription() string {
	if v == nil {
		return ""
	}
	return v.Description
}

func (v *V4StatusPagesStatusPageStatusesResponse) GetColor() string {
	if v == nil {
		return ""
	}
	return v.Color
}
