// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesComponentsComponent struct {
	ID                *int64                                  `json:"id,omitempty"`
	Type              *string                                 `json:"type,omitempty"`
	Name              *string                                 `json:"name,omitempty"`
	AllowSubscription *bool                                   `json:"allowSubscription,omitempty"`
	Description       *string                                 `json:"description,omitempty"`
	Status            *V4StatusPagesComponentsComponentStatus `json:"status,omitempty"`
	UnderMaintenance  *bool                                   `json:"underMaintenance,omitempty"`
	StatusMaintenance *V4StatusPagesComponentsComponentStatus `json:"statusMaintenance,omitempty"`
	Components        []V4StatusPagesComponentsComponent      `json:"components,omitempty"`
	IsHidden          *bool                                   `json:"isHidden,omitempty"`
}

func (v *V4StatusPagesComponentsComponent) GetID() *int64 {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V4StatusPagesComponentsComponent) GetType() *string {
	if v == nil {
		return nil
	}
	return v.Type
}

func (v *V4StatusPagesComponentsComponent) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V4StatusPagesComponentsComponent) GetAllowSubscription() *bool {
	if v == nil {
		return nil
	}
	return v.AllowSubscription
}

func (v *V4StatusPagesComponentsComponent) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V4StatusPagesComponentsComponent) GetStatus() *V4StatusPagesComponentsComponentStatus {
	if v == nil {
		return nil
	}
	return v.Status
}

func (v *V4StatusPagesComponentsComponent) GetUnderMaintenance() *bool {
	if v == nil {
		return nil
	}
	return v.UnderMaintenance
}

func (v *V4StatusPagesComponentsComponent) GetStatusMaintenance() *V4StatusPagesComponentsComponentStatus {
	if v == nil {
		return nil
	}
	return v.StatusMaintenance
}

func (v *V4StatusPagesComponentsComponent) GetComponents() []V4StatusPagesComponentsComponent {
	if v == nil {
		return nil
	}
	return v.Components
}

func (v *V4StatusPagesComponentsComponent) GetIsHidden() *bool {
	if v == nil {
		return nil
	}
	return v.IsHidden
}
