// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesNewStatusPageThemeColor struct {
	Primary   *string `json:"primary,omitempty"`
	Secondary *string `json:"secondary,omitempty"`
}

func (v *V4StatusPagesNewStatusPageThemeColor) GetPrimary() *string {
	if v == nil {
		return nil
	}
	return v.Primary
}

func (v *V4StatusPagesNewStatusPageThemeColor) GetSecondary() *string {
	if v == nil {
		return nil
	}
	return v.Secondary
}
