// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesIssuesIssueDetail struct {
	State         *V4StatusPagesIssuesComponentStatus    `json:"state,omitempty"`
	StateMessages []V4StatusPagesIssuesIssueStateMessage `json:"stateMessages,omitempty"`
}

func (v *V4StatusPagesIssuesIssueDetail) GetState() *V4StatusPagesIssuesComponentStatus {
	if v == nil {
		return nil
	}
	return v.State
}

func (v *V4StatusPagesIssuesIssueDetail) GetStateMessages() []V4StatusPagesIssuesIssueStateMessage {
	if v == nil {
		return nil
	}
	return v.StateMessages
}
