// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V4StatusPagesIssuesIssueStateMessage struct {
	ID        *int64     `json:"id,omitempty"`
	Text      *string    `json:"text,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

func (v V4StatusPagesIssuesIssueStateMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V4StatusPagesIssuesIssueStateMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V4StatusPagesIssuesIssueStateMessage) GetID() *int64 {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V4StatusPagesIssuesIssueStateMessage) GetText() *string {
	if v == nil {
		return nil
	}
	return v.Text
}

func (v *V4StatusPagesIssuesIssueStateMessage) GetTimestamp() *time.Time {
	if v == nil {
		return nil
	}
	return v.Timestamp
}
