// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesIssuesUpdateIssueResponse struct {
	ID           int64   `json:"id"`
	ComponentIDs []int64 `json:"componentIDs"`
	Title        string  `json:"title"`
}

func (v *V4StatusPagesIssuesUpdateIssueResponse) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V4StatusPagesIssuesUpdateIssueResponse) GetComponentIDs() []int64 {
	if v == nil {
		return []int64{}
	}
	return v.ComponentIDs
}

func (v *V4StatusPagesIssuesUpdateIssueResponse) GetTitle() string {
	if v == nil {
		return ""
	}
	return v.Title
}
