// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V4StatusPagesIssuesListStatusPageIssueStatesResponse struct {
	ID             int64      `json:"ID"`
	Idx            int64      `json:"Idx"`
	PageID         int64      `json:"PageID"`
	Name           string     `json:"Name"`
	Color          string     `json:"Color"`
	DefaultMessage string     `json:"DefaultMessage"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      time.Time  `json:"updatedAt"`
	DeletedAt      *time.Time `json:"deletedAt"`
}

func (v V4StatusPagesIssuesListStatusPageIssueStatesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V4StatusPagesIssuesListStatusPageIssueStatesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"ID", "Idx", "PageID", "Name", "Color", "DefaultMessage", "createdAt", "updatedAt"}); err != nil {
		return err
	}
	return nil
}

func (v *V4StatusPagesIssuesListStatusPageIssueStatesResponse) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V4StatusPagesIssuesListStatusPageIssueStatesResponse) GetIdx() int64 {
	if v == nil {
		return 0
	}
	return v.Idx
}

func (v *V4StatusPagesIssuesListStatusPageIssueStatesResponse) GetPageID() int64 {
	if v == nil {
		return 0
	}
	return v.PageID
}

func (v *V4StatusPagesIssuesListStatusPageIssueStatesResponse) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V4StatusPagesIssuesListStatusPageIssueStatesResponse) GetColor() string {
	if v == nil {
		return ""
	}
	return v.Color
}

func (v *V4StatusPagesIssuesListStatusPageIssueStatesResponse) GetDefaultMessage() string {
	if v == nil {
		return ""
	}
	return v.DefaultMessage
}

func (v *V4StatusPagesIssuesListStatusPageIssueStatesResponse) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *V4StatusPagesIssuesListStatusPageIssueStatesResponse) GetUpdatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.UpdatedAt
}

func (v *V4StatusPagesIssuesListStatusPageIssueStatesResponse) GetDeletedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.DeletedAt
}
