// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesUpdateStatusPageByIDRequestThemeColor struct {
	Primary   string `json:"primary"`
	Secondary string `json:"secondary"`
}

func (v *V4StatusPagesUpdateStatusPageByIDRequestThemeColor) GetPrimary() string {
	if v == nil {
		return ""
	}
	return v.Primary
}

func (v *V4StatusPagesUpdateStatusPageByIDRequestThemeColor) GetSecondary() string {
	if v == nil {
		return ""
	}
	return v.Secondary
}

type V4StatusPagesUpdateStatusPageByIDRequestComponent1 struct {
	Type              *string `json:"type,omitempty"`
	Name              *string `json:"name,omitempty"`
	AllowSubscription *bool   `json:"allowSubscription,omitempty"`
	Description       *string `json:"description,omitempty"`
	ServiceID         *string `json:"serviceID,omitempty"`
}

func (v *V4StatusPagesUpdateStatusPageByIDRequestComponent1) GetType() *string {
	if v == nil {
		return nil
	}
	return v.Type
}

func (v *V4StatusPagesUpdateStatusPageByIDRequestComponent1) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V4StatusPagesUpdateStatusPageByIDRequestComponent1) GetAllowSubscription() *bool {
	if v == nil {
		return nil
	}
	return v.AllowSubscription
}

func (v *V4StatusPagesUpdateStatusPageByIDRequestComponent1) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V4StatusPagesUpdateStatusPageByIDRequestComponent1) GetServiceID() *string {
	if v == nil {
		return nil
	}
	return v.ServiceID
}

type V4StatusPagesUpdateStatusPageByIDRequestComponent2 struct {
	Type              *string                                              `json:"type,omitempty"`
	Name              *string                                              `json:"name,omitempty"`
	AllowSubscription *bool                                                `json:"allowSubscription,omitempty"`
	Description       *string                                              `json:"description,omitempty"`
	Components        []V4StatusPagesUpdateStatusPageByIDRequestComponent1 `json:"components,omitempty"`
}

func (v *V4StatusPagesUpdateStatusPageByIDRequestComponent2) GetType() *string {
	if v == nil {
		return nil
	}
	return v.Type
}

func (v *V4StatusPagesUpdateStatusPageByIDRequestComponent2) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V4StatusPagesUpdateStatusPageByIDRequestComponent2) GetAllowSubscription() *bool {
	if v == nil {
		return nil
	}
	return v.AllowSubscription
}

func (v *V4StatusPagesUpdateStatusPageByIDRequestComponent2) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V4StatusPagesUpdateStatusPageByIDRequestComponent2) GetComponents() []V4StatusPagesUpdateStatusPageByIDRequestComponent1 {
	if v == nil {
		return nil
	}
	return v.Components
}

type V4StatusPagesUpdateStatusPageByIDRequest struct {
	Name                         string                                               `json:"name"`
	Description                  *string                                              `json:"description,omitempty"`
	IsPublic                     bool                                                 `json:"isPublic"`
	DomainName                   string                                               `json:"domainName"`
	CustomDomainName             *string                                              `json:"customDomainName,omitempty"`
	LogoURL                      *string                                              `json:"logoUrl,omitempty"`
	Timezone                     *string                                              `json:"timezone,omitempty"`
	TeamID                       string                                               `json:"teamID"`
	ThemeColor                   V4StatusPagesUpdateStatusPageByIDRequestThemeColor   `json:"themeColor"`
	AllowComponentsSubscription  *bool                                                `json:"allowComponentsSubscription,omitempty"`
	AllowMaintenanceSubscription *bool                                                `json:"allowMaintenanceSubscription,omitempty"`
	AllowWebhookSubscription     *bool                                                `json:"allowWebhookSubscription,omitempty"`
	Components                   []V4StatusPagesUpdateStatusPageByIDRequestComponent2 `json:"components,omitempty"`
	ContactEmail                 string                                               `json:"contactEmail"`
	IsCustomDomainEnabled        *bool                                                `json:"isCustomDomainEnabled,omitempty"`
	HideFromSearchEngines        *bool                                                `json:"hideFromSearchEngines,omitempty"`
	OwnerType                    string                                               `json:"ownerType"`
	OwnerID                      string                                               `json:"ownerID"`
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetIsPublic() bool {
	if v == nil {
		return false
	}
	return v.IsPublic
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetDomainName() string {
	if v == nil {
		return ""
	}
	return v.DomainName
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetCustomDomainName() *string {
	if v == nil {
		return nil
	}
	return v.CustomDomainName
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetLogoURL() *string {
	if v == nil {
		return nil
	}
	return v.LogoURL
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetTimezone() *string {
	if v == nil {
		return nil
	}
	return v.Timezone
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetTeamID() string {
	if v == nil {
		return ""
	}
	return v.TeamID
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetThemeColor() V4StatusPagesUpdateStatusPageByIDRequestThemeColor {
	if v == nil {
		return V4StatusPagesUpdateStatusPageByIDRequestThemeColor{}
	}
	return v.ThemeColor
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetAllowComponentsSubscription() *bool {
	if v == nil {
		return nil
	}
	return v.AllowComponentsSubscription
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetAllowMaintenanceSubscription() *bool {
	if v == nil {
		return nil
	}
	return v.AllowMaintenanceSubscription
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetAllowWebhookSubscription() *bool {
	if v == nil {
		return nil
	}
	return v.AllowWebhookSubscription
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetComponents() []V4StatusPagesUpdateStatusPageByIDRequestComponent2 {
	if v == nil {
		return nil
	}
	return v.Components
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetContactEmail() string {
	if v == nil {
		return ""
	}
	return v.ContactEmail
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetIsCustomDomainEnabled() *bool {
	if v == nil {
		return nil
	}
	return v.IsCustomDomainEnabled
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetHideFromSearchEngines() *bool {
	if v == nil {
		return nil
	}
	return v.HideFromSearchEngines
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetOwnerType() string {
	if v == nil {
		return ""
	}
	return v.OwnerType
}

func (v *V4StatusPagesUpdateStatusPageByIDRequest) GetOwnerID() string {
	if v == nil {
		return ""
	}
	return v.OwnerID
}
