// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 465922eace8f

package components

type V4StatusPagesTotalSubscribersCount struct {
	TotalCount int64 `json:"totalCount"`
}

func (v *V4StatusPagesTotalSubscribersCount) GetTotalCount() int64 {
	if v == nil {
		return 0
	}
	return v.TotalCount
}
