// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V4StatusPagesMaintenancesCreateMaintenanceResponse struct {
	ID         int64     `json:"id"`
	Title      string    `json:"title"`
	PageID     int64     `json:"pageID"`
	Note       string    `json:"note"`
	Components []int64   `json:"components,omitempty"`
	StartTime  time.Time `json:"startTime"`
	EndTime    time.Time `json:"endTime"`
}

func (v V4StatusPagesMaintenancesCreateMaintenanceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"id", "title", "pageID", "note", "startTime", "endTime"}); err != nil {
		return err
	}
	return nil
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceResponse) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceResponse) GetTitle() string {
	if v == nil {
		return ""
	}
	return v.Title
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceResponse) GetPageID() int64 {
	if v == nil {
		return 0
	}
	return v.PageID
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceResponse) GetNote() string {
	if v == nil {
		return ""
	}
	return v.Note
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceResponse) GetComponents() []int64 {
	if v == nil {
		return nil
	}
	return v.Components
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceResponse) GetStartTime() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.StartTime
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceResponse) GetEndTime() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.EndTime
}
