// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesStatusPageSubscriberComponent struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (v *V4StatusPagesStatusPageSubscriberComponent) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V4StatusPagesStatusPageSubscriberComponent) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}
