// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesDeleteSubscriberByIDResponse struct {
	ID         int64  `json:"id"`
	Type       string `json:"type"`
	EmailID    string `json:"emailID"`
	WebhookURL string `json:"webhookURL"`
}

func (v *V4StatusPagesDeleteSubscriberByIDResponse) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V4StatusPagesDeleteSubscriberByIDResponse) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *V4StatusPagesDeleteSubscriberByIDResponse) GetEmailID() string {
	if v == nil {
		return ""
	}
	return v.EmailID
}

func (v *V4StatusPagesDeleteSubscriberByIDResponse) GetWebhookURL() string {
	if v == nil {
		return ""
	}
	return v.WebhookURL
}

// #region class-body-v4statuspagesdeletesubscriberbyidresponse
// #endregion class-body-v4statuspagesdeletesubscriberbyidresponse
