// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/SquadcastHub/squadcast-sdk-go/internal/utils"
	"time"
)

type V4StatusPagesMaintenancesCreateMaintenanceRequest struct {
	Title      string    `json:"title"`
	Note       string    `json:"note"`
	Components []int64   `json:"components"`
	StartTime  time.Time `json:"startTime"`
	EndTime    time.Time `json:"endTime"`
}

func (v V4StatusPagesMaintenancesCreateMaintenanceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"title", "note", "components", "startTime", "endTime"}); err != nil {
		return err
	}
	return nil
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceRequest) GetTitle() string {
	if v == nil {
		return ""
	}
	return v.Title
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceRequest) GetNote() string {
	if v == nil {
		return ""
	}
	return v.Note
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceRequest) GetComponents() []int64 {
	if v == nil {
		return []int64{}
	}
	return v.Components
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceRequest) GetStartTime() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.StartTime
}

func (v *V4StatusPagesMaintenancesCreateMaintenanceRequest) GetEndTime() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.EndTime
}
