// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesComponentGroupsGetComponentGroupByIDResponse struct {
	ID                int64   `json:"id"`
	PageID            int64   `json:"pageID"`
	Name              string  `json:"name"`
	Description       *string `json:"description,omitempty"`
	AllowSubscription bool    `json:"allowSubscription"`
}

func (v *V4StatusPagesComponentGroupsGetComponentGroupByIDResponse) GetID() int64 {
	if v == nil {
		return 0
	}
	return v.ID
}

func (v *V4StatusPagesComponentGroupsGetComponentGroupByIDResponse) GetPageID() int64 {
	if v == nil {
		return 0
	}
	return v.PageID
}

func (v *V4StatusPagesComponentGroupsGetComponentGroupByIDResponse) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V4StatusPagesComponentGroupsGetComponentGroupByIDResponse) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V4StatusPagesComponentGroupsGetComponentGroupByIDResponse) GetAllowSubscription() bool {
	if v == nil {
		return false
	}
	return v.AllowSubscription
}
