// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V4StatusPagesComponentsUpdateComponentByIDRequest struct {
	Name              string  `json:"name"`
	Description       *string `json:"description,omitempty"`
	AllowSubscription *bool   `json:"allowSubscription,omitempty"`
	GroupID           *string `json:"groupID,omitempty"`
	ServiceID         *string `json:"serviceID,omitempty"`
	BelongsToGroup    *string `json:"belongsToGroup,omitempty"`
}

func (v *V4StatusPagesComponentsUpdateComponentByIDRequest) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V4StatusPagesComponentsUpdateComponentByIDRequest) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V4StatusPagesComponentsUpdateComponentByIDRequest) GetAllowSubscription() *bool {
	if v == nil {
		return nil
	}
	return v.AllowSubscription
}

func (v *V4StatusPagesComponentsUpdateComponentByIDRequest) GetGroupID() *string {
	if v == nil {
		return nil
	}
	return v.GroupID
}

func (v *V4StatusPagesComponentsUpdateComponentByIDRequest) GetServiceID() *string {
	if v == nil {
		return nil
	}
	return v.ServiceID
}

func (v *V4StatusPagesComponentsUpdateComponentByIDRequest) GetBelongsToGroup() *string {
	if v == nil {
		return nil
	}
	return v.BelongsToGroup
}
