// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4e47077f88e2

package apierrors

import (
	"encoding/json"
	"github.com/solarwinds/squadcast-sdk-go/models/components"
)

type CommonV4Error struct {
	Error_   components.Error        `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &CommonV4Error{}

func (e *CommonV4Error) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
